---
title: "R Notebook"
output: html_notebook
---


```{r}

library(Seurat)
library(SeuratDisk)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(patchwork)
library(dplyr)
library(data.table)
library(clustree)
library(reshape2)
library(tidyr)
library(gridExtra)
library(stringr)
library(plyr)
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_integration_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/xgboost_train.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/plottingFxns.R")
colors_list <- GetColors()

obj.ctx.glutamatergic.mouse <- readRDS("E:/STOmics/seurat/Mouse/mouse_stereoseq_ctx_glutamatergic_COLs_EXT_integrated.rds")
obj.ctx.glutamatergic.opossum <- readRDS("E:/STOmics/seurat/Opossum/opossum_stereoseq_ctx_glutamatergic_COLs_EXT_integrated.rds")

```


```{r}

colors <- hcl.colors(8, palette = "Dynamic")

```


```{r, fig.width=7, fig.height=5}

Idents(obj.ctx.glutamatergic.mouse) <- "subclass_nn"
levels(obj.ctx.glutamatergic.mouse) <- c("L2/3", "L4", "L5IT", "L5NP", "L5PT", "L6IT", "L6CT", "L6b")
ImageDimPlot(obj.ctx.glutamatergic.mouse, fov = "COL", size = 3, cols = colors, axes = TRUE)

```


```{r, fig.width=7, fig.height=5}

Idents(obj.ctx.glutamatergic.opossum) <- "subclass_nn"
levels(obj.ctx.glutamatergic.opossum) <- c("IT_A", "IT_B", "IT_C", "L5NP", "L5PT", "IT_D", "L6CT", "L6b")
ImageDimPlot(obj.ctx.glutamatergic.opossum, fov = "COL", size = 3, cols = colors, axes = TRUE)

```


```{r}

library(Seurat)
library(spatstat)
library(ineq)
library(geometry)
library(ggplot2)

# Function to calculate density-based Gini index
calc_density_gini <- function(coords, sigma = NULL, grid_res = 512, expand_dist = 0.1){
  xrange <- range(coords$x)
  yrange <- range(coords$y)
  window <- expand.owin(owin(xrange, yrange), distance = expand_dist)
  points_ppp <- ppp(coords$x, coords$y, window = window)
  dens <- density(points_ppp, sigma = sigma, dimyx = c(grid_res, grid_res))
  dens_values <- dens$v[dens$v > 0]
  ineq::Gini(as.vector(dens_values))
}

calc_convex_hull_area <- function(coords){
  hull_indices <- chull(coords$x, coords$y)
  hull_coords <- coords[hull_indices, ]
  area <- geometry::polyarea(hull_coords$x, hull_coords$y)
  return(area)
}

comps <- list(c("L2/3", "IT_A"), c("L4", "IT_B"), c("L5IT", "IT_C"), c("L6IT", "IT_D"))
results <- data.frame()

for (s in comps) {
  coords_mouse_all <- GetTissueCoordinates(obj.ctx.glutamatergic.mouse, image = "COL")
  coords_mouse <- coords_mouse_all[obj.ctx.glutamatergic.mouse$subclass_nn == s[1],]
  gini_mouse <- calc_density_gini(coords_mouse)
  hull_mouse <- calc_convex_hull_area(coords_mouse)
  
  coords_opossum_all <- GetTissueCoordinates(obj.ctx.glutamatergic.opossum, image = "COL")
  coords_opossum <- coords_opossum_all[obj.ctx.glutamatergic.opossum$subclass_nn == s[2],]
  gini_opossum <- calc_density_gini(coords_opossum)
  hull_opossum <- calc_convex_hull_area(coords_opossum)
  
  results_df <- rbind(results_df, 
                      data.frame(Subclass_Pair = paste(s[1], s[2], sep = " vs "),
                                 Species = c("Mouse", "Opossum"),
                                 ConvexHull = c(hull_mouse, hull_opossum),
                                 GiniIndex = c(gini_mouse, gini_opossum)))
}

# Scatterplot
p <- ggplot(results_df, aes(x = ConvexHull, y = GiniIndex, color = Species)) +
  geom_point(size = 4) +
  geom_text(aes(label = Subclass_Pair), vjust = -1, size = 3) +
  labs(x = "Convex Hull Area", y = "Density-based Gini Index", 
       title = "Spatial Restriction Comparison (Mouse vs Opossum)") +
  theme_minimal()

print(p)

```





























