---
title: "R Notebook"
output: html_notebook
---


```{r}

library(Seurat)
library(SeuratDisk)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(patchwork)
library(dplyr)
library(data.table)
library(clustree)
library(reshape2)
library(tidyr)
library(gridExtra)
library(stringr)
library(plyr)
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_integration_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/xgboost_train.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/plottingFxns.R")
colors_list <- GetColors()

obj.glutamatergic <- readRDS("E:/Transcriptomics_V1/Mouse/seurat/mouse_v1_P38_glutamatergic_processed.rds")
obj.glutamatergic$class <- "glutamatergic"
obj.gabaergic <- readRDS("E:/Transcriptomics_V1/Mouse/seurat/mouse_v1_P38_gabaergic_processed.rds")
obj.gabaergic$class <- "gabaergic"
obj.nonneuronal <- readRDS("E:/Transcriptomics_V1/Mouse/seurat/mouse_v1_P38_nonneuronal_processed.rds")

obj <- merge(obj.glutamatergic, y = c(obj.gabaergic, obj.nonneuronal))

obj.ctx <- readRDS("E:/STOmics/seurat/Mouse/mouse_stereoseq_ctx_COLS.rds")

```


```{r}

obj$method <- "snRNA-seq"
obj.ctx$method <- "Stereo-seq"
obj.i <- IntegrateObjects(obj, obj.ctx, resolutions = c(0.5), subsample = TRUE)

```


```{r}

DimPlot(obj.i, group.by = "class", label = TRUE) + NoLegend() + xlim(-12, 12) + ylim(-12, 12) + coord_equal()
DimPlot(obj.i, group.by = "subclass", label = TRUE) + NoLegend() + xlim(-12, 12) + ylim(-12, 12) + coord_equal()

```


```{r}

obj.i <- LabelByNearestNeighbors(obj.i, "class", fraction = 0.05, n.neighbors = 500)

```


```{r}

DimPlot(obj.i, group.by = "class_nn", label = TRUE) + NoLegend() + xlim(-12, 12) + ylim(-12, 12) + coord_equal()

```


```{r}

obj.ctx$class_nn <- obj.i$class_nn[colnames(obj.ctx)]
obj.ctx <- subset(obj.ctx, class_nn %in% c("glutamatergic", "gabaergic", "nonneuronal"))

```


```{r}

obj.i <- IntegrateObjects(obj, obj.ctx, resolutions = c(0.5), subsample = FALSE)

```


```{r}

DimPlot(obj.i, group.by = "class_nn", label = TRUE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

obj.i <- LabelByNearestNeighbors(obj.i, "class", fraction = 0.25, n.neighbors = 500)

```


```{r}

DimPlot(obj.i, group.by = "class_nn", label = TRUE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

obj.i <- LabelByNearestNeighbors(obj.i, "subclass", fraction = 0.25, n.neighbors = 100)

```


```{r}

DimPlot(obj.i, group.by = "subclass_nn", label = TRUE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

saveRDS(obj.i, "E:/STOmics/seurat/Mouse/mouse_stereoseq_ctx_COLs_integrated.rds")

```


```{r}

assigned_subclasses <- obj.i$subclass_nn[!is.na(obj.i$subclass_nn)]
cell_ids <- names(assigned_subclasses)
obj.ctx$subclass_nn <- NA
obj.ctx$subclass_nn[cell_ids] <- assigned_subclasses

```


```{r}

Idents(obj.ctx) <- "subclass_nn"
ImageDimPlot(obj.ctx, fov = "COL", size = 3)
colors_list[["None"]] <- "#34E1EB"
PlotClusterImageDim(obj.ctx, ident = "subclass_nn", colors_list = colors_list)

```


```{r}

colors <- hcl.colors(8, palette = "Dynamic")

```


```{r, fig.width=7, fig.height=5}

obj.ctx.glutamatergic <- subset(obj.ctx, subclass_nn %in% c("L2/3", "L4", "L5IT", "L6IT", "L5NP", "L5PT", "L6CT", "L6b"))
Idents(obj.ctx.glutamatergic) <- "subclass_nn"
levels(obj.ctx.glutamatergic) <- c("L2/3", "L4", "L5IT", "L5NP", "L5PT", "L6IT", "L6CT", "L6b")
p <- ImageDimPlot(obj.ctx.glutamatergic, fov = "COL", size = 3, cols = colors, axes = TRUE)

ggsave("E:/Opossum_Paper/Figure 3/Mouse_Glutamatergic_Column.svg", plot = p, width = 7, height = 5)

```


```{r, fig.width=7, fig.height=5}

obj.ctx.IT <- subset(obj.ctx, subclass_nn %in% c("L2/3", "L4", "L5IT"))
Idents(obj.ctx.IT) <- "subclass_nn"
levels(obj.ctx.IT) <- c("L2/3", "L4", "L5IT")
p <- ImageDimPlot(obj.ctx.IT, fov = "COL", size = 3, cols = colors, axes = TRUE)

ggsave("E:/Opossum_Paper/Figure 3/Mouse_IT_Column.svg", plot = p, width = 7, height = 5)

```


```{r}

# 2. Extract coordinates and subclass labels
coords <- GetTissueCoordinates(obj.ctx.glutamatergic)
df <- data.frame(
  y = coords$x,
  subclass = obj.ctx.glutamatergic$subclass_nn
)

# 3. Filter and set subclass as a factor to enforce order
df <- df %>%
  filter(!is.na(subclass) & subclass != "None") %>%
  mutate(subclass = factor(subclass, levels = c("L2/3", "L4", "L5IT", "L6IT", "L5NP", "L5PT", "L6CT", "L6b")))

# 4. Plot smooth density profiles
p <- ggplot(df, aes(x = y, color = subclass)) +
  geom_density(
    size = 2,
    # adjust = 0.2         # Smoothing factor (increase if you want smoother lines)
  ) +
  scale_color_manual(values = colors) +
  scale_fill_manual(values = colors) +
  theme_minimal() +
  theme(
    legend.title = element_blank(),
    aspect.ratio = 1
  ) + coord_flip()

ggsave("E:/Opossum_Paper/Figure 3/Mouse_Glutamatergic_Density.svg", plot = p)

# Outlined histograms without bin borders
p <- ggplot(df, aes(x = y, color = subclass)) +
  stat_bin(
    geom = "step",
    bins = 30,
    size = 1  # Adjust line thickness
  ) +
  scale_color_manual(values = colors) +
  theme_minimal() +
  theme(
    legend.title = element_blank(),
    aspect.ratio = 1
  ) + coord_flip()

ggsave("E:/Opossum_Paper/Figure 3/Mouse_Glutamatergic_Histogram.svg", plot = p)

```


```{r, fig.width=7, fig.height=5}

obj.ctx.gabaergic <- subset(obj.ctx, subclass_nn %in% c("Pvalb", "Sst", "Vip", "Lamp5", "Frem1", "Stac"))
Idents(obj.ctx.gabaergic) <- "subclass_nn"
levels(obj.ctx.gabaergic) <- c("Pvalb", "Sst", "Vip", "Lamp5", "Frem1", "Stac")
p <- ImageDimPlot(obj.ctx.gabaergic, fov = "COL", size = 3, cols = colors[1:6], axes = TRUE)

ggsave("E:/Opossum_Paper/Figure 3/Mouse_GABAergic_Column.svg", plot = p, width = 7, height = 5)

```


```{r}

# 2. Extract coordinates and subclass labels
coords <- GetTissueCoordinates(obj.ctx.gabaergic)
df <- data.frame(
  y = coords$x,
  subclass = obj.ctx.gabaergic$subclass_nn
)

# 3. Filter and set subclass as a factor to enforce order
df <- df %>%
  filter(!is.na(subclass) & subclass != "None") %>%
  mutate(subclass = factor(subclass, levels = c("Pvalb", "Sst", "Vip", "Lamp5", "Frem1")))

# 4. Plot smooth density profiles
p <- ggplot(df, aes(x = y, color = subclass)) +
  geom_density(
    size = 2,
    # adjust = 0.2         # Smoothing factor (increase if you want smoother lines)
  ) +
  scale_color_manual(values = colors) +
  scale_fill_manual(values = colors) +
  theme_minimal() +
  theme(
    legend.title = element_blank(),
    aspect.ratio = 1
  ) + coord_flip()

ggsave("E:/Opossum_Paper/Figure 3/Mouse_GABAergic_Density.svg", plot = p)

# Outlined histograms without bin borders
p <- ggplot(df, aes(x = y, color = subclass)) +
  stat_bin(
    geom = "step",
    bins = 30,
    size = 1  # Adjust line thickness
  ) +
  scale_color_manual(values = colors) +
  theme_minimal() +
  theme(
    legend.title = element_blank(),
    aspect.ratio = 1
  ) + coord_flip()

ggsave("E:/Opossum_Paper/Figure 3/Mouse_GABAergic_Histogram.svg", plot = p)

```


```{r, fig.width=7, fig.height=5}

obj.ctx.nonneuronal <- subset(obj.ctx, subclass_nn %in% c("OD", "OPC", "Micro", "Astro", "Endo", "VLMC"))
Idents(obj.ctx.nonneuronal) <- "subclass_nn"
levels(obj.ctx.nonneuronal) <- c("OD", "OPC", "Micro", "Astro", "Endo", "VLMC")
p <- ImageDimPlot(obj.ctx.nonneuronal, fov = "COL", size = 3, cols = colors[1:6], axes = TRUE)

ggsave("E:/Opossum_Paper/Figure 3/Mouse_Nonneuronal_Column.svg", plot = p, width = 7, height = 5)

```


```{r}

# 2. Extract coordinates and subclass labels
coords <- GetTissueCoordinates(obj.ctx.nonneuronal)
df <- data.frame(
  y = coords$x,
  subclass = obj.ctx.nonneuronal$subclass_nn
)

# 3. Filter and set subclass as a factor to enforce order
df <- df %>%
  filter(!is.na(subclass) & subclass != "None") %>%
  mutate(subclass = factor(subclass, levels = c("OD", "OPC", "Micro", "Astro", "Endo")))

# 4. Plot smooth density profiles
p <- ggplot(df, aes(x = y, color = subclass)) +
  geom_density(
    size = 2,
    # adjust = 0.2         # Smoothing factor (increase if you want smoother lines)
  ) +
  scale_color_manual(values = colors) +
  scale_fill_manual(values = colors) +
  theme_minimal() +
  theme(
    legend.title = element_blank(),
    aspect.ratio = 1
  ) + coord_flip()

ggsave("E:/Opossum_Paper/Figure 3/Mouse_Nonneuronal_Density.svg", plot = p)

# Outlined histograms without bin borders
p <- ggplot(df, aes(x = y, color = subclass)) +
  stat_bin(
    geom = "step",
    bins = 30,
    size = 1  # Adjust line thickness
  ) +
  scale_color_manual(values = colors) +
  theme_minimal() +
  theme(
    legend.title = element_blank(),
    aspect.ratio = 1
  ) + coord_flip()

ggsave("E:/Opossum_Paper/Figure 3/Mouse_Nonneuronal_Histogram.svg", plot = p)

```


```{r}

saveRDS(obj.ctx.glutamatergic, "E:/STOmics/seurat/Opossum/mouse_stereoseq_ctx_glutamatergic_COLs_EXT_integrated.rds")
saveRDS(obj.ctx.gabaergic, "E:/STOmics/seurat/Opossum/mouse_stereoseq_ctx_gabaergic_COLs_EXT_integrated.rds")
saveRDS(obj.ctx.nonneuronal, "E:/STOmics/seurat/Opossum/mouse_stereoseq_ctx_nonneuronal_COLs_EXT_integrated.rds")

```























