---
title: "R Notebook"
output: html_notebook
---


```{r}

library(Seurat)
library(SeuratObject)
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_integration_functions.R")

data.path <- "E:/STOmics/seurat/Mouse/raw/"
obj.data <- Read10X(data.path, gene.column = 2)
obj <- CreateSeuratObject(counts = obj.data, project = "Mouse_V1_Stereo-seq")

obj$species <- "Mouse"
X <- read.csv(paste(data.path, "x_coords.csv", sep = ""), header = FALSE) * -1
obj <- AddMetaData(obj, X$V1, "X")
Y <- read.csv(paste(data.path, "y_coords.csv", sep = ""), header = FALSE) * -1
obj <- AddMetaData(obj, Y$V1, "Y")

crops <- list(theta = c(45, 10, -8, -30), 
              x1 = c(-19450, -17500, -7650, -1700), 
              x2 = c(-17000, -16300, -6250, -250), 
              y1 = c(950, -3800, -6850, -14100), 
              y2 = c(2500, -2400, -5600, -12700))

# Define the rotation angle in degrees
rotation_angle <- -30  # Rotate by 30 degrees
theta <- rotation_angle * pi / 180  # Convert to radians

# Get current coordinates
coords <- as.matrix(obj@meta.data[, c("X", "Y")])

# Define rotation matrix
rotation_matrix <- matrix(
  c(cos(theta), -sin(theta),
    sin(theta),  cos(theta)),
  nrow = 2
)

# Apply rotation
rotated_coords <- coords %*% rotation_matrix

# Update metadata
obj$X_rotated <- rotated_coords[, 1]
obj$Y_rotated <- rotated_coords[, 2]

cents.df <- data.frame(X, Y)
colnames(cents.df) <- c("X", "Y")
rownames(cents.df) <- colnames(obj)

cents.df$X <- obj$X_rotated
cents.df$Y <- obj$Y_rotated

cents <- CreateCentroids(cents.df)
fov <- CreateFOV(
  cents, 
  type = "centroids",
  assay = "RNA",
  key = Key("FOV", quiet = TRUE)
)

fov <- fov[Cells(obj)]

obj[["FOV"]] <- fov

column.coords <- Crop(obj[["FOV"]], x = c(-1700, -250), y = c(-14100, -12700), coords = "plot")
obj[["COL4"]] <- column.coords

```


```{r, fig.width=10}

ImageDimPlot(obj, fov = "COL4", cols = "red", size = 3)
# ImageFeaturePlot(obj, "nCount_RNA", max.cutoff = 1000)
# ImageFeaturePlot(obj, "", max.cutoff = 10, axes = TRUE)

```






```{r}

obj.ctx <- subset(obj, cells = Cells(obj[["COL4"]]))
saveRDS(obj.ctx, "E:/STOmics/seurat/Mouse/mouse_stereoseq_ctx_COL4.rds")

```

