---
title: "R Notebook"
output: html_notebook
---

```{r}

library(Seurat)
library(SeuratObject)
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_integration_functions.R")

objs.col <- list(COL1 = NA, COL2 = NA, COL3 = NA, COL4 = NA)

for (n in 1:4) {

  path <- paste0("E:/STOmics/seurat/Mouse/mouse_stereoseq_ctx_COL", n, ".rds")
  objs.col[[n]] <- readRDS(path)
  objs.col[[n]]$sample <- paste0("COL", n)
  
}

obj.mouse.col <- merge(objs.col[[1]], y = objs.col[2:4])
obj.mouse.col$Species <- "Mouse"

objs.col <- list(COL1 = NA, COL2 = NA, COL3 = NA)

for (n in 1:3) {

  path <- paste0("E:/STOmics/seurat/Opossum/opossum_stereoseq_ctx_COL", n, "_EXTEXT.rds")
  objs.col[[n]] <- readRDS(path)
  objs.col[[n]]$sample <- paste0("COL", n)
  
}

obj.opossum.col <- merge(objs.col[[1]], y = objs.col[2:3])
obj.opossum.col$Species <- "Opossum"

```


```{r}

obj.col <- merge(obj.mouse.col, y = obj.opossum.col)

```


```{r}

p <- VlnPlot(obj.col, "nFeature_RNA", group.by = "Species", pt.size = 0.01)
ggsave("E:/Opossum_Paper/Figure S3/nFeature_Stereo-seq.svg", plot = p, width = 3, height = 5)

p <- VlnPlot(obj.col, "nCount_RNA", group.by = "Species", pt.size = 0.01)
ggsave("E:/Opossum_Paper/Figure S3/nCount_Stereo-seq.svg", plot = p, width = 3, height = 5)

```


```{r}

# crops <- list(theta = c(-5, -7, -38), 
#               x1 = c(-9500, -7000, -125), 
#               x2 = c(-7500, -5000, 1045), 
#               y1 = c(-14300, -14600, -5650), 
#               y2 = c(-12800, -13050, -7000))

areas.opossum <- c((9500-7500)*(14300-12800), (7000-5000)*(14600-13050), (1045+125)*(7000-5650))
counts.opossum.tot <- c(2034, 1904, 1263)

# crops <- list(theta = c(45, 10, -8, -30), 
#               x1 = c(-19450, -17500, -7650, -1700), 
#               x2 = c(-17000, -16300, -6250, -250), 
#               y1 = c(950, -3800, -6850, -14100), 
#               y2 = c(2500, -2400, -5600, -12700))

areas.mouse <- c((19450-17000)*(2500-950), (17500-16300)*(3800-2400), (7650-6250)*(6850-5600), (1700-250)*(14100-12700))
counts.mouse.tot <- c(3551, 1580, 1910, 2098)

# Compute densities
densities.opossum <- (counts.opossum.tot / (areas.opossum * 2.5e-7))
densities.mouse <- (counts.mouse.tot / (areas.mouse * 2.5e-7))

# Combine into one dataframe
df <- data.frame(
  species = rep(c("Opossum", "Mouse"), times = c(length(densities.opossum), length(densities.mouse))),
  density = c(densities.opossum, densities.mouse)
)

# Plot
p <- ggplot(df, aes(x = species, y = density, fill = species)) +
  stat_summary(fun = mean, geom = "bar", width = 0.6, color = "black") +
  stat_summary(fun.data = mean_se, geom = "errorbar", width = 0.2) +
  geom_jitter(width = 0.15, size = 3, shape = 21, stroke = 1.2, aes(fill = species)) +
  scale_fill_manual(values = c("Opossum" = "#6baed6", "Mouse" = "#fd8d3c")) +
  labs(y = "Total Cell Density (per 10,000 µm²)", x = NULL,
       title = "Total Cell Density: Opossum vs Mouse") +
  theme_classic(base_size = 14) +
  theme(legend.position = "none")

ggsave("E:/Opossum_Paper/Figure S3/TotDensity_Stereo-seq.svg", plot = p, width = 3, height = 5)

# (counts.opossum.pv / areas.opossum) * 10000
# (counts.mouse.pv / areas.mouse) * 10000

```

