---
title: "R Notebook"
output: html_notebook
---

```{r, fig.height=3, fig.width=4.5}

library(ggplot2)
library(dplyr)

df <- read.csv("G:/Shared drives/Opossum transcriptomics/data/MERFISH_gaba.csv")

df$Area <- factor(df$Area, levels = c("VISp", "MOp", "PL"))

area_gabaergic <- ggplot(df, aes(x = factor(Subclass, level = c("Pvalb", "Sst", "Vip", "Lamp5", "Sncg")), y = Fraction, fill = Area)) +
    geom_bar(stat = "summary", fun = "mean", position = position_dodge(width = 0.8), width = 0.75) +
    geom_point(colour = "black", position = position_dodge(width = 0.8), size = 1) +
    scale_x_discrete(labels = c("Pvalb", "Sst", "Vip", "Lamp5", "Sncg")) +
    scale_y_continuous(breaks = c(0, 0.25, 0.5), expand = c(0, 0), limits = c(0, 0.5)) +
    guides(fill = guide_legend(override.aes = list(shape = NA))) +
    theme_classic() + theme(axis.text = element_text(color = "black"), legend.text = element_text(size = 10)) + 
    labs(x = NULL, y = "Fraction of GABAergic Cells", fill = NULL) + 
    scale_fill_manual("legend", values = c("VISp" = "#4d5fe2", "MOp" = "#aaaaaa", "PL" = "#ed4e42"))
  
# ggsave(file="G:/Shared drives/Opossum transcriptomics/figures/HMO_GABAergic_Subclass_Proportion.svg", plot=hmo_gabaergic, width=4.5, height=3, dpi=500)
ggsave(file="G:/Shared drives/Opossum transcriptomics/figures/Area_GABAergic_Subclass_Proportion.png", plot=area_gabaergic, width=4.5, height=3, dpi=500)

```


```{r, fig.height=3, fig.width=4.5}

library(ggplot2)
library(dplyr)

df <- read.csv("G:/Shared drives/Opossum transcriptomics/data/MERFISH_gaba_vis.csv")

df$Area <- factor(df$Area, levels = c("VISp", "VISl", "VISrl"))

ggplot(df, aes(x = factor(Subclass, level = c("Pvalb", "Sst", "Vip", "Lamp5", "Sncg")), y = Fraction, fill = Area)) +
    geom_bar(stat = "summary", fun = "mean", position = position_dodge(width = 0.8), width = 0.75) +
    geom_point(colour = "black", position = position_dodge(width = 0.8), size = 1) +
    scale_x_discrete(labels = c("Pvalb", "Sst", "Vip", "Lamp5", "Sncg")) +
    scale_y_continuous(breaks = c(0, 0.25, 0.5), expand = c(0, 0), limits = c(0, 0.5)) +
    guides(fill = guide_legend(override.aes = list(shape = NA))) +
    theme_classic() + theme(axis.text = element_text(color = "black"), legend.text = element_text(size = 10)) + 
    labs(x = NULL, y = "Fraction of GABAergic Cells", fill = NULL) + 
    scale_fill_manual("legend", values = c("VISp" = "#aaaaaa", "VISl" = "#a2bc8c", "VISrl" = "#c692b8"))

# ggsave(file="G:/Shared drives/Opossum transcriptomics/figures/HMO_GABAergic_Subclass_Proportion.svg", plot=hmo_gabaergic, width=4.5, height=3, dpi=500)
# ggsave(file="G:/Shared drives/Opossum transcriptomics/figures/HMO_GABAergic_Subclass_Proportion.png", plot=hmo_gabaergic, width=4.5, height=3, dpi=500)

```

