---
title: "R Notebook"
output: html_notebook
---


```{r}

obj.combined <- LoadH5Seurat("E:/Transcriptomics_v1/Opossum/seurat/opossum_v1_all_integrated.h5seurat")

```


```{r}

DimPlot(obj.combined, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.combined, reduction = "umap", group.by = "sample", raster = FALSE, shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined, "nFeature_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined, "nCount_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.combined, reduction = "umap", group.by = "predicted_doublets", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

DefaultAssay(obj.combined) <- "RNA"

FeaturePlot(obj.combined, reduction = "umap", features = c("Snap25"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined, reduction = "umap", features = c("Sv2b"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined, reduction = "umap", features = c("Cux2"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined, reduction = "umap", features = c("Gucy1a1"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined, reduction = "umap", features = c("Cdh22"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined, reduction = "umap", features = c("Rorb"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined, reduction = "umap", features = c("Kank1"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined, reduction = "umap", features = c("Fam163a"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined, reduction = "umap", features = c("Foxp2"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined, reduction = "umap", features = c("Myt1"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined, reduction = "umap", features = c("Cdh9"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

obj.opossum.glutamatergic <- subset(obj.combined, idents = c(1, 2, 3, 5, 6, 9, 10, 13, 16, 17, 18, 22, 23))

```


```{r}

obj.list.glutamatergic <- SplitObject(obj.opossum.glutamatergic, split.by = "sample")
for (o in 1:length(obj.list.glutamatergic)) {
  obj.list.glutamatergic[[o]] <- SCTransform(obj.list.glutamatergic[[o]], vst.flavor = "v2", return.only.var.genes = FALSE, verbose = FALSE)
}
features <- SelectIntegrationFeatures(object.list = obj.list.glutamatergic, nfeatures = 5000)
obj.list.glutamatergic <- PrepSCTIntegration(object.list = obj.list.glutamatergic, assay = "SCT", anchor.features = features)
anchors <- FindIntegrationAnchors(object.list = obj.list.glutamatergic, normalization.method = "SCT", anchor.features = features)
features.to.integrate <- Reduce(intersect, lapply(obj.list.glutamatergic, rownames))
obj.combined.glutamatergic <- IntegrateData(anchorset = anchors, normalization.method = "SCT", features.to.integrate = features.to.integrate)

```


```{r}

obj.combined.glutamatergic <- RunPCA(obj.combined.glutamatergic)
obj.combined.glutamatergic <- FindNeighbors(obj.combined.glutamatergic, dims = 1:30)
obj.combined.glutamatergic <- FindClusters(obj.combined.glutamatergic, resolution = 1, algorithm = 4, method = "igraph")
obj.combined.glutamatergic <- RunUMAP(obj.combined.glutamatergic, dims = 1:30, method="umap-learn")

```


```{r}

DimPlot(obj.combined.glutamatergic, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.combined.glutamatergic, reduction = "umap", group.by = "sample", raster = FALSE, shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, "nFeature_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, "nCount_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.combined.glutamatergic, reduction = "umap", group.by = "predicted_doublets", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
VlnPlot(obj.combined.glutamatergic, "nCount_RNA")

```


```{r}

DefaultAssay(obj.combined.glutamatergic) <- "RNA"

FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Snap25"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Gad2"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Pvalb"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Sst"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Sv2b"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Cux2"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Gucy1a1"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Cdh22"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Rorb"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Kank1"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Fam163a"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Foxp2"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Myt1"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Cdh9"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Ust"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Sorcs1"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Cald1"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

DotPlot(obj.combined.glutamatergic, features = c("Cux2", "Gucy1a1", 
                                                 "Rorb", "Kank1", "Fam163a", 
                                                 "Myt1", "Plxna1", 
                                                 "Trpc4", "Sorcs1", "Gadl1", 
                                                 "Nxph1", "Ust", 
                                                 "Cdh9", "Cald1", 
                                                 "Syt6", "Foxp2", 
                                                 "Wasf3", "Stk10"), scale = FALSE) + coord_flip()

```


```{r}

obj.combined.glutamatergic.pre1 <- obj.combined.glutamatergic
obj.combined.glutamatergic <- subset(obj.combined.glutamatergic, idents = c(7, 15, 19, 21), invert = TRUE)

```


```{r}

obj.list.glutamatergic <- SplitObject(obj.combined.glutamatergic, split.by = "sample")
for (o in 1:length(obj.list.glutamatergic)) {
  obj.list.glutamatergic[[o]] <- SCTransform(obj.list.glutamatergic[[o]], vst.flavor = "v2", return.only.var.genes = FALSE, verbose = FALSE)
}
features <- SelectIntegrationFeatures(object.list = obj.list.glutamatergic, nfeatures = 5000)
obj.list.glutamatergic <- PrepSCTIntegration(object.list = obj.list.glutamatergic, assay = "SCT", anchor.features = features)
anchors <- FindIntegrationAnchors(object.list = obj.list.glutamatergic, normalization.method = "SCT", anchor.features = features)
features.to.integrate <- Reduce(intersect, lapply(obj.list.glutamatergic, rownames))
obj.combined.glutamatergic <- IntegrateData(anchorset = anchors, normalization.method = "SCT", features.to.integrate = features.to.integrate)

```


```{r}

obj.combined.glutamatergic <- RunPCA(obj.combined.glutamatergic)
obj.combined.glutamatergic <- FindNeighbors(obj.combined.glutamatergic, dims = 1:30)
obj.combined.glutamatergic <- FindClusters(obj.combined.glutamatergic, resolution = 1, algorithm = 4, method = "igraph")
obj.combined.glutamatergic <- RunUMAP(obj.combined.glutamatergic, dims = 1:30, method="umap-learn")

```


```{r}

DimPlot(obj.combined.glutamatergic, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.combined.glutamatergic, reduction = "umap", group.by = "sample", raster = FALSE, shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, "nFeature_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, "nCount_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.combined.glutamatergic, reduction = "umap", group.by = "predicted_doublets", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
VlnPlot(obj.combined.glutamatergic, "nCount_RNA")

```


```{r}

library(tidyverse)

cluster.sample <- table(obj.combined.glutamatergic$sample, obj.combined.glutamatergic$integrated_snn_res.1) %>%
  as.data.frame.matrix() %>%
  rownames_to_column(var = "sample")
cluster.sample[-1] <- lapply(cluster.sample[-1], function(x) x/sum(x))
cluster.sample <- cluster.sample %>%
  pivot_longer(
    cols = -c("sample"),
    names_to = "cluster",
    values_to = "count"
  )
cluster.sample$cluster <- factor(cluster.sample$cluster, levels = unique(cluster.sample$cluster))
  ggplot(cluster.sample, aes(x=cluster, y=count, fill=sample)) +
    geom_bar(stat="identity") +
    theme_minimal()

```


```{r}

SaveH5Seurat(obj.combined.glutamatergic, "E:/Transcriptomics_V1/Opossum/seurat/opossum_v1_glutamatergic_integrated.h5seurat", overwrite = TRUE, verbose = TRUE)

```


```{r}

DefaultAssay(obj.combined.glutamatergic) <- "RNA"

FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Snap25"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Gad2"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Pvalb"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Sst"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Sv2b"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Cux2"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Gucy1a1"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Cdh22"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Rorb"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Kank1"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Fam163a"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Foxp2"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Plxna1"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Cdh9"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Ust"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Sorcs1"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, reduction = "umap", features = c("Cald1"), raster = FALSE, max.cutoff = 2) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

DotPlot(obj.combined.glutamatergic, features = c("Cux2", "Gucy1a1", 
                                                 "Rorb", "Kank1", "Fam163a", 
                                                 "Myt1", "Plxna1", 
                                                 "Trpc4", "Sorcs1", "Gadl1", 
                                                 "Nxph1", "Ust", 
                                                 "Cdh9", "Cald1", 
                                                 "Syt6", "Foxp2", 
                                                 "Wasf3", "Stk10"), scale = FALSE) + coord_flip()

```


```{r}

cells.L23 <- WhichCells(obj.combined.glutamatergic, ident = c(2, 4, 8))
obj.combined.glutamatergic$subclass <- ifelse(colnames(obj.combined.glutamatergic) %in% cells.L23, "L2/3", "ambiguous")

cells.L4 <- WhichCells(obj.combined.glutamatergic, ident = c(1, 3, 7, 14, 16))
obj.combined.glutamatergic$subclass[cells.L4] <- "L4"

cells.L5IT <- WhichCells(obj.combined.glutamatergic, ident = c(6, 15))
obj.combined.glutamatergic$subclass[cells.L5IT] <- "L5IT"

cells.L6IT <- WhichCells(obj.combined.glutamatergic, ident = c(9))
obj.combined.glutamatergic$subclass[cells.L6IT] <- "L6IT"

cells.L5NP <- WhichCells(obj.combined.glutamatergic, ident = c(18))
obj.combined.glutamatergic$subclass[cells.L5NP] <- "L5NP"

cells.L5PT <- WhichCells(obj.combined.glutamatergic, ident = c(11))
obj.combined.glutamatergic$subclass[cells.L5PT] <- "L5PT"

cells.L6CT <- WhichCells(obj.combined.glutamatergic, ident = c(5, 10))
obj.combined.glutamatergic$subclass[cells.L6CT] <- "L6CT"

cells.L6b <- WhichCells(obj.combined.glutamatergic, ident = c(17))
obj.combined.glutamatergic$subclass[cells.L6b] <- "L6b"

```


```{r}

DimPlot(obj.combined.glutamatergic, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.combined.glutamatergic, reduction = "umap", group.by = "sample", raster = FALSE, shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.combined.glutamatergic, reduction = "umap", group.by = "subclass", raster = FALSE, shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, "nFeature_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, "nCount_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.combined.glutamatergic, reduction = "umap", group.by = "predicted_doublets", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
VlnPlot(obj.combined.glutamatergic, "nCount_RNA")

```


```{r}

obj.combined.glutamatergic.pre2 <- obj.combined.glutamatergic
Idents(obj.combined.glutamatergic) <- "subclass"
obj.combined.glutamatergic <- subset(obj.combined.glutamatergic, idents = "ambiguous", invert = TRUE)

```


```{r}

obj.list.glutamatergic <- SplitObject(obj.combined.glutamatergic, split.by = "sample")
for (o in 1:length(obj.list.glutamatergic)) {
  obj.list.glutamatergic[[o]] <- SCTransform(obj.list.glutamatergic[[o]], vst.flavor = "v2", return.only.var.genes = FALSE, verbose = FALSE)
}
features <- SelectIntegrationFeatures(object.list = obj.list.glutamatergic, nfeatures = 5000)
obj.list.glutamatergic <- PrepSCTIntegration(object.list = obj.list.glutamatergic, assay = "SCT", anchor.features = features)
anchors <- FindIntegrationAnchors(object.list = obj.list.glutamatergic, normalization.method = "SCT", anchor.features = features)
features.to.integrate <- Reduce(intersect, lapply(obj.list.glutamatergic, rownames))
obj.combined.glutamatergic <- IntegrateData(anchorset = anchors, normalization.method = "SCT", features.to.integrate = features.to.integrate)

```


```{r}

obj.combined.glutamatergic <- RunPCA(obj.combined.glutamatergic)
obj.combined.glutamatergic <- FindNeighbors(obj.combined.glutamatergic, dims = 1:30)
obj.combined.glutamatergic <- FindClusters(obj.combined.glutamatergic, resolution = 1, algorithm = 4, method = "igraph")
obj.combined.glutamatergic <- RunUMAP(obj.combined.glutamatergic, dims = 1:30, method="umap-learn")

```


```{r}

DimPlot(obj.combined.glutamatergic, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.combined.glutamatergic, reduction = "umap", group.by = "sample", raster = FALSE, shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.combined.glutamatergic, reduction = "umap", group.by = "subclass", raster = FALSE, shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, "nFeature_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, "nCount_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.combined.glutamatergic, reduction = "umap", group.by = "predicted_doublets", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
VlnPlot(obj.combined.glutamatergic, "nCount_RNA")

```


```{r}

DotPlot(obj.combined.glutamatergic, features = c("Cux2", "Gucy1a1", 
                                                 "Rorb", "Kank1", "Fam163a", 
                                                 "Myt1", "Plxna1", 
                                                 "Trpc4", "Sorcs1", "Gadl1", 
                                                 "Nxph1", "Ust", 
                                                 "Cdh9", "Cald1", 
                                                 "Syt6", "Foxp2", 
                                                 "Wasf3", "Stk10"), scale = FALSE) + coord_flip()

```


```{r}

cells.L23 <- WhichCells(obj.combined.glutamatergic, ident = c(2, 6, 8, 9))
obj.combined.glutamatergic$subclass <- ifelse(colnames(obj.combined.glutamatergic) %in% cells.L23, "L2/3", "ambiguous")

cells.L4 <- WhichCells(obj.combined.glutamatergic, ident = c(1, 4, 7))
obj.combined.glutamatergic$subclass[cells.L4] <- "L4"

cells.L5IT <- WhichCells(obj.combined.glutamatergic, ident = c(5, 15))
obj.combined.glutamatergic$subclass[cells.L5IT] <- "L5IT"

cells.L6IT <- WhichCells(obj.combined.glutamatergic, ident = c(10, 13))
obj.combined.glutamatergic$subclass[cells.L6IT] <- "L6IT"

cells.L5NP <- WhichCells(obj.combined.glutamatergic, ident = c(17))
obj.combined.glutamatergic$subclass[cells.L5NP] <- "L5NP"

cells.L5PT <- WhichCells(obj.combined.glutamatergic, ident = c(11))
obj.combined.glutamatergic$subclass[cells.L5PT] <- "L5PT"

cells.L6CT <- WhichCells(obj.combined.glutamatergic, ident = c(3, 11))
obj.combined.glutamatergic$subclass[cells.L6CT] <- "L6CT"

cells.L6b <- WhichCells(obj.combined.glutamatergic, ident = c(16))
obj.combined.glutamatergic$subclass[cells.L6b] <- "L6b"

```


```{r}

DimPlot(obj.combined.glutamatergic, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.combined.glutamatergic, reduction = "umap", group.by = "sample", raster = FALSE, shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.combined.glutamatergic, reduction = "umap", group.by = "subclass", raster = FALSE, shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, "nFeature_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.combined.glutamatergic, "nCount_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.combined.glutamatergic, reduction = "umap", group.by = "predicted_doublets", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
VlnPlot(obj.combined.glutamatergic, "nCount_RNA")

```


```{r}

SaveH5Seurat(obj.combined.glutamatergic, "E:/Transcriptomics_V1/Opossum/seurat/opossum_v1_glutamatergic_integrated_processed.h5seurat", overwrite = TRUE, verbose = TRUE)

```


```{r}

DefaultAssay(obj.combined.glutamatergic) <- "RNA"
L23.markers.2 <- FindMarkers(obj.combined.glutamatergic, ident.1 = c("2", "8"), ident.2 = c("6", "9"), only.pos = TRUE)
L23.markers.28 <- FindMarkers(obj.combined.glutamatergic, ident.1 = c("2"), ident.2 = c("8"), only.pos = TRUE)
L23.markers.6 <- FindMarkers(obj.combined.glutamatergic, ident.1 = c("6"), ident.2 = c("2", "8", "9"), only.pos = TRUE)
L23.markers.9 <- FindMarkers(obj.combined.glutamatergic, ident.1 = c("9"), ident.2 = c("2", "6", "8"), only.pos = TRUE)

```


```{r}

FeaturePlot(obj.combined.glutamatergic, "Etv6", raster = FALSE, max.cutoff = 5) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```

















