---
title: "Cat M1 Raw"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
library(data.table)

data_path <- "E:/Cat_M1/output/"

sample_IDs <- c("NW_TX0132-3", "NW_TX0133-5", "NW_TX0133-6", "NW_TX0133-7", "NW_TX0135-6", "NW_TX0135-7", 
                "NW_TX0137-1", "NW_TX0137-2", "NW_TX0141-12", "NW_TX0142-1", "NW_TX0145-9", "NW_TX0146-3") 

objs <- c()

for (sample in sample_IDs) {
  
  temp.obj.path <- paste(data_path, sample, "/outs/filtered_feature_bc_matrix/", sep = "")
  temp.obj.data <- Read10X(temp.obj.path)
  temp.obj <- CreateSeuratObject(counts = temp.obj.data, project = "Cat_M1")
  temp.obj$sample <- sample
  temp.obj <- scrublet_R(seurat_obj = temp.obj)
  objs <- append(objs, temp.obj)
  
}

```


```{r}

obj.cat <- merge(objs[[1]], y = objs[2:12], add.cell.ids = sample_IDs, project = "Cat_M1")

```


```{r}

VlnPlot(obj.cat, features = c("nFeature_RNA"), group.by = "sample", raster = FALSE)
VlnPlot(obj.cat, features = c("nCount_RNA"), group.by = "sample", raster = FALSE)
FeatureScatter(obj.cat, feature1 = "nCount_RNA", feature2 = "nFeature_RNA", raster = FALSE)

```


```{r}

cell_mask <- Reduce(intersect,list(WhichCells(obj.cat, expression = nFeature_RNA > 700), 
                                   WhichCells(obj.cat, expression = nFeature_RNA < 6500),
                                   WhichCells(obj.cat, expression = nCount_RNA < 40000)))

gene_mask <- rownames(obj.cat)[Matrix::rowSums(obj.cat[["RNA"]]@counts > 0) > 8]

obj.cat <- subset(obj.cat, features = gene_mask, cells = cell_mask)

```


```{r}
obj.cat <- NormalizeData(obj.cat, normalization.method = "LogNormalize", scale.factor = 10000)
obj.cat <- FindVariableFeatures(obj.cat, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(obj.cat)
obj.cat <- ScaleData(obj.cat, features = all.genes)
obj.cat <- RunPCA(obj.cat, features = VariableFeatures(object = obj.cat))
ElbowPlot(obj.cat, ndims = 50)

```


```{r}

obj.cat <- FindNeighbors(obj.cat, dims = 1:30)
obj.cat <- FindClusters(obj.cat, resolution = 1, algorithm = 4, method = "igraph")
obj.cat <- RunUMAP(obj.cat, dims = 1:30, method="umap-learn")

```


```{r}

DimPlot(obj.cat, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.cat, reduction = "umap", group.by = "sample", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.cat, "nFeature_RNA", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.cat, "nCount_RNA", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.cat, reduction = "umap", group.by = "predicted_doublets", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

#glutamatergic 
FeaturePlot(obj.cat, reduction = "umap", features = c("SNAP25"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.cat, reduction = "umap", features = c("SLC17A7"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.cat, reduction = "umap", features = c("CSF1R"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.cat, reduction = "umap", features = c("MOG"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.cat, reduction = "umap", features = c("PDGFRA"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
#FeaturePlot(obj.cat, reduction = "umap", features = c("ALDH1L1"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.cat, reduction = "umap", features = c("COL1A1"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

#GABAergic 
FeaturePlot(obj.cat, reduction = "umap", features = c("PVALB"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.cat, reduction = "umap", features = c("GAD2"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.cat, reduction = "umap", features = c("SST"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.cat, reduction = "umap", features = c("VIP"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.cat, reduction = "umap", features = c("LAMP5"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.cat, reduction = "umap", features = c("SNCG"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

#non-neuronal
FeaturePlot(obj.cat, reduction = "umap", features = c("CSF1R"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal() # microglia
FeaturePlot(obj.cat, reduction = "umap", features = c("MOG"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal() # oligodendrocytes
FeaturePlot(obj.cat, reduction = "umap", features = c("PDGFRA"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal() # OPC
FeaturePlot(obj.cat, reduction = "umap", features = c("AQP4"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal() # astrocytes
FeaturePlot(obj.cat, reduction = "umap", features = c("COL1A1"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal() # VLMC
FeaturePlot(obj.cat, reduction = "umap", features = c("TEK"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal() # endothelial

```


```{r}

cells.glutamatergic <- WhichCells(obj.cat, ident = c(1, 2, 3, 4, 5, 7, 8, 9, 10, 13, 15, 17, 19, 21, 23, 24, 26, 29, 30, 31, 33, 35, 36))
obj.cat$class <- ifelse(colnames(obj.cat) %in% obj.cat.glutamatergic, "glutamatergic", "ambiguous")

cells.gabaergic <- WhichCells(obj.cat, ident = c(6, 12, 14, 16, 20, 22, 25, 28))
obj.cat$class[obj.cat.gabaergic] <- "gabaergic"

cells.nonneuronal <- WhichCells(obj.cat, ident = c(11, 18, 27, 32, 34))
obj.cat$class[obj.cat.nonneuronal] <- "nonneuronal"

```


```{r}

DimPlot(obj.cat, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-19, 19) + ylim(-19, 19) + coord_equal()
DimPlot(obj.cat, reduction = "umap", group.by = "class", raster = FALSE) + xlim(-19, 19) + ylim(-19, 19) + coord_equal()

```

```{r}

obj.cat.glutamatergic <- subset(obj.cat, subset = class == "glutamatergic")
obj.cat.gabaergic <- subset(obj.cat, subset = class == "gabaergic")
obj.cat.nonneuronal <- subset(obj.cat, subset = class == "nonneuronal")

```


```{r}

obj.cat.glutamatergic <- NormalizeData(obj.cat.glutamatergic, normalization.method = "LogNormalize", scale.factor = 10000)
obj.cat.glutamatergic <- FindVariableFeatures(obj.cat.glutamatergic, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(obj.cat.glutamatergic)
obj.cat.glutamatergic <- ScaleData(obj.cat.glutamatergic, features = all.genes)
obj.cat.glutamatergic <- RunPCA(obj.cat, features = VariableFeatures(object = obj.cat.glutamatergic))

obj.cat.glutamatergic <- FindNeighbors(obj.cat.glutamatergic, dims = 1:30)
obj.cat.glutamatergic <- FindClusters(obj.cat.glutamatergic, resolution = 1, algorithm = 4, method = "igraph")
obj.cat.glutamatergic <- RunUMAP(obj.cat.glutamatergic, dims = 1:30, method="umap-learn")

```


```{r}

obj.cat.gabaergic <- NormalizeData(obj.cat.gabaergic, normalization.method = "LogNormalize", scale.factor = 10000)
obj.cat.gabaergic <- FindVariableFeatures(obj.cat.gabaergic, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(obj.cat.gabaergic)
obj.cat.gabaergic <- ScaleData(obj.cat.gabaergic, features = all.genes)
obj.cat.gabaergic <- RunPCA(obj.cat.gabaergic, features = VariableFeatures(object = obj.cat.gabaergic))

obj.cat.gabaergic <- FindNeighbors(obj.cat.gabaergic, dims = 1:30)
obj.cat.gabaergic <- FindClusters(obj.cat.gabaergic, resolution = 1.1, algorithm = 4, method = "igraph")
obj.cat.gabaergic <- RunUMAP(obj.cat.gabaergic, dims = 1:30, method="umap-learn")

```


```{r}

obj.cat.nonneuronal <- NormalizeData(obj.cat.nonneuronal, normalization.method = "LogNormalize", scale.factor = 10000)
obj.cat.nonneuronal <- FindVariableFeatures(obj.cat.nonneuronal, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(obj.cat.nonneuronal)
obj.cat.nonneuronal <- ScaleData(obj.cat.nonneuronal, features = all.genes)
obj.cat.nonneuronal <- RunPCA(obj.cat.nonneuronal, features = VariableFeatures(object = obj.cat.nonneuronal))

obj.cat.nonneuronal <- FindNeighbors(obj.cat.nonneuronal, dims = 1:30)
obj.cat.nonneuronal <- FindClusters(obj.cat.nonneuronal, resolution = 1, algorithm = 4, method = "igraph")
obj.cat.nonneuronal <- RunUMAP(obj.cat.nonneuronal, dims = 1:30, method="umap-learn")

```


```{r}

SaveH5Seurat(obj.cat.glutamatergic, "E:/cat_M1/seurat/cat_m1_glutamatergic_raw.h5seurat", overwrite = TRUE, verbose = TRUE)
SaveH5Seurat(obj.cat.gabaergic, "E:/cat_M1/seurat/cat_m1_gabaergic_raw.h5seurat", overwrite = TRUE, verbose = TRUE)
SaveH5Seurat(obj.cat.nonneuronal, "E:/cat_M1/seurat/cat_m1_nonneuronal_raw.h5seurat", overwrite = TRUE, verbose = TRUE)

```

