---
title: "Receptor Expression Mouse/Opossum"
output: html_notebook
---

```{r, fig.width=4, fig.height=4}

library(viridis)

Idents(obj.mouse.glutamatergic) <- "subclass_label"
levels(obj.mouse.glutamatergic) <- c("L2/3 IT", "L5 IT", "L6 IT", "L5 ET", "L5/6 NP", "L6b", "L6 CT", "L6 IT Car3")
cholinergic.markers = c("Chrm1", "Chrm2", "Chrm3", "Chrm4", "Chrm5", 
                        "Chrna1", "Chrna2", "Chrna3", "Chrna4", "Chrna5", "Chrna6", "Chrna7", "Chrna10", 
                        "Chrnb1", "Chrnb2", "Chrnb3", "Chrnb4", 
                        "Chrnd", "Chrne")
DoHeatmap(object = obj.mouse.glutamatergic, cholinergic.markers, slot = "data") + scale_fill_gradientn(colors = c("white", "red")) + theme(text = element_text(size = 10))
expr <- AverageExpression(obj.mouse.glutamatergic, assays = "RNA", return.seurat = TRUE, features = cholinergic.markers)
DoHeatmap(expr, features = cholinergic.markers, slot = "data", draw.lines = FALSE, size = 3) + scale_fill_gradientn(colors = magma(100), limits = c(0, 3)) + theme(text = element_text(size = 10))

```


```{r, fig.width=4, fig.height=4}

Idents(obj.mouse.glutamatergic) <- "subclass_label"
levels(obj.mouse.glutamatergic) <- c("Pvalb", "Sst", "Sst Chodl", "Vip", "Lamp5", "Sncg", "Meis2")
adrenergic.markers = c("Adra1a", "Adra1b", "Adra1d", "Adra2a", "Adra2c", "Adrb1", "Adrb2", "Adrb3")
DoHeatmap(object = obj.mouse.glutamatergic, adrenergic.markers, slot = "data") + scale_fill_gradientn(colors = c("white", "red")) + theme(text = element_text(size = 10))
expr <- AverageExpression(obj.mouse.glutamatergic, assays = "RNA", return.seurat = TRUE, features = adrenergic.markers)
DoHeatmap(expr, features = adrenergic.markers, slot = "data", draw.lines = FALSE, size = 3) + scale_fill_gradientn(colors = magma(100), limits = c(0, 3)) + theme(text = element_text(size = 10))

```

