---
title: "Species Gabaergic UMAP Plots"
output: html_notebook

---

```{r}
#loading in all the species data: mouse, opossum, treeshrew

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)

obj.mouse.gabaergic <- LoadH5Seurat("E:/Mouse_M1/seurat/mouse_m1_gabaergic.h5Seurat")
obj.opossum.gabaergic <- LoadH5Seurat("E:/Opossum_M1/seurat/opossum_m1_gabaergic.h5Seurat")
obj.treeshrew.gabaergic <- LoadH5Seurat("E:/Tree_Shrew_M1/seurat/treeshrew_m1_gabaergic_sct.h5seurat")

```

```{r, fig.height=4, fig.width=5}

cells.sst <- WhichCells(obj.mouse.gabaergic, ident = c("Sst", "Sst Chodl"))
obj.mouse.gabaergic$subclass[cells.sst] <- "Sst"

dim_plot_mouse <- DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by = "subclass", order = rev(c("Pvalb", "Sst", "Vip", "Lamp5", "Meis2", "Sncg")), cols = c("#468fba", "#ba1851",  "#a85d96", "#a2bc8c", "#878a88", "#f6cb7c"), label = TRUE, label.size = 5, raster = FALSE) + NoLegend()  + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

dim_plot_opossum <- DimPlot(obj.opossum.gabaergic, reduction = "umap", group.by = "subclass", order = rev(c("Pvalb", "Sst", "Vip", "Lamp5")), cols = c("#468fba", "#ba1851",  "#a85d96", "#a2bc8c"), label = TRUE, label.size = 5, raster = FALSE) + NoLegend()  + xlim(-13, 17) + ylim(-13, 17) + coord_equal()

dim_plot_treeshrew <- DimPlot(obj.treeshrew.gabaergic, reduction = "umap", group.by = "subclass", order = rev(c("Pvalb", "Sst", "Vip", "Lamp5", "Sncg")), cols = c("#468fba", "#ba1851",  "#a85d96", "#a2bc8c", "#f6cb7c"),label = TRUE, label.size = 5, raster = FALSE) + NoLegend()  + xlim(-17, 13) + ylim(-17, 13) + coord_equal()

ggsave("G:/Shared drives/Opossum transcriptomics/figures/Species_GABAergic_UMAP_Plots/Mouse_UMAP_GABAergic_subclass.png", dim_plot_mouse, width=7, height=4, dpi=500)
ggsave("G:/Shared drives/Opossum transcriptomics/figures/Species_GABAergic_UMAP_Plots/Opossum_UMAP_GABAergic_subclass.png", dim_plot_opossum, width=7, height=4, dpi=500)
ggsave("G:/Shared drives/Opossum transcriptomics/figures/Species_GABAergic_UMAP_Plots/Treeshrew_UMAP_GABAergic_subclass.png", dim_plot_treeshrew, width=7, height=4, dpi=500)

```
