---
title: "Opossum M1 Object"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
library(data.table)

data_path <- "E:/Armadillo_M1/output/"

sample_IDs <- c("NW_TX0042-3", "NW_TX0043-7", "NW_TX0043-9", "NW_TX0043-10", 
                "NW_TX0044-7", "NW_TX0044-8", "NW_TX0044-9", "NW_TX0064-2", 
                "NW_TX0072-10", "NW_TX0073-7", "NW_TX0073-8", "NW_TX0073-9")

objs <- c()

for (sample in sample_IDs) {
  
  temp.obj.path <- paste(data_path, sample, "/outs/filtered_feature_bc_matrix/", sep = "")
  temp.obj.data <- Read10X(temp.obj.path)
  temp.obj <- CreateSeuratObject(counts = temp.obj.data, project = "Armadillo_M1")
  temp.obj$sample <- sample
  temp.obj <- scrublet_R(seurat_obj = temp.obj)
  objs <- append(objs, temp.obj)
  
}

```


```{r}

obj.armadillo <- merge(objs[[1]], y = objs[2:12], add.cell.ids = sample_IDs, project = "Armadillo_M1")

```


```{r}

genes.mapping <- read.csv("E:/Armadillo_Mouse_Genes.txt")
genes.mapping.mouse <- as.list(genes.mapping$Mouse.gene.name)
genes.mapping.armadillo <- as.list(genes.mapping$Gene.name)
ids.mapping.armadillo <- as.list(genes.mapping$Gene.stable.ID)
genes.armadillo = rownames(obj.armadillo)
for (gene in genes.mapping.mouse) {
  
    idx.mouse <- which(genes.mapping.mouse %in% gene)

    if (length(idx.mouse) == 1) {
      
      gene.armadillo <- genes.mapping.armadillo[idx.mouse]
      id.armadillo <- ids.mapping.armadillo[idx.mouse]
      
      if (gene.armadillo == "") {
        
        idx.armadillo <- which(genes.armadillo %in% id.armadillo)
        genes.armadillo[idx.armadillo] <- gene
        
      } else {
        
        idx.armadillo <- which(genes.armadillo %in% gene.armadillo)
        genes.armadillo[idx.armadillo] <- gene
        
      }
      
    }
  
}

```


```{r}

obj.df <- as.data.frame(as.matrix(obj.armadillo[["RNA"]]@counts))
rownames(obj.df) <- genes.armadillo
obj.armadillo.temp <- CreateSeuratObject(counts = obj.df, meta.data = obj.armadillo[[]])
obj.armadillo <- obj.armadillo.temp

```


```{r}

VlnPlot(obj.armadillo, features = c("nFeature_RNA", "nCount_RNA"), ncol = 2, raster = FALSE)
FeatureScatter(obj.armadillo, feature1 = "nCount_RNA", feature2 = "nFeature_RNA", raster = FALSE)

```


```{r}

cell_mask <- Reduce(intersect,list(WhichCells(obj.armadillo, expression = nFeature_RNA > 700), 
                                   WhichCells(obj.armadillo, expression = nFeature_RNA < 6500),
                                   WhichCells(obj.armadillo, expression = nCount_RNA < 40000)))

gene_mask <- rownames(obj.armadillo)[Matrix::rowSums(obj.armadillo) > 8]

obj.armadillo <- subset(obj.armadillo, features = gene_mask, cells = cell_mask)

```


```{r}

obj.list <- SplitObject(obj.armadillo, split.by = "sample")

obj.list <- lapply(X = obj.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 3000)
})

features <- SelectIntegrationFeatures(object.list = obj.list)

```


```{r}

obj.anchors <- FindIntegrationAnchors(object.list = obj.list, anchor.features = features)
obj.armadillo <- IntegrateData(anchorset = obj.anchors)

```


```{r}

DefaultAssay(obj.armadillo) <- "integrated"

# Run the standard workflow for visualization and clustering
obj.armadillo <- ScaleData(obj.armadillo, verbose = FALSE)
obj.armadillo <- RunPCA(obj.armadillo, npcs = 30, verbose = FALSE)
obj.armadillo <- FindNeighbors(obj.armadillo, dims = 1:30, graph.name = "integrated_snn")
obj.armadillo <- FindClusters(obj.armadillo, resolution = 1, algorithm = 4, method = "igraph", graph.name = "integrated_snn")
obj.armadillo <- RunUMAP(obj.armadillo, dims = 1:30, method="umap-learn")

```


```{r}

DimPlot(obj.armadillo, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.armadillo, reduction = "umap", group.by = "sample", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.armadillo, reduction = "umap", group.by = "predicted_doublets", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

# FeaturePlot(obj.armadillo, "SNAP25", slot = "scale.data", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.armadillo, "GAD1", slot = "scale.data", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.armadillo, "GAD2", slot = "scale.data", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
# FeaturePlot(obj.armadillo, "CSF1R", slot = "scale.data", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal() # microglia
FeaturePlot(obj.armadillo, "MOG", slot = "scale.data", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal() # oligodendrocytes
FeaturePlot(obj.armadillo, "PDGFRA", slot = "scale.data", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal() # OPC
FeaturePlot(obj.armadillo, "AQP4", slot = "scale.data", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal() # astrocytes
# FeaturePlot(obj.armadillo, "COL1A1", slot = "scale.data", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal() # VLMC
FeaturePlot(obj.armadillo, "TEK", slot = "scale.data", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal() # endothelial

```


```{r}

DefaultAssay(obj.armadillo) <- "RNA"

FeaturePlot(obj.armadillo, "PVALB", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.armadillo, "SST", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.armadillo, "VIP", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.armadillo, "LAMP5", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.armadillo, "SNCG", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

obj.armadillo.gabaergic <- subset(obj.armadillo, idents = c("8", "12", "13", "18", "21", "23", "25", "28", "33"))
SaveH5Seurat(obj.armadillo.gabaergic, "E:/Armadillo_M1/seurat/armadillo_m1_gabaergic.h5seurat", overwrite = TRUE, verbose = TRUE)

```


```{r}

SaveH5Seurat(obj.armadillo, "E:/Armadillo_M1/seurat/armadillo_m1_all.h5seurat", overwrite = TRUE, verbose = TRUE)

```

