---
title: "Human M1 Object"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)

matrix <- readRDS("E:/Human_M1/Human_M1_10xV3_Matrix.RDS")
meta_tb <- arrow::read_feather("E:/Human_M1/Human_M1_10xV3_Metadata.feather")
meta_df <- as.data.frame(meta_tb)
row.names(meta_df) <- meta_df[, "sample_id"]
obj.human <- CreateSeuratObject(counts = matrix, meta.data = meta_df)
rm(list = c("matrix", "meta_df", "meta_tb"))

```


```{r}

obj.human <- AddMetaData(obj.human, metadata = unlist(rep(list("Human_M1"), ncol(obj.human))), col.name = "dataset")
Idents(object = obj.human) <- obj.human[["dataset"]]
obj.human[["percent.mt"]] <- PercentageFeatureSet(obj.human, pattern = "^mt-")
VlnPlot(obj.human, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
plot1 <- FeatureScatter(obj.human, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(obj.human, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2

```


```{r}

obj.human <- NormalizeData(obj.human, normalization.method = "LogNormalize", scale.factor = 10000)
obj.human <- FindVariableFeatures(obj.human, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(obj.human)
obj.human <- ScaleData(obj.human, features = all.genes)
obj.human <- RunPCA(obj.human, features = VariableFeatures(object = obj.human))
ElbowPlot(obj.human, ndims = 50)

```


```{r}

obj.human.list <- SplitObject(obj.human, split.by = "donor_id")

for (sample in names(obj.human.list)) {
    obj.human.list[[sample]] <- SCTransform(obj.human.list[[sample]], vst.flavor = "v2", verbose = FALSE) %>%
    RunPCA(npcs = 30, verbose = FALSE)
}

```


```{r}

features <- SelectIntegrationFeatures(object.list = obj.human.list, nfeatures = 2000)
obj.human.list <- PrepSCTIntegration(object.list = obj.human.list, anchor.features = features)
obj.human.anchors <- FindIntegrationAnchors(object.list = obj.human.list, normalization.method = "SCT", anchor.features = features)
obj.human.sct <- IntegrateData(anchorset = obj.human.anchors, normalization.method = "SCT")

```


```{r}

obj.human.sct <- RunPCA(obj.human.sct, verbose = FALSE)
obj.human.sct <- RunUMAP(obj.human.sct, dims = 1:30, method = "umap-learn", reduction = "pca")
obj.human.sct <- FindNeighbors(obj.human.sct, reduction = "pca", dims = 1:30)
obj.human.sct <- FindClusters(obj.human.sct, resolution = 1, algorithm = 4, method = "igraph")

```


```{r}

DimPlot(obj.human.sct, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.human.sct, reduction = "umap", group.by = "donor_id", shuffle = TRUE, raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.human.sct, reduction = "umap", group.by = "subclass_label", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```

```{r}

Idents(obj.human.sct) <- "level1_label"

cells.glutamatergic <- WhichCells(obj.human.sct, ident = "Glutamatergic")
obj.human.sct$class <- ifelse(colnames(obj.human) %in% cells.glutamatergic, "glutamatergic", "glutamatergic")

cells.gabaergic <- WhichCells(obj.human.sct, ident = "GABAergic")
obj.human.sct$class[cells.gabaergic] <- "gabaergic"

cells.nonneuronal <- WhichCells(obj.human.sct, ident = "Non-neuronal")
obj.human.sct$class[cells.nonneuronal] <- "nonneuronal"

```


```{r}

DimPlot(obj.human.sct, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-19, 19) + ylim(-19, 19) + coord_equal()
DimPlot(obj.human.sct, reduction = "umap", group.by = "class", raster = FALSE) + xlim(-19, 19) + ylim(-19, 19) + coord_equal()

```


```{r}

obj.human.glutamatergic <- subset(obj.human.sct, subset = class == "glutamatergic")
obj.human.gabaergic <- subset(obj.human.sct, subset = class == "gabaergic")
obj.human.nonneuronal <- subset(obj.human.sct, subset = class == "nonneuronal")

```


```{r}

obj.human.gabaergic <- SplitObject(obj.human.gabaergic, split.by = "donor_id")

for (sample in names(obj.human.gabaergic)) {
    obj.human.gabaergic[[sample]] <- SCTransform(obj.human.gabaergic[[sample]], vst.flavor = "v2", verbose = FALSE) %>%
    RunPCA(npcs = 30, verbose = FALSE)
}

features <- SelectIntegrationFeatures(object.list = obj.human.gabaergic, nfeatures = 2000)
obj.human.gabaergic <- PrepSCTIntegration(object.list = obj.human.gabaergic, anchor.features = features)
obj.human.gabaergic.anchors <- FindIntegrationAnchors(object.list = obj.human.gabaergic, normalization.method = "SCT", anchor.features = features)
obj.human.gabaergic.sct <- IntegrateData(anchorset = obj.human.gabaergic.anchors, normalization.method = "SCT")

obj.human.gabaergic.sct <- RunPCA(obj.human.gabaergic.sct, verbose = FALSE)
obj.human.gabaergic.sct <- RunUMAP(obj.human.gabaergic.sct, dims = 1:30, method = "umap-learn", reduction = "pca")
obj.human.gabaergic.sct <- FindNeighbors(obj.human.gabaergic.sct, reduction = "pca", dims = 1:30)
obj.human.gabaergic.sct <- FindClusters(obj.human.gabaergic.sct, resolution = 1, algorithm = 4, method = "igraph")

```


```{r}

obj.human.glutamatergic <- SplitObject(obj.human.glutamatergic, split.by = "donor_id")

for (sample in names(obj.human.glutamatergic)) {
    obj.human.glutamatergic[[sample]] <- SCTransform(obj.human.glutamatergic[[sample]], vst.flavor = "v2", verbose = FALSE) %>%
    RunPCA(npcs = 30, verbose = FALSE)
}

features <- SelectIntegrationFeatures(object.list = obj.human.glutamatergic, nfeatures = 2000)
obj.human.glutamatergic <- PrepSCTIntegration(object.list = obj.human.glutamatergic, anchor.features = features)
obj.human.glutamatergic.anchors <- FindIntegrationAnchors(object.list = obj.human.glutamatergic, normalization.method = "SCT", anchor.features = features)
obj.human.glutamatergic.sct <- IntegrateData(anchorset = obj.human.glutamatergic.anchors, normalization.method = "SCT")

obj.human.glutamatergic.sct <- RunPCA(obj.human.glutamatergic.sct, verbose = FALSE)
obj.human.glutamatergic.sct <- RunUMAP(obj.human.glutamatergic.sct, dims = 1:30, method = "umap-learn", reduction = "pca")
obj.human.glutamatergic.sct <- FindNeighbors(obj.human.glutamatergic.sct, reduction = "pca", dims = 1:30)
obj.human.glutamatergic.sct <- FindClusters(obj.human.glutamatergic.sct, resolution = 1, algorithm = 4, method = "igraph")

```


```{r}

obj.human.nonneuronal <- SplitObject(obj.human.nonneuronal, split.by = "donor_id")

for (sample in names(obj.human.nonneuronal)) {
    obj.human.nonneuronal[[sample]] <- SCTransform(obj.human.nonneuronal[[sample]], vst.flavor = "v2", verbose = FALSE) %>%
    RunPCA(npcs = 30, verbose = FALSE)
}

features <- SelectIntegrationFeatures(object.list = obj.human.nonneuronal, nfeatures = 2000)
obj.human.nonneuronal <- PrepSCTIntegration(object.list = obj.human.nonneuronal, anchor.features = features)
obj.human.nonneuronal.anchors <- FindIntegrationAnchors(object.list = obj.human.nonneuronal, normalization.method = "SCT", anchor.features = features)
obj.human.nonneuronal.sct <- IntegrateData(anchorset = obj.human.nonneuronal.anchors, normalization.method = "SCT")

obj.human.nonneuronal.sct <- RunPCA(obj.human.nonneuronal.sct, verbose = FALSE)
obj.human.nonneuronal.sct <- RunUMAP(obj.human.nonneuronal.sct, dims = 1:30, method = "umap-learn", reduction = "pca")
obj.human.nonneuronal.sct <- FindNeighbors(obj.human.nonneuronal.sct, reduction = "pca", dims = 1:30)
obj.human.nonneuronal.sct <- FindClusters(obj.human.nonneuronal.sct, resolution = 1, algorithm = 4, method = "igraph")

```


```{r}

SaveH5Seurat(obj.human.glutamatergic.sct, "E:/Human_M1/seurat/human_m1_glutamatergic_raw.h5seurat", overwrite = TRUE, verbose = TRUE)
SaveH5Seurat(obj.human.gabaergic.sct, "E:/Human_M1/seurat/human_m1_gabaergic_raw.h5seurat", overwrite = TRUE, verbose = TRUE)
SaveH5Seurat(obj.human.nonneuronal.sct, "E:/Human_M1/seurat/human_m1_nonneuronal_raw.h5seurat", overwrite = TRUE, verbose = TRUE)

```

