---
title: "R Notebook"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(SeuratDisk)

obj.mouse <- LoadH5Seurat("E:/Mouse_M1/seurat/mouse_m1_gabaergic_pv.h5seurat")
obj.mouse[["dataset"]] <- "Mouse_M1"
obj.opossum <- LoadH5Seurat("E:/Opossum_M1/seurat/opossum_m1_gabaergic_pv.h5seurat")
obj.opossum[["dataset"]] <- "Opossum_M1"

# obj.mouse <- obj.mouse[, sample(colnames(obj.mouse), size = ncol(obj.opossum), replace = FALSE)]

```


```{r}

common.features <- intersect(rownames(obj.mouse), rownames(obj.opossum))
obj.combined <- merge(obj.mouse[common.features,], y = obj.opossum[common.features,])

```


```{r}

obj.list <- SplitObject(obj.combined, split.by = "dataset")

obj.list <- lapply(X = obj.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 1000)
})

features <- SelectIntegrationFeatures(object.list = obj.list, nfeatures = 1000)

```


```{r}

integ.anchors <- FindIntegrationAnchors(object.list = obj.list, anchor.features = features)
integ.combined <- IntegrateData(anchorset = integ.anchors)

```


```{r}

DefaultAssay(integ.combined) <- "integrated"

integ.combined <- ScaleData(integ.combined, verbose = FALSE)
integ.combined <- RunPCA(integ.combined, verbose = FALSE)
integ.combined <- RunUMAP(integ.combined, dims = 1:30)
integ.combined <- FindNeighbors(integ.combined, dims = 1:30)
integ.combined <- FindClusters(integ.combined, resolution = 2, algorithm = 4, method = "igraph")

```


```{r}

DimPlot(integ.combined, reduction = "umap", raster = FALSE) + xlim(-15, 15) + ylim(-10, 10) + coord_equal()
DimPlot(integ.combined, reduction = "umap", group.by = "dataset", raster = FALSE) + xlim(-15, 15) + ylim(-10, 10) + coord_equal()
DimPlot(integ.combined, reduction = "umap", split.by = "dataset", group.by = "cluster_label", raster = FALSE) + xlim(-10, 10) + ylim(-10, 10) + coord_equal()
DimPlot(integ.combined, reduction = "umap", split.by = "dataset", group.by = "RNA_snn_res.2", raster = FALSE) + xlim(-10, 10) + ylim(-10, 10) + coord_equal()

```


```{r}

# resolution = 2
markers <- FindAllMarkers(integ.combined, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, test.use = "roc")
markers.top <- markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 10, order_by = avg_log2FC)
DimPlot(integ.combined, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-10, 10) + ylim(-10, 10) + coord_equal()
DoHeatmap(object = integ.combined, markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 6))
expr <- AverageExpression(integ.combined, assays = "integrated", return.seurat = TRUE, features = markers.top$gene)
DoHeatmap(expr, features = markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 6))

```


















