---
title: "Merge Mouse/Opossum M1"
output: html_notebook
---


```{r}

library(Seurat)
library(reticulate)
library(scrubletR)
library(ggplot2)

# Load Mouse dataset

matrix <- readRDS("E:/Mouse_M1/Mouse_M1_10xV3_Matrix.RDS")
genes.mapping <- read.csv("E:/Opossum_Mouse_Genes.txt")
genes.mapping.mouse <- as.list(genes.mapping$Mouse.gene.name)
genes.mapping.opossum <- as.list(genes.mapping$Gene.name)
ids.mapping.opossum <- as.list(genes.mapping$Gene.stable.ID)
genes.mouse = rownames(matrix)
for (gene in genes.mouse) {
  
  if (gene %in% genes.mapping.mouse) {
    
    idx.mouse <- which(genes.mouse %in% gene)
    idx.mapping <- which(as.list(genes.mapping$Mouse.gene.name) %in% gene)
    if (length(idx.mapping) == 1) {
      
      gene.opossum <- genes.mapping.opossum[idx.mapping]
      
      if (gene.opossum == "") {
        
        genes.mouse[idx.mouse] <- ids.mapping.opossum[idx.mapping]
        
      } else {
        
        genes.mouse[idx.mouse] <- gene.opossum
        
      }
      
    }
    
  }
  
}
rownames(matrix) <- genes.mouse
meta_tb <- arrow::read_feather("E:/Mouse_M1/Mouse_M1_10xV3_Metadata.feather")
meta_df <- as.data.frame(meta_tb)
row.names(meta_df) <- meta_df[, "sample_id"]
obj.mouse <- CreateSeuratObject(counts = matrix, meta.data = meta_df)
rm(list = c("matrix", "meta_df", "meta_tb"))
obj.mouse <- AddMetaData(obj.mouse, metadata = unlist(rep(list("Mouse_M1"), ncol(obj.mouse))), col.name = "dataset")
obj.mouse[["percent.mt"]] <- PercentageFeatureSet(obj.mouse, pattern = "^mt-")

```

```{r}

data_path <- "E:/Opossum_M1/output/"
sample_IDs <- c("NW_TX0055-4", "NW_TX0055-5", "NW_TX0055-6", "NW_TX0064-3", 
                "NW_TX0064-4", "NW_TX0064-5", "NW_TX0077-7", "NW_TX0077-8", 
                "NW_TX0078-1", "NW_TX0090-11", "NW_TX0092-7", "NW_TX0092-8")

objs <- c()

for (sample in sample_IDs) {
  
  temp.obj.path <- paste(data_path, sample, "/outs/filtered_feature_bc_matrix/", sep = "")
  temp.obj.data <- Read10X(temp.obj.path)
  temp.obj <- CreateSeuratObject(counts = temp.obj.data, project = "Opossum_M1")
  temp.obj$sample <- sample
  # temp.obj <- scrublet_R(seurat_obj = temp.obj)
  objs <- append(objs, temp.obj)
  
}

obj <- merge(objs[[1]], y = objs[2:12], add.cell.ids = sample_IDs, project = "Opossum_M1")

cell_mask <- Reduce(intersect,list(WhichCells(obj, expression = nFeature_RNA > 700), 
                                   WhichCells(obj, expression = nFeature_RNA < 6500),
                                   WhichCells(obj, expression = nCount_RNA < 40000)))

gene_mask <- rownames(obj)[Matrix::rowSums(obj) > 8]

obj.opossum <- subset(obj, features = gene_mask, cells = cell_mask)
meta.data <- read.csv("E:/Opossum_M1/metadata.csv")
rownames(meta.data) <- meta.data$X
obj.opossum$class <- meta.data$class
obj.opossum <- AddMetaData(obj.opossum, metadata = unlist(rep(list("Opossum_M1"), ncol(obj.opossum))), col.name = "dataset")

```


```{r}

obj.mouse <- subset(x = obj.mouse, subset = level1_label == "Glutamatergic")
obj.opossum <- subset(x = obj.opossum, subset = class == "glutamatergic")
common.features <- intersect(rownames(obj.mouse), rownames(obj.opossum))

obj.combined <- merge(obj.mouse[common.features, ], y = obj.opossum[common.features, ])

```

```{r}

obj.list <- SplitObject(obj.combined, split.by = "dataset")

obj.list <- lapply(X = obj.list, FUN = function(x) {
    x <- NormalizeData(x)
    x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 1000)
})

features <- SelectIntegrationFeatures(object.list = obj.list, nfeatures = 1000)

```

```{r}

rm(list = c("temp.obj.data", "temp.obj", "objs", "obj.mouse", "obj.opossum", "obj.combined"))

```


```{r}

# obj.list <- lapply(X = obj.list, FUN = function(x) {
#     x <- ScaleData(x, features = features, verbose = FALSE)
#     x <- RunPCA(x, features = features, verbose = FALSE)
# })

```


```{r}

# integ.anchors <- FindIntegrationAnchors(object.list = obj.list, anchor.features = features, reduction = "rpca", dims = 1:30)
# integ.combined <- IntegrateData(anchorset = integ.anchors, dims = 1:30)

```

```{r}

integ.anchors <- FindIntegrationAnchors(object.list = obj.list, anchor.features = features)
integ.combined <- IntegrateData(anchorset = integ.anchors)

```


```{r}

rm(integ.anchors)

```


```{r}

DefaultAssay(integ.combined) <- "integrated"

integ.combined <- ScaleData(integ.combined, verbose = FALSE)
integ.combined <- RunPCA(integ.combined, verbose = FALSE)
integ.combined <- RunUMAP(integ.combined, dims = 1:30)

```

```{r}

meta.data <- read.csv("E:/Opossum_M1/metadata.csv")
rownames(meta.data) <- meta.data$X
meta.data <- subset(meta.data, subset = class == "gabaergic")
integ.combined$subclass_label[rownames(meta.data)] <- as.character(meta.data$seurat_clusters)

```


```{r}

DimPlot(integ.combined, reduction = "umap", group.by = "dataset", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(integ.combined, reduction = "umap", split.by = "dataset", group.by = "subclass_label", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```

```{r}

integ.combined <- FindNeighbors(integ.combined, dims = 1:30)
integ.combined <- FindClusters(integ.combined, resolution = 1, algorithm = 4, method = "igraph")

```


```{r}

DimPlot(integ.combined, reduction = "umap", group.by = "dataset", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(integ.combined, reduction = "umap", split.by = "dataset", group.by = "subclass_label", label = TRUE, raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(integ.combined, reduction = "umap", group.by = "seurat_clusters", label = TRUE, raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(integ.combined, reduction = "umap", split.by = "dataset", group.by = "seurat_clusters", label = TRUE, raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```

```{r}

# integ.combined <- RenameIdents(integ.combined, `1` = "Astro", `2` = "Micro-PVM", `3` = "Oligo", 
#                                 `4` = "Oligo", `5` = "Oligo", `6` = "OPC", `7` = "Astro", `8` = "Oligo", `9` = "Endo",
#                                 `10` = "Astro", `11` = "U-1", `12` = "Astro", `13` = "VLMC", `14` = "Astro", 
#                                 `15` = "Peri-SMC", `16` = "U-2", `17` = "Oligo", `18` = "VLMC", `19` = "U-3", 
#                                 `20` = "Micro-PVM", `21` = "U-4", `22` = "U-5", `23` = "OPC", `24` = "Oligo")

```


```{r}

# DimPlot(integ.combined, reduction = "umap", label = TRUE, raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
# DimPlot(integ.combined, reduction = "umap", split.by = "dataset", label = TRUE, raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

# library(SeuratDisk)
# SaveH5Seurat(integ.combined, "E:/Mouse_Opossum_Non_Combined.h5Seurat", overwrite = FALSE, verbose = TRUE)

```



