---
title: "Mouse M1 GABAergic SST"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
obj.mouse.gabaergic <- LoadH5Seurat("E:/Mouse_M1/seurat/mouse_m1_gabaergic.h5Seurat")

```


```{r}

FeaturePlot(obj.mouse.gabaergic, reduction = "umap", features = c("Sst")) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic, reduction = "umap", features = c("Pvalb")) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="cluster_label", label = TRUE, label.size = 2, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.0.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.1", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.1.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.2", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.2.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.3", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.3.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.4", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.4.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

# SST resolution = 0.5
obj.mouse.gabaergic.sst <- subset(obj.mouse.gabaergic, subset = RNA_snn_res.0.5 == c("2", "9", "10", "14"))
Idents(obj.mouse.gabaergic.sst) <- "RNA_snn_res.0.5"
sst.markers <- FindAllMarkers(obj.mouse.gabaergic.sst, only.pos = TRUE, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 10, order_by = avg_log2FC)
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.0.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DoHeatmap(object = obj.mouse.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 8))
expr <- AverageExpression(obj.mouse.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 8))
ggplot(subset(sst.markers), aes(x = avg_log2FC, fill = cluster)) + stat_ecdf(geom = "step", aes(col = cluster))

```


```{r}

# SST resolution = 1
obj.mouse.gabaergic.sst <- subset(obj.mouse.gabaergic, subset = RNA_snn_res.1 == c("1", "7", "13", "14", "15", "21"))
Idents(obj.mouse.gabaergic.sst) <- "RNA_snn_res.1"
sst.markers <- FindAllMarkers(obj.mouse.gabaergic.sst, only.pos = TRUE, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 10, order_by = avg_log2FC)
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.1", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DoHeatmap(object = obj.mouse.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 7))
expr <- AverageExpression(obj.mouse.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 7))
ggplot(subset(sst.markers), aes(x = avg_log2FC, fill = cluster)) + stat_ecdf(geom = "step", aes(col = cluster))

```


```{r}

# SST resolution = 1.5
obj.mouse.gabaergic.sst <- subset(obj.mouse.gabaergic, subset = RNA_snn_res.1.5 == c("6", "9", "12", "15", "16", "17", "23"))
Idents(obj.mouse.gabaergic.sst) <- "RNA_snn_res.1.5"
sst.markers <- FindAllMarkers(obj.mouse.gabaergic.sst, only.pos = TRUE, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 10, order_by = avg_log2FC)
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.1.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DoHeatmap(object = obj.mouse.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 6))
expr <- AverageExpression(obj.mouse.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 6))
ggplot(subset(sst.markers), aes(x = avg_log2FC, fill = cluster)) + stat_ecdf(geom = "step", aes(col = cluster))

```


```{r}

# SST resolution = 2
obj.mouse.gabaergic.sst <- subset(obj.mouse.gabaergic, subset = RNA_snn_res.2 == c("6", "9", "12", "14", "15", "16", "25", "28"))
Idents(obj.mouse.gabaergic.sst) <- "RNA_snn_res.2"
sst.markers <- FindAllMarkers(obj.mouse.gabaergic.sst, only.pos = TRUE, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 10, order_by = avg_log2FC)
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.2", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DoHeatmap(object = obj.mouse.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 5))
expr <- AverageExpression(obj.mouse.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 5))
ggplot(subset(sst.markers), aes(x = avg_log2FC, fill = cluster)) + stat_ecdf(geom = "step", aes(col = cluster))

```


```{r}

# SST resolution = 2.5
obj.mouse.gabaergic.sst <- subset(obj.mouse.gabaergic, subset = RNA_snn_res.2.5 == c("2", "4", "13", "14", "15", "18", "25", "30", "33"))
Idents(obj.mouse.gabaergic.sst) <- "RNA_snn_res.2.5"
sst.markers <- FindAllMarkers(obj.mouse.gabaergic.sst, only.pos = TRUE, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 10, order_by = avg_log2FC)
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.2.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DoHeatmap(object = obj.mouse.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 4))
expr <- AverageExpression(obj.mouse.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 4))
ggplot(subset(sst.markers), aes(x = avg_log2FC, fill = cluster)) + stat_ecdf(geom = "step", aes(col = cluster))

```


```{r}

# SST resolution = 3
obj.mouse.gabaergic.sst <- subset(obj.mouse.gabaergic, subset = RNA_snn_res.3 == c("2", "9", "10", "14", "15", "16", "27", "31", "32", "36"))
Idents(obj.mouse.gabaergic.sst) <- "RNA_snn_res.3"
sst.markers <- FindAllMarkers(obj.mouse.gabaergic.sst, only.pos = TRUE, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 10, order_by = avg_log2FC)
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.3", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DoHeatmap(object = obj.mouse.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 4))
expr <- AverageExpression(obj.mouse.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 4))
ggplot(subset(sst.markers), aes(x = avg_log2FC, fill = cluster)) + stat_ecdf(geom = "step", aes(col = cluster))

```

