---
title: "Mouse V1 VIP"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
obj.mouse.gabaergic <- LoadH5Seurat("E:/allGABA.h5seurat")

```


```{r}

Idents(obj.mouse.gabaergic) <- "Age"
obj.mouse.gabaergic.P6 <- subset(obj.mouse.gabaergic, idents = c("P6")) # , "P10", "P12", "P14", "P17", "P21"

```


```{r}

obj.mouse.gabaergic.P6 <- FindVariableFeatures(obj.mouse.gabaergic.P6, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(obj.mouse.gabaergic.P6)
obj.mouse.gabaergic.P6 <- ScaleData(obj.mouse.gabaergic.P6, features = all.genes)
obj.mouse.gabaergic.P6 <- RunPCA(obj.mouse.gabaergic.P6, features = VariableFeatures(object = obj.mouse.gabaergic.P6))
ElbowPlot(obj.mouse.gabaergic.P6, ndims = 50)

```


```{r}

obj.mouse.gabaergic.P6 <- FindNeighbors(obj.mouse.gabaergic.P6, dims = 1:30)
obj.mouse.gabaergic.P6 <- FindClusters(obj.mouse.gabaergic.P6, resolution = 1, algorithm = 4, method = "igraph")
obj.mouse.gabaergic.P6 <- RunUMAP(obj.mouse.gabaergic.P6, dims = 1:30, method="umap-learn")

```


```{r}

DimPlot(obj.mouse.gabaergic.P6, reduction = "umap", raster = FALSE) + xlim(-12, 12) + ylim(-12, 12) + coord_equal()

```



```{r}

FeaturePlot(obj.mouse.gabaergic.P6, reduction = "umap", features = c("Pvalb")) + xlim(-12, 12) + ylim(-12, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.P6, reduction = "umap", features = c("Sst")) + xlim(-12, 12) + ylim(-12, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.P6, reduction = "umap", features = c("Vip")) + xlim(-12, 12) + ylim(-12, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.P6, reduction = "umap", features = c("Lamp5")) + xlim(-12, 12) + ylim(-12, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.P6, reduction = "umap", features = c("Sncg")) + xlim(-12, 12) + ylim(-12, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.P6, reduction = "umap", features = c("Frem1")) + xlim(-12, 12) + ylim(-12, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.P6, reduction = "umap", features = c("Stac")) + xlim(-12, 12) + ylim(-12, 12) + coord_equal()

```


```{r}

Idents(obj.mouse.gabaergic) <- "Age"
obj.mouse.gabaergic.P21 <- subset(obj.mouse.gabaergic, idents = c("P21")) # , "P10", "P12", "P14", "P17", "P21"

```


```{r}

obj.mouse.gabaergic.P21 <- FindVariableFeatures(obj.mouse.gabaergic.P21, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(obj.mouse.gabaergic.P21)
obj.mouse.gabaergic.P21 <- ScaleData(obj.mouse.gabaergic.P21, features = all.genes)
obj.mouse.gabaergic.P21 <- RunPCA(obj.mouse.gabaergic.P21, features = VariableFeatures(object = obj.mouse.gabaergic.P21))
ElbowPlot(obj.mouse.gabaergic.P21, ndims = 50)

```


```{r}

obj.mouse.gabaergic.P21 <- FindNeighbors(obj.mouse.gabaergic.P21, dims = 1:30)
obj.mouse.gabaergic.P21 <- FindClusters(obj.mouse.gabaergic.P21, resolution = 1, algorithm = 4, method = "igraph")
obj.mouse.gabaergic.P21 <- RunUMAP(obj.mouse.gabaergic.P21, dims = 1:30, method="umap-learn")

```


```{r}

DimPlot(obj.mouse.gabaergic.P21, reduction = "umap", raster = FALSE) + xlim(-12, 12) + ylim(-12, 12) + coord_equal()

```



```{r}

FeaturePlot(obj.mouse.gabaergic.P21, reduction = "umap", features = c("Pvalb")) + xlim(-12, 12) + ylim(-12, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.P21, reduction = "umap", features = c("Sst")) + xlim(-12, 12) + ylim(-12, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.P21, reduction = "umap", features = c("Vip")) + xlim(-12, 12) + ylim(-12, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.P21, reduction = "umap", features = c("Lamp5")) + xlim(-12, 12) + ylim(-12, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.P21, reduction = "umap", features = c("Sncg")) + xlim(-12, 12) + ylim(-12, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.P21, reduction = "umap", features = c("Frem1")) + xlim(-12, 12) + ylim(-12, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.P21, reduction = "umap", features = c("Stac")) + xlim(-12, 12) + ylim(-12, 12) + coord_equal()

```





