---
title: "Mouse M1 GABAergic"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
obj.mouse.gabaergic <- LoadH5Seurat("E:/Mouse_M1/seurat/mouse_m1_gabaergic.h5Seurat")

```


```{r}

DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by = "subclass_label", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by = "cluster_label", label = TRUE, label.size = 2, raster = FALSE) + NoLegend()  + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by = "RNA_snn_res.1", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by = "RNA_snn_res.1.5", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by = "RNA_snn_res.2", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by = "RNA_snn_res.3", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by = "RNA_snn_res.4", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

Idents(obj.mouse.gabaergic) <- "subclass"
obj.mouse.gabaergic.sst <- subset(obj.mouse.gabaergic, idents = "Sst")
Idents(obj.mouse.gabaergic.sst) <- "RNA_snn_res.2"
all.markers.sst <- FindAllMarkers(obj.mouse.gabaergic.sst, only.pos = TRUE)

```


```{r}

DimPlot(obj.mouse.gabaergic.sst, reduction = "umap", group.by = "RNA_snn_res.2", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
# DimPlot(obj.mouse.gabaergic.sst, reduction = "umap", group.by = "RNA_snn_res.3.merge", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-12, 5) + ylim(-5, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, "Gm13601")  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()

```


```{r}

# 6 -> Nr2f2, Plpp4
# 9 -> Necab1
# 12 -> Maml2
# 14 -> Hpse
# 15 -> Crhr2
# 16 -> Crh
# 28 -> Etv1

DimPlot(obj.mouse.gabaergic.sst, reduction = "umap", group.by = "RNA_snn_res.2", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Nr2f2"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Necab1"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Maml2"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Hpse"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Crhr2"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Crh"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Etv1"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()

```



```{r}

# 6 -> Nr2f2, Plpp4
# 9 -> Necab1
# 12 -> Maml2
# 14 -> Hpse
# 15 -> Crhr2
# 16 -> Crh, Rxfp1
# 28 -> Etv1

DimPlot(obj.mouse.gabaergic.sst, reduction = "umap", group.by = "RNA_snn_res.2", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Tac1"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Calb2"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Pdlim5"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Necab1"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Nr2f2"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Chrna2"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Sema3c"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Hpse"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Ndnf"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Crh"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Rxfp1"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Esm1"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sst, c("Nts"))  + xlim(-12, 5) + ylim(-2, 15) + coord_equal()

```


```{r}

DotPlot(obj.mouse.gabaergic.sst, features = c("Nr2f2", "Necab1", "Calb2", "Hpse", "Crhr2", "Crh", "Etv1"))

```


```{r}

Idents(obj.mouse.gabaergic) <- "RNA_snn_res.2"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 6] <- "Sst"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 6] <- "Sst Nr2f2"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 9] <- "Sst"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 9] <- "Sst Necab1"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 12] <- "Sst"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 12] <- "Sst Calb2"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 14] <- "Sst"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 14] <- "Sst Hpse"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 15] <- "Sst"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 15] <- "Sst Crhr2"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 16] <- "Sst"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 16] <- "Sst Crh"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 28] <- "Sst"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 28] <- "Sst Etv1"

obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 25] <- "Sst Chodl"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 25] <- "Sst Chodl"

```


```{r}

Idents(obj.mouse.gabaergic) <- "subclass"
obj.mouse.gabaergic.pvalb <- subset(obj.mouse.gabaergic, idents = "Pvalb")
Idents(obj.mouse.gabaergic.pvalb) <- "RNA_snn_res.3"
all.markers.pvalb <- FindAllMarkers(obj.mouse.gabaergic.pvalb, only.pos = TRUE)

```


```{r}

DimPlot(obj.mouse.gabaergic.pvalb, reduction = "umap", group.by = "RNA_snn_res.3", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-12, 5) + ylim(-12, 5) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.pvalb, "Th")  + xlim(-12, 5) + ylim(-12, 5) + coord_equal()

```


```{r}

# 6/24 -> Htr2c
# 8/17/21 -> Il1rapl2
# 5/7/28/30 -> Reln
# 34 -> Vipr2
# 25 -> Th, Gabrg1
# 13/22 -> Sema3e

DimPlot(obj.mouse.gabaergic.pvalb, reduction = "umap", group.by = "RNA_snn_res.3", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-12, 5) + ylim(-12, 5) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.pvalb, c("Htr2c"))  + xlim(-12, 5) + ylim(-12, 5) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.pvalb, c("Il1rapl2"))  + xlim(-12, 5) + ylim(-12, 5) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.pvalb, c("Reln"))  + xlim(-12, 5) + ylim(-12, 5) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.pvalb, c("Th"))  + xlim(-12, 5) + ylim(-12, 5) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.pvalb, c("Sema3e"))  + xlim(-12, 5) + ylim(-12, 5) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.pvalb, c("Vipr2"))  + xlim(-12, 5) + ylim(-12, 5) + coord_equal()

```


```{r}

Idents(obj.mouse.gabaergic) <- "RNA_snn_res.3"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.3 == 5] <- "Pvalb"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.3 == 5] <- "Pvalb Reln"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.3 == 6] <- "Pvalb"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.3 == 6] <- "Pvalb Htr2c"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.3 == 7] <- "Pvalb"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.3 == 7] <- "Pvalb Reln"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.3 == 8] <- "Pvalb"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.3 == 8] <- "Pvalb Il1rapl2"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.3 == 13] <- "Pvalb"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.3 == 13] <- "Pvalb Sema3e"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.3 == 17] <- "Pvalb"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.3 == 17] <- "Pvalb Il1rapl2"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.3 == 21] <- "Pvalb"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.3 == 21] <- "Pvalb Il1rapl2"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.3 == 22] <- "Pvalb"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.3 == 22] <- "Pvalb Sema3e"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.3 == 24] <- "Pvalb"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.3 == 24] <- "Pvalb Htr2c"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.3 == 25] <- "Pvalb"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.3 == 25] <- "Pvalb Th"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.3 == 28] <- "Pvalb"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.3 == 28] <- "Pvalb Reln"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.3 == 30] <- "Pvalb"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.3 == 30] <- "Pvalb Reln"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.3 == 34] <- "Pvalb"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.3 == 34] <- "Pvalb Vipr2"

```


```{r}

Idents(obj.mouse.gabaergic) <- "subclass"
obj.mouse.gabaergic.vip <- subset(obj.mouse.gabaergic, idents = "Vip")
Idents(obj.mouse.gabaergic.vip) <- "RNA_snn_res.2"
all.markers.vip <- FindAllMarkers(obj.mouse.gabaergic.vip, only.pos = TRUE)

```


```{r}

DimPlot(obj.mouse.gabaergic.vip, reduction = "umap", group.by = "RNA_snn_res.2", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(2, 14) + ylim(0, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.vip, "Myl1")  + xlim(2, 14) + ylim(0, 12) + coord_equal()

```


```{r}

# 5 -> Chat
# 11 -> Npy
# 18 -> Mybpc1, Htr3a
# 20 -> Reln
# 23 -> Ptger3
# 24 -> Col14a1

DimPlot(obj.mouse.gabaergic.vip, reduction = "umap", group.by = "RNA_snn_res.2", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(2, 14) + ylim(0, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.vip, c("Chat"))  + xlim(2, 14) + ylim(0, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.vip, c("Npy"))  + xlim(2, 14) + ylim(0, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.vip, c("Mybpc1"))  + xlim(2, 14) + ylim(0, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.vip, c("Reln"))  + xlim(2, 14) + ylim(0, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.vip, c("Ptger3"))  + xlim(2, 14) + ylim(0, 12) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.vip, c("Col14a1"))  + xlim(2, 14) + ylim(0, 12) + coord_equal()

```


```{r}

Idents(obj.mouse.gabaergic) <- "RNA_snn_res.2"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 5] <- "Vip"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 5] <- "Vip Chat"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 11] <- "Vip"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 11] <- "Vip Npy"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 18] <- "Vip"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 18] <- "Vip Mybpc1"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 20] <- "Vip"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 20] <- "Vip Reln"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 23] <- "Vip"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 23] <- "Vip Ptger3"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 24] <- "Vip"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 24] <- "Vip Col14a1"

```


```{r}

Idents(obj.mouse.gabaergic) <- "subclass"
obj.mouse.gabaergic.lamp5 <- subset(obj.mouse.gabaergic, idents = "Lamp5")
Idents(obj.mouse.gabaergic.lamp5) <- "RNA_snn_res.2"
all.markers.lamp5 <- FindAllMarkers(obj.mouse.gabaergic.lamp5, only.pos = TRUE)

```


```{r}

DimPlot(obj.mouse.gabaergic.lamp5, reduction = "umap", group.by = "RNA_snn_res.2", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(0, 15) + ylim(-16, -1) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.lamp5, "Ndst3")  + xlim(0, 15) + ylim(-16, -1) + coord_equal()

```


```{r}

# 1 -> Htr1f
# 8 -> Ndnf
# 19 -> Cdh4
# 27 -> Lhx6

DimPlot(obj.mouse.gabaergic.lamp5, reduction = "umap", group.by = "RNA_snn_res.2", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(0, 15) + ylim(-16, -1) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.lamp5, c("Htr1f"))  + xlim(0, 15) + ylim(-16, -1) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.lamp5, c("Ndnf"))  + xlim(0, 15) + ylim(-16, -1) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.lamp5, c("Cdh4"))  + xlim(0, 15) + ylim(-16, -1) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.lamp5, c("Lhx6"))  + xlim(0, 15) + ylim(-16, -1) + coord_equal()

```


```{r}

DotPlot(obj.mouse.gabaergic.lamp5, features = c("Htr1f", "Ndnf", "Cdh4", "Lhx6"))

```


```{r}

Idents(obj.mouse.gabaergic) <- "RNA_snn_res.2"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 1] <- "Lamp5"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 1] <- "Lamp5 Htr1f"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 8] <- "Lamp5"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 8] <- "Lamp5 Ndnf"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 19] <- "Lamp5"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 19] <- "Lamp5 Cdh4"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.2 == 27] <- "Lamp5"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.2 == 27] <- "Lamp5 Lhx6"

```


```{r}

Idents(obj.mouse.gabaergic) <- "subclass"
obj.mouse.gabaergic.sncg <- subset(obj.mouse.gabaergic, idents = "Sncg")
Idents(obj.mouse.gabaergic.sncg) <- "RNA_snn_res.15"
all.markers.sncg <- FindAllMarkers(obj.mouse.gabaergic.sncg, only.pos = TRUE)

```


```{r}

DimPlot(obj.mouse.gabaergic.sncg, reduction = "umap", group.by = "RNA_snn_res.15", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(2, 12) + ylim(-5, 5) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sncg, "Cpne5")  + xlim(2, 12) + ylim(-5, 5) + coord_equal()

```


```{r}

# 4/87 -> Vip
# 60 -> Slc17a8
# 104 -> Cpne5

DimPlot(obj.mouse.gabaergic.sncg, reduction = "umap", group.by = "RNA_snn_res.15", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(2, 12) + ylim(-5, 5) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sncg, c("Slc17a8"))  + xlim(2, 12) + ylim(-5, 5) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sncg, c("Cpne5"))  + xlim(2, 12) + ylim(-5, 5) + coord_equal()
FeaturePlot(obj.mouse.gabaergic.sncg, c("Vip"))  + xlim(2, 12) + ylim(-5, 5) + coord_equal()

```


```{r}

Idents(obj.mouse.gabaergic) <- "RNA_snn_res.15"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.15 == 4] <- "Sncg"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.15 == 4] <- "Sncg Vip"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.15 == 60] <- "Sncg"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.15 == 60] <- "Sncg Slc17a8"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.15 == 87] <- "Sncg"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.15 == 87] <- "Sncg Vip"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.15 == 104] <- "Sncg"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.15 == 104] <- "Sncg Cpne5"

```


```{r}

Idents(obj.mouse.gabaergic) <- "RNA_snn_res.4"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$RNA_snn_res.4 == 46] <- "Meis2"
obj.mouse.gabaergic$type[obj.mouse.gabaergic$RNA_snn_res.4 == 46] <- "Meis2"

```


```{r}

DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by = "subclass", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by = "type", label = TRUE, label.size = 3, raster = FALSE) + NoLegend()  + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

Idents(obj.mouse.gabaergic) <- "subclass"
SaveH5Seurat(obj.mouse.gabaergic, "E:/Mouse_M1/seurat/mouse_m1_gabaergic.h5seurat", overwrite = TRUE, verbose = TRUE)

```

