---
title: "Mouse M1 Glutamatergic"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
obj.mouse.glutamatergic <- LoadH5Seurat("E:/Mouse_M1/seurat/mouse_m1_glutamatergic.h5Seurat")

```


```{r}

obj.mouse.glutamatergic <- FindVariableFeatures(obj.mouse.glutamatergic, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(obj.mouse.glutamatergic)
obj.mouse.glutamatergic <- ScaleData(obj.mouse.glutamatergic, features = all.genes)
obj.mouse.glutamatergic <- RunPCA(obj.mouse.glutamatergic, features = VariableFeatures(object = obj.mouse.glutamatergic))
ElbowPlot(obj.mouse.glutamatergic, ndims = 50)

```


```{r}

obj.mouse.glutamatergic <- FindNeighbors(obj.mouse.glutamatergic, dims = 1:30)
obj.mouse.glutamatergic <- FindClusters(obj.mouse.glutamatergic, resolution = 1, algorithm = 4, method = "igraph")
obj.mouse.glutamatergic <- RunUMAP(obj.mouse.glutamatergic, dims = 1:30, method="umap-learn")

```


```{r}

obj.mouse.glutamatergic$subclass <- obj.mouse.glutamatergic$subclass_label
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$subclass == "L6 IT Car3"] <- "L6 IT"
obj.mouse.glutamatergic$type <- NA

```


```{r}

DimPlot(obj.mouse.glutamatergic, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
DimPlot(obj.mouse.glutamatergic, reduction = "umap", group.by = "donor_id", raster = FALSE) + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
DimPlot(obj.mouse.glutamatergic, reduction = "umap", group.by = "subclass", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
DimPlot(obj.mouse.glutamatergic, reduction = "umap", group.by = "cluster_label", label = TRUE, label.size = 2,raster = FALSE) + NoLegend()  + xlim(-17, 13) + ylim(-18, 12) + coord_equal()

```


```{r}

FeaturePlot(obj.mouse.glutamatergic, "Cux2") + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic, "Rorb") + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic, "Rspo1") + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic, "Deptor") + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic, "Foxo1") + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic, "Ptprm") + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic, "Zfp804b") + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic, "Cdh9") + xlim(-17, 13) + ylim(-18, 12) + coord_equal()

```


```{r}

obj.mouse.glutamatergic <- FindClusters(obj.mouse.glutamatergic, resolution = 0.5, algorithm = 4, method = "igraph")
obj.mouse.glutamatergic <- FindClusters(obj.mouse.glutamatergic, resolution = 1.5, algorithm = 4, method = "igraph")
obj.mouse.glutamatergic <- FindClusters(obj.mouse.glutamatergic, resolution = 2, algorithm = 4, method = "igraph")

```


```{r}

DimPlot(obj.mouse.glutamatergic, reduction = "umap", group.by="RNA_snn_res.0.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
DimPlot(obj.mouse.glutamatergic, reduction = "umap", group.by="RNA_snn_res.1", label = TRUE, raster = FALSE) + NoLegend() + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
DimPlot(obj.mouse.glutamatergic, reduction = "umap", group.by="RNA_snn_res.1.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
DimPlot(obj.mouse.glutamatergic, reduction = "umap", group.by="RNA_snn_res.2", label = TRUE, raster = FALSE) + NoLegend() + xlim(-17, 13) + ylim(-18, 12) + coord_equal()

```


```{r}

FeaturePlot(obj.mouse.glutamatergic, "Cdh12") + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic, "Pdzrn3") + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic, "St6galnac5") + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic, "Bmpr1b") + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic, "Il1rapl2") + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic, "Sulf1") + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic, "Osr1") + xlim(-17, 13) + ylim(-18, 12) + coord_equal()

```


```{r}

Idents(obj.mouse.glutamatergic) <- "RNA_snn_res.1"

cells.l23it <- WhichCells(obj.mouse.glutamatergic, ident = c("2", "6", "10", "14"))
obj.mouse.glutamatergic$subclass <- ifelse(colnames(obj.mouse.glutamatergic) %in% cells.l23it, "L2/3 IT", "ambiguous")

cells.l5it <- WhichCells(obj.mouse.glutamatergic, ident = c("1", "4", "5", "8", "13", "19"))
obj.mouse.glutamatergic$subclass[cells.l5it] <- "L5 IT"

cells.l6it <- WhichCells(obj.mouse.glutamatergic, ident = c("7", "9"))
obj.mouse.glutamatergic$subclass[cells.l6it] <- "L6 IT"

cells.l5et <- WhichCells(obj.mouse.glutamatergic, ident = c("15", "20"))
obj.mouse.glutamatergic$subclass[cells.l5et] <- "L5 ET"

cells.l6ct <- WhichCells(obj.mouse.glutamatergic, ident = c("3", "11", "12", "17"))
obj.mouse.glutamatergic$subclass[cells.l6ct] <- "L6 CT"

cells.l56np <- WhichCells(obj.mouse.glutamatergic, ident = c("16"))
obj.mouse.glutamatergic$subclass[cells.l56np] <- "L5/6 NP"

cells.l6b <- WhichCells(obj.mouse.glutamatergic, ident = c("18"))
obj.mouse.glutamatergic$subclass[cells.l6b] <- "L6b"

Idents(obj.mouse.glutamatergic) <- "subclass"
obj.mouse.glutamatergic <- subset(obj.mouse.glutamatergic, subset = subclass != "ambiguous")

```


```{r}

DimPlot(obj.mouse.glutamatergic, reduction = "umap", group.by = "subclass", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-17, 13) + ylim(-18, 12) + coord_equal()

```


```{r}

Idents(obj.mouse.glutamatergic) <- "subclass"
obj.mouse.glutamatergic.l23it <- subset(obj.mouse.glutamatergic, idents = "L2/3 IT")
Idents(obj.mouse.glutamatergic.l23it) <- "RNA_snn_res.1"
all.markers.l23it <- FindAllMarkers(obj.mouse.glutamatergic.l23it, only.pos = TRUE)

```


```{r}

DimPlot(obj.mouse.glutamatergic.l23it, reduction = "umap", group.by = "RNA_snn_res.1", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-4, 10) + ylim(0, 14) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l23it, "Cdh13")  + xlim(-4, 10) + ylim(0, 14) + coord_equal()
VlnPlot(obj.mouse.glutamatergic.l23it, "Cdh13", group.by = "RNA_snn_res.1")

```


```{r}

# 2 -> Scg2
# 6 -> Rcan2
# 10 -> Cntnap5c
# 14 -> Adamts2

DimPlot(obj.mouse.glutamatergic.l23it, reduction = "umap", group.by = "RNA_snn_res.1", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-4, 10) + ylim(0, 14) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l23it, c("Scg2"))  + xlim(-4, 10) + ylim(0, 14) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l23it, c("Rcan2"))  + xlim(-4, 10) + ylim(0, 14) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l23it, c("Cntnap5c"))  + xlim(-4, 10) + ylim(0, 14) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l23it, c("Adamts2"))  + xlim(-4, 10) + ylim(0, 14) + coord_equal()

```


```{r}

Idents(obj.mouse.glutamatergic) <- "RNA_snn_res.1"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1 == 2] <- "L2/3 IT"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1 == 2] <- "L2/3 IT Scg2"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1 == 6] <- "L2/3 IT"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1 == 6] <- "L2/3 IT Rcan2"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1 == 10] <- "L2/3 IT"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1 == 10] <- "L2/3 IT Cntnap5c"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1 == 14] <- "L2/3 IT"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1 == 14] <- "L2/3 IT Adamts2"

```


```{r}

Idents(obj.mouse.glutamatergic) <- "subclass"
obj.mouse.glutamatergic.l5it <- subset(obj.mouse.glutamatergic, idents = "L5 IT")
Idents(obj.mouse.glutamatergic.l5it) <- "RNA_snn_res.1"
all.markers.l5it <- FindAllMarkers(obj.mouse.glutamatergic.l5it, only.pos = TRUE)

```


```{r}

DimPlot(obj.mouse.glutamatergic.l5it, reduction = "umap", group.by = "RNA_snn_res.1", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-5, 15) + ylim(-10, 10) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l5it, "Zfhx4")  + xlim(-5, 15) + ylim(-10, 10) + coord_equal()
VlnPlot(obj.mouse.glutamatergic.l5it, "Zfhx4", group.by = "RNA_snn_res.1")

```


```{r}

# 1 -> Grik3
# 4 -> Spock3
# 5 -> Pld5
# 8 -> Pcsk5
# 13 -> Zfhx4
# 19 -> ambiguous

DimPlot(obj.mouse.glutamatergic.l5it, reduction = "umap", group.by = "RNA_snn_res.1", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-5, 15) + ylim(-10, 10) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l5it, c("Grik3"))  + xlim(-5, 15) + ylim(-10, 10) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l5it, c("Spock3"))  + xlim(-5, 15) + ylim(-10, 10) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l5it, c("Pld5"))  + xlim(-5, 15) + ylim(-10, 10) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l5it, c("Pcsk5"))  + xlim(-5, 15) + ylim(-10, 10) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l5it, c("Zfhx4"))  + xlim(-5, 15) + ylim(-10, 10) + coord_equal()

```


```{r}

Idents(obj.mouse.glutamatergic) <- "RNA_snn_res.1"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1 == 1] <- "L5 IT"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1 == 1] <- "L5 IT Grik3"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1 == 4] <- "L5 IT"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1 == 4] <- "L5 IT Spock3"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1 == 5] <- "L5 IT"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1 == 5] <- "L5 IT Pld5"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1 == 8] <- "L5 IT"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1 == 8] <- "L5 IT Pcsk5"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1 == 13] <- "L5 IT"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1 == 13] <- "L5 IT Zfhx4"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1 == 19] <- "ambiguous"

Idents(obj.mouse.glutamatergic) <- "subclass"
obj.mouse.glutamatergic <- subset(obj.mouse.glutamatergic, subset = subclass != "ambiguous")

```


```{r}

Idents(obj.mouse.glutamatergic) <- "subclass"
obj.mouse.glutamatergic.l6it <- subset(obj.mouse.glutamatergic, idents = "L6 IT")
Idents(obj.mouse.glutamatergic.l6it) <- "RNA_snn_res.1"
all.markers.l6it <- FindAllMarkers(obj.mouse.glutamatergic.l6it, only.pos = TRUE)

```


```{r}

DimPlot(obj.mouse.glutamatergic.l6it, reduction = "umap", group.by = "RNA_snn_res.1", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-5, 15) + ylim(-15, 5) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l6it, "Grik3")  + xlim(-5, 15) + ylim(-15, 5) + coord_equal()
VlnPlot(obj.mouse.glutamatergic.l6it, "Grik3", group.by = "RNA_snn_res.1")

```


```{r}

# 7 -> Pld5
# 9 -> Zfp804b

DimPlot(obj.mouse.glutamatergic.l6it, reduction = "umap", group.by = "RNA_snn_res.1", label = TRUE, label.size = 4, raster = FALSE) + NoLegend() + xlim(-5, 15) + ylim(-15, 5) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l6it, c("Pld5"))  + xlim(-5, 15) + ylim(-15, 5) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l6it, c("Zfp804b"))  + xlim(-5, 15) + ylim(-15, 5) + coord_equal()

```


```{r}

Idents(obj.mouse.glutamatergic) <- "RNA_snn_res.1"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1 == 7] <- "L6 IT"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1 == 7] <- "L6 IT Pld5"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1 == 9] <- "L6 IT"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1 == 9] <- "L6 IT Zfp804b"

```


```{r}

Idents(obj.mouse.glutamatergic) <- "subclass"
obj.mouse.glutamatergic.l5et <- subset(obj.mouse.glutamatergic, idents = "L5 ET")
Idents(obj.mouse.glutamatergic.l5et) <- "RNA_snn_res.1"
all.markers.l5et <- FindAllMarkers(obj.mouse.glutamatergic.l5et, only.pos = TRUE)

```


```{r}

DimPlot(obj.mouse.glutamatergic.l5et, reduction = "umap", group.by = "RNA_snn_res.1", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-5, 15) + ylim(-18, 2) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l5et, "Tshz2")  + xlim(-5, 15) + ylim(-18, 2) + coord_equal()
VlnPlot(obj.mouse.glutamatergic.l5et, "Tshz2", group.by = "RNA_snn_res.1")

```


```{r}

# 15 -> Kcnab1
# 20 -> Tshz2

DimPlot(obj.mouse.glutamatergic.l5et, reduction = "umap", group.by = "RNA_snn_res.1", label = TRUE, label.size = 4, raster = FALSE) + NoLegend() + xlim(-5, 15) + ylim(-18, 2) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l5et, c("Kcnab1"))  + xlim(-5, 15) + ylim(-18, 2) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l5et, c("Tshz2"))  + xlim(-5, 15) + ylim(-18, 2) + coord_equal()

```


```{r}

Idents(obj.mouse.glutamatergic) <- "RNA_snn_res.1"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1 == 15] <- "L5 ET"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1 == 15] <- "L5 ET Kcnab1"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1 == 20] <- "L5 ET"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1 == 20] <- "L5 ET Tshz2"

```


```{r}

Idents(obj.mouse.glutamatergic) <- "subclass"
obj.mouse.glutamatergic.l6ct <- subset(obj.mouse.glutamatergic, idents = "L6 CT")
Idents(obj.mouse.glutamatergic.l6ct) <- "RNA_snn_res.1.5"
all.markers.l6ct <- FindAllMarkers(obj.mouse.glutamatergic.l6ct, only.pos = TRUE)

```


```{r}

DimPlot(obj.mouse.glutamatergic.l6ct, reduction = "umap", group.by = "RNA_snn_res.1.5", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-15, 5) + ylim(-10, 10) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l6ct, "Egfem1")  + xlim(-15, 5) + ylim(-10, 10) + coord_equal()
VlnPlot(obj.mouse.glutamatergic.l6ct, "Egfem1", group.by = "RNA_snn_res.1.5")

```


```{r}

# 5 -> Egfem1
# 8 -> Brinp3
# 10 -> Egfem1
# 20 -> Brinp3
# 21 -> Gm10635

DimPlot(obj.mouse.glutamatergic.l6ct, reduction = "umap", group.by = "RNA_snn_res.1.5", label = TRUE, label.size = 4, raster = FALSE) + NoLegend() + xlim(-15, 5) + ylim(-10, 10) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l6ct, c("Egfem1"))  + xlim(-15, 5) + ylim(-10, 10) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l6ct, c("Brinp3"))  + xlim(-15, 5) + ylim(-10, 10) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l6ct, c("Gm10635"))  + xlim(-15, 5) + ylim(-10, 10) + coord_equal()

```


```{r}

Idents(obj.mouse.glutamatergic) <- "RNA_snn_res.1.5"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1.5 == 5] <- "L6 CT"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1.5 == 5] <- "L6 CT Egfem1"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1.5 == 8] <- "L6 CT"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1.5 == 8] <- "L6 CT Brinp3"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1.5 == 10] <- "L6 CT"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1.5 == 10] <- "L6 CT Egfem1"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1.5 == 20] <- "L6 CT"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1.5 == 20] <- "L6 CT Brinp3"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1.5 == 21] <- "L6 CT"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1.5 == 21] <- "L6 CT Gm10635"

```


```{r}

Idents(obj.mouse.glutamatergic) <- "subclass"
obj.mouse.glutamatergic.l56np <- subset(obj.mouse.glutamatergic, idents = "L5/6 NP")
Idents(obj.mouse.glutamatergic.l56np) <- "RNA_snn_res.1.5"
all.markers.l56np <- FindAllMarkers(obj.mouse.glutamatergic.l56np, only.pos = TRUE)

```


```{r}

DimPlot(obj.mouse.glutamatergic.l56np, reduction = "umap", group.by = "RNA_snn_res.1.5", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-15, 5) + ylim(-10, 10) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l56np, "Tmem132d")  + xlim(-15, 5) + ylim(-10, 10) + coord_equal()
VlnPlot(obj.mouse.glutamatergic.l56np, "Tmem132d", group.by = "RNA_snn_res.1.5")

```


```{r}

# 22 -> Inpp4b
# 27 -> Tmem132d

DimPlot(obj.mouse.glutamatergic.l56np, reduction = "umap", group.by = "RNA_snn_res.1.5", label = TRUE, label.size = 4, raster = FALSE) + NoLegend() + xlim(-15, 5) + ylim(-10, 10) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l56np, c("Inpp4b"))  + xlim(-15, 5) + ylim(-10, 10) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.l56np, c("Tmem132d"))  + xlim(-15, 5) + ylim(-10, 10) + coord_equal()

```


```{r}

Idents(obj.mouse.glutamatergic) <- "RNA_snn_res.1.5"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1.5 == 22] <- "L5/6 NP"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1.5 == 22] <- "L5/6 NP Inpp4b"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1.5 == 27] <- "L5/6 NP"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1.5 == 27] <- "L5/6 NP Tmem132d"

```


```{r}

Idents(obj.mouse.glutamatergic) <- "RNA_snn_res.1"
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$RNA_snn_res.1 == 18] <- "L6b"
obj.mouse.glutamatergic$type[obj.mouse.glutamatergic$RNA_snn_res.1 == 18] <- "L6b"

```



```{r}

DimPlot(obj.mouse.glutamatergic, reduction = "umap", group.by = "subclass", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-17, 13) + ylim(-18, 12) + coord_equal()
DimPlot(obj.mouse.glutamatergic, reduction = "umap", group.by = "type", label = TRUE, label.size = 4, raster = FALSE) + NoLegend()  + xlim(-17, 13) + ylim(-18, 12) + coord_equal()

```


```{r}

Idents(obj.mouse.glutamatergic) <- "subclass"
SaveH5Seurat(obj.mouse.glutamatergic, "E:/Mouse_M1/seurat/mouse_m1_glutamatergic_types.h5seurat", overwrite = TRUE, verbose = TRUE)

```

