
```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)

matrix <- readRDS("E:/Mouse_M1/Mouse_M1_10xV3_Matrix.RDS")
meta_tb <- arrow::read_feather("E:/Mouse_M1/Mouse_M1_10xV3_Metadata.feather")
meta_df <- as.data.frame(meta_tb)
row.names(meta_df) <- meta_df[, "sample_id"]
obj.mouse <- CreateSeuratObject(counts = matrix, meta.data = meta_df)
rm(list = c("matrix", "meta_df", "meta_tb"))

```


```{r}

obj.mouse <- AddMetaData(obj.mouse, metadata = unlist(rep(list("Mouse_M1"), ncol(obj.mouse))), col.name = "dataset")
Idents(object = obj.mouse) <- obj.mouse[["dataset"]]
obj.mouse[["percent.mt"]] <- PercentageFeatureSet(obj.mouse, pattern = "^mt-")
VlnPlot(obj.mouse, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
plot1 <- FeatureScatter(obj.mouse, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot2 <- FeatureScatter(obj.mouse, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot1 + plot2

```
```{r}

obj.mouse <- NormalizeData(obj.mouse, normalization.method = "LogNormalize", scale.factor = 10000)
obj.mouse <- FindVariableFeatures(obj.mouse, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(obj.mouse)
obj.mouse <- ScaleData(obj.mouse, features = all.genes)
obj.mouse <- RunPCA(obj.mouse, features = VariableFeatures(object = obj.mouse))
ElbowPlot(obj.mouse, ndims = 50)

```


```{r}

obj.mouse <- FindNeighbors(obj.mouse, dims = 1:30)
obj.mouse <- FindClusters(obj.mouse, resolution = 1, algorithm = 4, method = "igraph")
obj.mouse <- RunUMAP(obj.mouse, dims = 1:30, method="umap-learn")

```


```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
obj.mouse <- LoadH5Seurat("E:/Mouse_M1/seurat/mouse_m1_all.h5Seurat")

```


```{r}

Idents(obj.mouse) <- "RNA_snn_res.1"
DimPlot(obj.mouse, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse, reduction = "umap", group.by = "subclass_label", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```

```{r}

cells.glutamatergic <- WhichCells(obj.mouse, ident = c(1, 3, 5, 6, 7, 10, 15, 17, 21))
obj.mouse$class <- ifelse(colnames(obj.mouse) %in% cells.glutamatergic, "glutamatergic", "ambiguous")

cells.gabaergic <- WhichCells(obj.mouse, ident = c(11, 16, 18, 20, 28, 29, 30))
obj.mouse$class[cells.gabaergic] <- "gabaergic"

cells.nonneuronal <- WhichCells(obj.filt, ident = c(8, 10, 19, 20, 24, 25, 28, 32))
obj.filt$class[cells.nonneuronal] <- "nonneuronal"

```


```{r}

obj.mouse.gabaergic <- subset(obj.mouse, subset = class == "gabaergic")

```


```{r}

obj.mouse.gabaergic <- FindVariableFeatures(obj.mouse.gabaergic, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(obj.mouse.gabaergic)
obj.mouse.gabaergic <- ScaleData(obj.mouse.gabaergic, features = all.genes)
obj.mouse.gabaergic <- RunPCA(obj.mouse.gabaergic, features = VariableFeatures(object = obj.mouse.gabaergic))
ElbowPlot(obj.mouse.gabaergic, ndims = 50)

```

```{r}

obj.mouse.gabaergic <- FindNeighbors(obj.mouse.gabaergic, dims = 1:30)
obj.mouse.gabaergic <- FindClusters(obj.mouse.gabaergic, resolution = 1, algorithm = 4, method = "igraph")
obj.mouse.gabaergic <- RunUMAP(obj.mouse.gabaergic, dims = 1:30, method="umap-learn")

```


```{r}

obj.mouse.gabaergic <- FindClusters(obj.mouse.gabaergic, resolution = 1, algorithm = 4, method = "igraph")

```


```{r}

DimPlot(obj.mouse.gabaergic, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by = "subclass_label", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by = "cluster_label", label = FALSE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

FeaturePlot(obj.mouse.gabaergic, reduction = "umap", features = c("Sst")) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic, reduction = "umap", features = c("Pvalb")) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic, reduction = "umap", features = c("Vip")) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic, reduction = "umap", features = c("Lamp5")) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic, reduction = "umap", features = c("Sncg")) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.mouse.gabaergic, reduction = "umap", features = c("Meis2")) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

obj.mouse.gabaergic <- FindClusters(obj.mouse.gabaergic, resolution = 0.5, algorithm = 4, method = "igraph")
obj.mouse.gabaergic <- FindClusters(obj.mouse.gabaergic, resolution = 1.5, algorithm = 4, method = "igraph")
obj.mouse.gabaergic <- FindClusters(obj.mouse.gabaergic, resolution = 2, algorithm = 4, method = "igraph")
obj.mouse.gabaergic <- FindClusters(obj.mouse.gabaergic, resolution = 2.5, algorithm = 4, method = "igraph")
obj.mouse.gabaergic <- FindClusters(obj.mouse.gabaergic, resolution = 3, algorithm = 4, method = "igraph")

```


```{r}

DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.0.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.1", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.1.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.2", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.2.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse.gabaergic, reduction = "umap", group.by="RNA_snn_res.3", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

SaveH5Seurat(obj.mouse.gabaergic, "E:/Mouse_M1/seurat/mouse_m1_gabaergic.h5seurat", overwrite = TRUE, verbose = TRUE)

```


```{r}

# SST resolution = 0.5
obj.mouse.gabaergic.sst <- subset(obj.mouse.gabaergic, subset = RNA_snn_res.0.5 == c("2", "8", "10", "15"))
Idents(obj.mouse.gabaergic.sst) <- "RNA_snn_res.0.5"
sst.markers <- FindAllMarkers(obj.mouse.gabaergic.sst, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 5, order_by = avg_log2FC)

DoHeatmap(object = obj.mouse.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red"))
expr <- AverageExpression(obj.mouse.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red"))

```


```{r}

# SST resolution = 1
obj.mouse.gabaergic.sst <- subset(obj.mouse.gabaergic, subset = RNA_snn_res.1 == c("2", "9", "12", "14", "15", "21"))
Idents(obj.mouse.gabaergic.sst) <- "RNA_snn_res.1"
sst.markers <- FindAllMarkers(obj.mouse.gabaergic.sst, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 5, order_by = avg_log2FC)

DoHeatmap(object = obj.mouse.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red"))
expr <- AverageExpression(obj.mouse.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red"))

```

```{r}

# SST resolution = 1.5
obj.mouse.gabaergic.sst <- subset(obj.mouse.gabaergic, subset = RNA_snn_res.1.5 == c("5", "9", "11", "14", "16", "17", "25"))
Idents(obj.mouse.gabaergic.sst) <- "RNA_snn_res.1.5"
sst.markers <- FindAllMarkers(obj.mouse.gabaergic.sst, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 5, order_by = avg_log2FC)

DoHeatmap(object = obj.mouse.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red"))
expr <- AverageExpression(obj.mouse.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red"))

```


```{r}

# SST resolution = 2
obj.mouse.gabaergic.sst <- subset(obj.mouse.gabaergic, subset = RNA_snn_res.2 == c("8", "9", "11", "14", "16", "17", "26", "29"))
Idents(obj.mouse.gabaergic.sst) <- "RNA_snn_res.2"
sst.markers <- FindAllMarkers(obj.mouse.gabaergic.sst, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 5, order_by = avg_log2FC)

DoHeatmap(object = obj.mouse.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red"))
expr <- AverageExpression(obj.mouse.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red"))

```


```{r}

# SST resolution = 2.5
obj.mouse.gabaergic.sst <- subset(obj.mouse.gabaergic, subset = RNA_snn_res.2.5 == c("6", "7", "9", "12", "15", "16", "29", "32"))
Idents(obj.mouse.gabaergic.sst) <- "RNA_snn_res.2.5"
sst.markers <- FindAllMarkers(obj.mouse.gabaergic.sst, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 5, order_by = avg_log2FC)

DoHeatmap(object = obj.mouse.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red"))
expr <- AverageExpression(obj.mouse.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red"))

```


```{r}

# SST resolution = 3
obj.mouse.gabaergic.sst <- subset(obj.mouse.gabaergic, subset = RNA_snn_res.3 == c("4", "6", "11", "14", "15", "16", "27", "33", "36"))
Idents(obj.mouse.gabaergic.sst) <- "RNA_snn_res.3"
sst.markers <- FindAllMarkers(obj.mouse.gabaergic.sst, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 5, order_by = avg_log2FC)

DoHeatmap(object = obj.mouse.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red"))
expr <- AverageExpression(obj.mouse.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red"))

```


```{r}

library(SeuratDisk)

SaveH5Seurat(obj.mouse.gabaergic, "E:/Mouse_M1/seurat/mouse_m1_gabaergic.h5seurat", overwrite = TRUE, verbose = TRUE)

obj.mouse.gabaergic.sst <- subset(obj.mouse.gabaergic, subset = RNA_snn_res.3 == c("4", "6", "11", "14", "15", "16", "27", "33", "36"))
SaveH5Seurat(obj.mouse.gabaergic.sst, "E:/Mouse_M1/seurat/mouse_m1_gabaergic_sst.h5seurat", overwrite = TRUE, verbose = TRUE)

```


```{r}

obj.mouse.gabaergic.pv <- subset(obj.mouse.gabaergic, subset = RNA_snn_res.2.5 == c("2", "3", "5", "10", "11", "19", "20", "22", "23", "30"))
SaveH5Seurat(obj.mouse.gabaergic.pv, "E:/Mouse_M1/seurat/mouse_m1_gabaergic_pv.h5seurat", overwrite = TRUE, verbose = TRUE)

```


```{r}

obj.mouse.gabaergic.vip <- subset(obj.mouse.gabaergic, subset = RNA_snn_res.2.5 == c("8", "14", "17", "21", "24", "27", "28"))
SaveH5Seurat(obj.mouse.gabaergic.vip, "E:/Mouse_M1/seurat/mouse_m1_gabaergic_vip.h5seurat", overwrite = TRUE, verbose = TRUE)

```

