---
title: "Opossum M1 GABAergic"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
obj.opossum.glutamatergic <- LoadH5Seurat("E:/Opossum_M1/seurat/opossum_m1_glutamatergic.h5Seurat")

```


```{r}

obj.opossum.glutamatergic <- FindVariableFeatures(obj.opossum.glutamatergic, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(obj.opossum.glutamatergic)
obj.opossum.glutamatergic <- ScaleData(obj.opossum.glutamatergic, features = all.genes)
obj.opossum.glutamatergic <- RunPCA(obj.opossum.glutamatergic, features = VariableFeatures(object = obj.opossum.glutamatergic))
ElbowPlot(obj.opossum.glutamatergic, ndims = 50)

```


```{r}

obj.opossum.glutamatergic <- FindNeighbors(obj.opossum.glutamatergic, dims = 1:30)
obj.opossum.glutamatergic <- FindClusters(obj.opossum.glutamatergic, resolution = 1, algorithm = 4, method = "igraph")
obj.opossum.glutamatergic <- RunUMAP(obj.opossum.glutamatergic, dims = 1:30, method = "umap-learn")

```


```{r}

# DimPlot(obj.opossum.glutamatergic, reduction = "umap", group.by = "RNA_snn_res.1.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 12) + ylim(-18, 12) + coord_equal()
# DimPlot(obj.opossum.glutamatergic, reduction = "umap", group.by = "sample", raster = FALSE) + xlim(-18, 15) + ylim(-18, 15) + coord_equal()
# DimPlot(obj.opossum.glutamatergic, reduction = "umap", group.by = "predicted_doublets", raster = FALSE) + xlim(-18, 15) + ylim(-18, 15) + coord_equal()
DimPlot(obj.opossum.glutamatergic, reduction = "umap", group.by = "subclass", cols = c("#F8766D", "#C49A00", "#53B400", "#00C094", "#00B6EB", "#FB61D7"), label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 12) + ylim(-18, 12) + coord_equal()
# ggsave(file="G:/Shared drives/Opossum transcriptomics/figures/Opossum_M1_Glutamatergic_Subclass.svg", plot=subclass_plot, width=4, height=4)

```


```{r}

FeaturePlot(obj.opossum.glutamatergic, reduction = "umap", features = c("Ptprm")) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

obj.opossum.glutamatergic <- FindClusters(obj.opossum.glutamatergic, resolution = 0.5, algorithm = 4, method = "igraph")
obj.opossum.glutamatergic <- FindClusters(obj.opossum.glutamatergic, resolution = 1.5, algorithm = 4, method = "igraph")
obj.opossum.glutamatergic <- FindClusters(obj.opossum.glutamatergic, resolution = 2, algorithm = 4, method = "igraph")
obj.opossum.glutamatergic <- FindClusters(obj.opossum.glutamatergic, resolution = 2.5, algorithm = 4, method = "igraph")
obj.opossum.glutamatergic <- FindClusters(obj.opossum.glutamatergic, resolution = 3, algorithm = 4, method = "igraph")

```


```{r}

DimPlot(obj.opossum.glutamatergic, reduction = "umap", group.by="RNA_snn_res.0.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-12, 15) + ylim(-12, 15) + coord_equal()
DimPlot(obj.opossum.glutamatergic, reduction = "umap", group.by="RNA_snn_res.1", label = TRUE, raster = FALSE) + NoLegend() + xlim(-12, 15) + ylim(-12, 15) + coord_equal()
DimPlot(obj.opossum.glutamatergic, reduction = "umap", group.by="RNA_snn_res.1.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-12, 15) + ylim(-12, 15) + coord_equal()
DimPlot(obj.opossum.glutamatergic, reduction = "umap", group.by="RNA_snn_res.2", label = TRUE, raster = FALSE) + NoLegend() + xlim(-12, 15) + ylim(-12, 15) + coord_equal()
DimPlot(obj.opossum.glutamatergic, reduction = "umap", group.by="RNA_snn_res.2.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-12, 15) + ylim(-12, 15) + coord_equal()
DimPlot(obj.opossum.glutamatergic, reduction = "umap", group.by="RNA_snn_res.3", label = TRUE, raster = FALSE) + NoLegend() + xlim(-12, 15) + ylim(-12, 15) + coord_equal()

```


```{r}

Idents(obj.opossum.glutamatergic) <- "RNA_snn_res.1.5"
cells.l23it <- WhichCells(obj.opossum.glutamatergic, ident = c("2", "4", "8", "12", "15", "21"))
obj.opossum.glutamatergic$subclass <- ifelse(colnames(obj.opossum.glutamatergic) %in% cells.l23it, "L2/3 IT", "ambiguous")

cells.l5it <- WhichCells(obj.opossum.glutamatergic, ident = c("6", "9", "10", "11", "13", "14", "16", "20", "22"))
obj.opossum.glutamatergic$subclass[cells.l5it] <- "L5 IT"

# cells.l6it <- WhichCells(obj.opossum.glutamatergic, ident = c("9"))
# obj.opossum.glutamatergic$subclass[cells.l6it] <- "L6 IT"

cells.l5et <- WhichCells(obj.opossum.glutamatergic, ident = c("7"))
obj.opossum.glutamatergic$subclass[cells.l5et] <- "L5 ET"

cells.l56np <- WhichCells(obj.opossum.glutamatergic, ident = c("17", "23"))
obj.opossum.glutamatergic$subclass[cells.l56np] <- "L5/6 NP"

cells.l6b <- WhichCells(obj.opossum.glutamatergic, ident = c("19"))
obj.opossum.glutamatergic$subclass[cells.l6b] <- "L6b"

cells.l6ct <- WhichCells(obj.opossum.glutamatergic, ident = c("1", "5", "3", "18"))
obj.opossum.glutamatergic$subclass[cells.l6ct] <- "L6 CT"

Idents(obj.opossum.glutamatergic) <- "subclass"
obj.opossum.glutamatergic <- subset(obj.opossum.glutamatergic, subset = subclass != "ambiguous")

```


```{r, fig.width=4, fig.height=4}

library(viridis)

Idents(obj.opossum.glutamatergic) <- "subclass"
levels(obj.opossum.glutamatergic) <- c("L2/3 IT", "L5 IT", "L6 IT", "L5 ET", "L5/6 NP", "L6b", "L6 CT")
cholinergic.markers = c("Chrm1", "Chrm2", "Chrm3", "Chrm4", "Chrm5", 
                        "Chrna1", "Chrna2", "Chrna3", "Chrna4", "Chrna5", "Chrna6", "Chrna7", "Chrna10", 
                        "Chrnb1", "Chrnb2", "Chrnb3", "Chrnb4", 
                        "Chrnd", "Chrne")
DoHeatmap(object = obj.opossum.glutamatergic, cholinergic.markers, slot = "data") + scale_fill_gradientn(colors = c("white", "red")) + theme(text = element_text(size = 10))
expr <- AverageExpression(obj.opossum.glutamatergic, assays = "RNA", return.seurat = TRUE, features = cholinergic.markers)
DoHeatmap(expr, features = cholinergic.markers, slot = "data", draw.lines = FALSE, size = 3) + scale_fill_gradientn(colors = magma(100), limits = c(0, 3)) + theme(text = element_text(size = 10))

```


```{r}

SaveH5Seurat(obj.opossum.glutamatergic, "E:/Opossum_M1/seurat/opossum_m1_glutamatergic.h5seurat", overwrite = TRUE, verbose = TRUE)

```

