---
title: "Opossum M1 GABAergic SST"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
obj.opossum.gabaergic <- LoadH5Seurat("E:/Opossum_M1/seurat/opossum_m1_gabaergic.h5Seurat")

```


```{r}

FeaturePlot(obj.opossum.gabaergic, reduction = "umap", features = c("Sst")) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.opossum.gabaergic, reduction = "umap", features = c("Pvalb")) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

DimPlot(obj.opossum.gabaergic, reduction = "umap", group.by="RNA_snn_res.0.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.opossum.gabaergic, reduction = "umap", group.by="RNA_snn_res.1", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.opossum.gabaergic, reduction = "umap", group.by="RNA_snn_res.1.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.opossum.gabaergic, reduction = "umap", group.by="RNA_snn_res.2", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.opossum.gabaergic, reduction = "umap", group.by="RNA_snn_res.2.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.opossum.gabaergic, reduction = "umap", group.by="RNA_snn_res.3", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

# SST resolution = 0.5
obj.opossum.gabaergic.sst <- subset(obj.opossum.gabaergic, subset = RNA_snn_res.0.5 == c("2", "8", "9", "12"))
Idents(obj.opossum.gabaergic.sst) <- "RNA_snn_res.0.5"
sst.markers <- FindAllMarkers(obj.opossum.gabaergic.sst, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 10, order_by = avg_log2FC)
DimPlot(obj.opossum.gabaergic, reduction = "umap", group.by="RNA_snn_res.0.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DoHeatmap(object = obj.opossum.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 8))
expr <- AverageExpression(obj.opossum.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 8))
ggplot(subset(sst.markers), aes(x = avg_log2FC, fill = cluster)) + stat_ecdf(geom = "step", aes(col = cluster))

```


```{r}

# SST resolution = 1
obj.opossum.gabaergic.sst <- subset(obj.opossum.gabaergic, subset = RNA_snn_res.1 == c("4", "6", "9", "13", "17"))
Idents(obj.opossum.gabaergic.sst) <- "RNA_snn_res.1"
sst.markers <- FindAllMarkers(obj.opossum.gabaergic.sst, only.pos = TRUE, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 10, order_by = avg_log2FC)
DimPlot(obj.opossum.gabaergic, reduction = "umap", group.by="RNA_snn_res.1", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DoHeatmap(object = obj.opossum.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 7))
expr <- AverageExpression(obj.opossum.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 7))
ggplot(subset(sst.markers), aes(x = avg_log2FC, fill = cluster)) + stat_ecdf(geom = "step", aes(col = cluster))

```


```{r}

# SST resolution = 1.5
obj.opossum.gabaergic.sst <- subset(obj.opossum.gabaergic, subset = RNA_snn_res.1.5 == c("4", "7", "13", "14", "17", "19", "21"))
Idents(obj.opossum.gabaergic.sst) <- "RNA_snn_res.1.5"
sst.markers <- FindAllMarkers(obj.opossum.gabaergic.sst, only.pos = TRUE, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 10, order_by = avg_log2FC)
DimPlot(obj.opossum.gabaergic, reduction = "umap", group.by="RNA_snn_res.1.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DoHeatmap(object = obj.opossum.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 6))
expr <- AverageExpression(obj.opossum.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 6))
ggplot(subset(sst.markers), aes(x = avg_log2FC, fill = cluster)) + stat_ecdf(geom = "step", aes(col = cluster))

```


```{r}

# SST resolution = 2
obj.opossum.gabaergic.sst <- subset(obj.opossum.gabaergic, subset = RNA_snn_res.2 == c("1", "2", "13", "14", "21", "22", "25"))
Idents(obj.opossum.gabaergic.sst) <- "RNA_snn_res.2"
sst.markers <- FindAllMarkers(obj.opossum.gabaergic.sst, only.pos = TRUE, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 10, order_by = avg_log2FC)
DimPlot(obj.opossum.gabaergic, reduction = "umap", group.by="RNA_snn_res.2", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DoHeatmap(object = obj.opossum.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 5))
expr <- AverageExpression(obj.opossum.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 5))
ggplot(subset(sst.markers), aes(x = avg_log2FC, fill = cluster)) + stat_ecdf(geom = "step", aes(col = cluster))

```


```{r}

# SST resolution = 2.5
obj.opossum.gabaergic.sst <- subset(obj.opossum.gabaergic, subset = RNA_snn_res.2.5 == c("1", "10", "11", "14", "15", "22", "24", "28"))
Idents(obj.opossum.gabaergic.sst) <- "RNA_snn_res.2.5"
sst.markers <- FindAllMarkers(obj.opossum.gabaergic.sst, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 10, order_by = avg_log2FC)
DimPlot(obj.opossum.gabaergic, reduction = "umap", group.by="RNA_snn_res.2.5", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DoHeatmap(object = obj.opossum.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 4))
expr <- AverageExpression(obj.opossum.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 4))
ggplot(subset(sst.markers), aes(x = avg_log2FC, fill = cluster)) + stat_ecdf(geom = "step", aes(col = cluster))

```


```{r}

# SST resolution = 3
obj.opossum.gabaergic.sst <- subset(obj.opossum.gabaergic, subset = RNA_snn_res.3 == c("4", "8", "9", "12", "13", "24", "26", "28", "32"))
Idents(obj.opossum.gabaergic.sst) <- "RNA_snn_res.3"
sst.markers <- FindAllMarkers(obj.opossum.gabaergic.sst, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, test.use = "roc")
sst.markers.top <- sst.markers %>%
                       group_by(cluster) %>%
                       slice_max(n = 10, order_by = avg_log2FC)
DimPlot(obj.opossum.gabaergic, reduction = "umap", group.by="RNA_snn_res.3", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DoHeatmap(object = obj.opossum.gabaergic.sst, sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 4))
expr <- AverageExpression(obj.opossum.gabaergic.sst, assays = "RNA", return.seurat = TRUE, features = sst.markers.top$gene)
DoHeatmap(expr, features = sst.markers.top$gene) + scale_fill_gradientn(colors = c("blue", "white", "red")) + theme(text = element_text(size = 4))
ggplot(subset(sst.markers), aes(x = avg_log2FC, fill = cluster)) + stat_ecdf(geom = "step", aes(col = cluster))

```

