---
title: "R Notebook"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
obj.opossum.glutamatergic <- LoadH5Seurat("E:/Opossum_M1/seurat/opossum_m1_glutamatergic_filt.h5Seurat")
obj.opossum.gabaergic <- LoadH5Seurat("E:/Opossum_M1/seurat/opossum_m1_gabaergic_filt.h5Seurat")
obj.opossum.nonneuronal <- LoadH5Seurat("E:/Opossum_M1/seurat/opossum_m1_nonneuronal_filt.h5Seurat")
obj.opossum <- merge(obj.opossum.glutamatergic, y = c(obj.opossum.gabaergic, obj.opossum.nonneuronal))

```


```{r}

obj.opossum <- FindVariableFeatures(obj.opossum, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(obj.opossum)
obj.opossum <- ScaleData(obj.opossum, features = all.genes)
obj.opossum <- RunPCA(obj.opossum, features = VariableFeatures(object = obj.opossum))
ElbowPlot(obj.opossum, ndims = 50)

```


```{r}

obj.opossum <- FindNeighbors(obj.opossum, dims = 1:30)
obj.opossum <- FindClusters(obj.opossum, resolution = 1, algorithm = 4, method = "igraph")
obj.opossum <- RunUMAP(obj.opossum, dims = 1:30, method="umap-learn")

```


```{r}

glutamatergic.palette <- colorRampPalette(c("#ffffdd", "#468fba"))(8)[c(2, 3, 4, 5, 6, 7)] # 2:8
gabaergic.palette <- colorRampPalette(c("#ffffdd", "#ba1851"))(7)[c(2, 4, 5, 6)] # 2:7
nonneuronal.palette <- colorRampPalette(c("#ffffdd", "#6e6e6e"))(10)[c(4, 5, 6, 7, 8, 10)] # 4:10

```


```{r}

Idents(obj.opossum) <- "subclass"
levels(obj.opossum) <- c("L2/3 IT", "L6 CT", "L5 ET", "L5 IT", "L6b", "L5/6 NP", 
                       "Pvalb", "Sst", "Lamp5", "Vip", 
                       "OPC", "Endo", "Oligo", "Astro", "Micro-PVM", "VLMC")

dim_plot <- DimPlot(obj.opossum, reduction = "umap", label = TRUE, raster = FALSE, label.size = 3, cols = c(glutamatergic.palette, gabaergic.palette, nonneuronal.palette)) + NoLegend() + xlim(-12, 17) + ylim(-14, 15) + coord_equal()

ggsave("G:/Shared drives/Opossum transcriptomics/figures/Opossum_UMAP_All.png", dim_plot, width=4, height=4, dpi=500)
ggsave("G:/Shared drives/Opossum transcriptomics/figures/Opossum_UMAP_All.svg", dim_plot, width=4, height=4, dpi=500)

```

