---
title: "Mouse Opossum Shared Genes"
output: html_notebook
---


```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)

obj.mouse.temp <- LoadH5Seurat("E:/Mouse_M1/seurat/mouse_m1_gabaergic.h5seurat")
obj.opossum.temp <- LoadH5Seurat("E:/Opossum_M1/seurat/opossum_m1_gabaergic.h5seurat")

```


```{r, fig.height=2, fig.width=3}

library(ggVennDiagram)

genes = list(M = rownames(obj.mouse.gabaergic), O = rownames(obj.opossum.gabaergic))
data = process_data(Venn(genes), shape_id == "201f")
ggplot() +
  geom_sf(aes(fill = count), data = venn_region(data)) +
  geom_sf(aes(color = id), data = venn_setedge(data), show.legend = FALSE) +
  geom_sf_text(aes(label = name), data = venn_setlabel(data), colour = "black") +
  geom_sf_text(aes(label = count), data = venn_region(data), colour = "white") +
  scale_fill_gradient(low="#f6cb7c", high = "#babdce") +
  scale_color_manual(values = c("white","white")) +
  theme_void()

# ggsave(file="G:/Shared drives/Opossum transcriptomics/figures/Shared_Genes.png", plot=venn, width=3, height=2, dpi=500)

```
