---
title: "Treeshrew M1 Glutamatergic SCT"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
obj.treeshrew.glutamatergic <- LoadH5Seurat("E:/Tree_Shrew_M1/seurat/treeshrew_m1_glutamatergic_sct.h5seurat")

```


```{r}

obj.treeshrew.glutamatergic <- SCTransform(obj.treeshrew.glutamatergic, vst.flavor = "v2", verbose = FALSE) %>%
               RunPCA(npcs = 30, verbose = FALSE) %>%
               RunUMAP(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
               FindNeighbors(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
               FindClusters(resolution = 2, algorithm = 4, method = "igraph")

```


```{r}

DimPlot(obj.treeshrew.glutamatergic, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.treeshrew.glutamatergic, reduction = "umap", group.by = "sample", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.treeshrew.glutamatergic, "nFeature_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.treeshrew.glutamatergic, "nCount_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.treeshrew.glutamatergic, reduction = "umap", group.by = "predicted_doublets", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
VlnPlot(obj.treeshrew.glutamatergic, "nCount_RNA")

```


```{r}

library(tidyverse)

cluster.sample <- table(obj.treeshrew.glutamatergic$sample, obj.treeshrew.glutamatergic$SCT_snn_res.2) %>%
  as.data.frame.matrix() %>%
  rownames_to_column(var = "sample")
cluster.sample[-1] <- lapply(cluster.sample[-1], function(x) x/sum(x))
cluster.sample <- cluster.sample %>%
  pivot_longer(
    cols = -c("sample"),
    names_to = "cluster",
    values_to = "count"
  )
cluster.sample$cluster <- factor(cluster.sample$cluster, levels = unique(cluster.sample$cluster))
  ggplot(cluster.sample, aes(x=cluster, y=count, fill=sample)) +
    geom_bar(stat="identity") +
    scale_fill_brewer(palette = "Set3") +
    theme_minimal()

```


```{r}

obj.treeshrew.glutamatergic$subclass <- NA
Idents(obj.treeshrew.glutamatergic) <- "SCT_snn_res.2"
obj.treeshrew.glutamatergic <- subset(obj.treeshrew.glutamatergic, idents = c("1", "2", "4", "5", "11", "13", "16", "19", "23"), invert = TRUE)

```


```{r}

obj.treeshrew.glutamatergic <- SCTransform(obj.treeshrew.glutamatergic, vst.flavor = "v2", verbose = FALSE) %>%
               RunPCA(npcs = 30, verbose = FALSE) %>%
               RunUMAP(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
               FindNeighbors(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
               FindClusters(resolution = 1, algorithm = 4, method = "igraph")

```


```{r}

DimPlot(obj.treeshrew.glutamatergic, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.treeshrew.glutamatergic, reduction = "umap", group.by = "SCT_snn_res.2", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.treeshrew.glutamatergic, reduction = "umap", group.by = "sample", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.treeshrew.glutamatergic, "nFeature_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.treeshrew.glutamatergic, "nCount_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.treeshrew.glutamatergic, reduction = "umap", group.by = "predicted_doublets", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
VlnPlot(obj.treeshrew.glutamatergic, "nCount_RNA")
FeaturePlot(obj.treeshrew.glutamatergic, "Plec", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

library(tidyverse)

cluster.sample <- table(obj.treeshrew.glutamatergic$sample, obj.treeshrew.glutamatergic$SCT_snn_res.1) %>%
  as.data.frame.matrix() %>%
  rownames_to_column(var = "sample")
cluster.sample[-1] <- lapply(cluster.sample[-1], function(x) x/sum(x))
cluster.sample <- cluster.sample %>%
  pivot_longer(
    cols = -c("sample"),
    names_to = "cluster",
    values_to = "count"
  )
cluster.sample$cluster <- factor(cluster.sample$cluster, levels = unique(cluster.sample$cluster))
  ggplot(cluster.sample, aes(x=cluster, y=count, fill=sample)) +
    geom_bar(stat="identity") +
    scale_fill_brewer(palette = "Set3") +
    theme_minimal()

```


```{r}

DimPlot(obj.treeshrew.glutamatergic, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.treeshrew.glutamatergic, reduction = "umap", features = c("Sst"), min.cutoff = 0) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.treeshrew.glutamatergic, reduction = "umap", features = c("Pvalb"), min.cutoff = 0) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.treeshrew.glutamatergic, reduction = "umap", features = c("Vip"), min.cutoff = 0) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.treeshrew.glutamatergic, reduction = "umap", features = c("Lamp5"), min.cutoff = 0) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.treeshrew.glutamatergic, reduction = "umap", features = c("Sncg"), min.cutoff = 0) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.treeshrew.glutamatergic, reduction = "umap", features = c("Meis2"), min.cutoff = 0) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.treeshrew.glutamatergic, reduction = "umap", features = c("Chodl"), min.cutoff = 0) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.treeshrew.glutamatergic, reduction = "umap", features = c("Lhx6"), min.cutoff = 0) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

Idents(obj.treeshrew.glutamatergic) <- "SCT_snn_res.1"

cells.pv <- WhichCells(obj.treeshrew.glutamatergic, ident = c("2", "6", "7", "8", "11", "12"))
obj.treeshrew.glutamatergic$subclass <- ifelse(colnames(obj.treeshrew.glutamatergic) %in% cells.pv, "Pvalb", "ambiguous")

cells.sst <- WhichCells(obj.treeshrew.glutamatergic, ident = c("1", "3", "9", "13", "16"))
obj.treeshrew.glutamatergic$subclass[cells.sst] <- "Sst"

cells.vip <- WhichCells(obj.treeshrew.glutamatergic, ident = c("5", "10", "14"))
obj.treeshrew.glutamatergic$subclass[cells.vip] <- "Vip"

cells.lamp5 <- WhichCells(obj.treeshrew.glutamatergic, ident = c("4", "17"))
obj.treeshrew.glutamatergic$subclass[cells.lamp5] <- "Lamp5"

cells.meis2 <- WhichCells(obj.treeshrew.glutamatergic, ident = c("15"))
obj.treeshrew.glutamatergic$subclass[cells.meis2] <- "Meis2"

Idents(obj.treeshrew.glutamatergic) <- "subclass"
obj.treeshrew.glutamatergic <- subset(obj.treeshrew.glutamatergic, subset = subclass != "ambiguous")

```


```{r}

DimPlot(obj.treeshrew.glutamatergic, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

SaveH5Seurat(obj.treeshrew.glutamatergic, "E:/treeshrew_M1/seurat/treeshrew_m1_glutamatergic_sct.h5seurat", overwrite = TRUE, verbose = TRUE)

```

