---
title: "Integrate GABAergic Mouse Opossum"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(cowplot)
library(dplyr)
library(SeuratDisk)
library(lisi)


obj.opossum <- LoadH5Seurat("E:/Transcriptomics_M1/Opossum/seurat/opossum_m1_gabaergic.h5seurat")
obj.opossum$species <- "Opossum"

obj.mouse <- LoadH5Seurat("E:/Transcriptomics_M1/Mouse/seurat/mouse_m1_gabaergic.h5seurat")
obj.mouse$species <- "Mouse"
obj.mouse$subclass[obj.mouse$subclass == "Sst Chodl"] <- "Sst"
obj.mouse <- subset(obj.mouse, subset = subclass != "Meis2")

obj.human <- LoadH5Seurat("E:/Transcriptomics_M1/Human/seurat/human_m1_gabaergic.h5seurat")

# obj.mouse <- obj.mouse[, sample(colnames(obj.mouse), size = ncol(obj.opossum), replace = FALSE)]

```


```{r}

common.features <- intersect(rownames(obj.mouse), rownames(obj.opossum))
obj.combined <- merge(obj.mouse[common.features,], y = obj.opossum[common.features,])
obj.combined[["RNA"]] <- split(obj.combined[["RNA"]], f = obj.combined$species)

```

```{r}

obj.combined <- NormalizeData(obj.combined)
obj.combined <- FindVariableFeatures(obj.combined)
obj.combined <- ScaleData(obj.combined)
obj.combined <- RunPCA(obj.combined)

obj.combined <- FindNeighbors(obj.combined, dims = 1:30, reduction = "pca")
obj.combined <- FindClusters(obj.combined, resolution = 2, cluster.name = "unintegrated_clusters")

obj.combined <- RunUMAP(obj.combined, dims = 1:30, reduction = "pca", reduction.name = "umap.unintegrated")

```



```{r}

# obj.combined <- SCTransform(obj.combined, vst.flavor = "v2", verbose = FALSE) %>%
#                        RunPCA(npcs = 30, verbose = FALSE) %>%
#                        RunUMAP(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
#                        FindNeighbors(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
#                        FindClusters(resolution = 1, algorithm = 4, method = "igraph", cluster.name = "clusters.unintegrated")
# obj.combined[["SCT"]] <- split(obj.combined[["SCT"]], f = obj.combined$species)

```

```{r}

DimPlot(obj.combined, label = FALSE, split.by = "species", group.by = "sample") + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.combined, label = TRUE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.combined, label = TRUE, split.by = "species", group.by = "subclass") + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
# DimPlot(obj.list[["Mouse"]], label = TRUE, group.by = "type") + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```



```{r}

obj.combined <- IntegrateLayers(object = obj.combined, method = CCAIntegration, orig.reduction = "pca", new.reduction = "integrated.cca",
  verbose = FALSE
)

```


```{r}

obj.combined <- FindNeighbors(obj.combined, reduction = "integrated.cca", dims = 1:30)
obj.combined <- FindClusters(obj.combined, resolution = 2, cluster.name = "cca_clusters")

obj.combined <- RunUMAP(obj.combined, reduction = "integrated.cca", dims = 1:30, reduction.name = "umap.cca")

```


```{r}

DimPlot(obj.combined, reduction = "umap.cca", group.by = "species", raster = FALSE, shuffle = TRUE, cols = c("#909090", "#c692b8")) + xlim(-16, 14) + ylim(-14, 16) + coord_equal()
DimPlot(obj.combined, reduction = "umap.cca", group.by = "subclass", split.by = "species", label = FALSE, raster = FALSE, order = rev(c("Pvalb", "Sst", "Vip", "Lamp5", "Sncg")), cols = c("#589B43", "#9B53A0",  "#29589A", "#EF3C46", "#EfAE70")) + NoLegend() + xlim(-16, 14) + ylim(-14, 16) + coord_equal()

# ggsave(file="G:/Shared drives/Grants/2024 Gorzek NRSA/_FIGURES/Figure 2/UMAP_Mixed.svg", plot=mixed_plot, dpi=500)
# ggsave(file="G:/Shared drives/Grants/2024 Gorzek NRSA/_FIGURES/Figure 2/UMAP_Split.svg", plot=split_plot, dpi=500)

```

