---
title: "Integrate GABAergic Mouse Opossum"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(cowplot)
library(dplyr)
library(SeuratDisk)
library(lisi)

obj.mouse <- LoadH5Seurat("E:/Mouse_M1/seurat/mouse_m1_gabaergic.h5seurat")
obj.mouse$species <- "Mouse"
obj.mouse$subclass[obj.mouse$subclass == "Sst Chodl"] <- "Sst"
obj.mouse <- subset(obj.mouse, subset = subclass != "Meis2")

obj.opossum <- LoadH5Seurat("E:/Opossum_M1/seurat/opossum_m1_gabaergic.h5seurat")
obj.opossum$species <- "Opossum"

obj.mouse <- obj.mouse[, sample(colnames(obj.mouse), size = ncol(obj.opossum), replace = FALSE)]

```


```{r}

common.features <- intersect(rownames(obj.mouse), rownames(obj.opossum))
obj.combined <- merge(obj.mouse[common.features,], y = obj.opossum[common.features,])
obj.list <- SplitObject(obj.combined, split.by = "species")

```


```{r}

obj.list[["Mouse"]] <- SCTransform(obj.list[["Mouse"]], vst.flavor = "v2", verbose = FALSE) %>%
               RunPCA(npcs = 30, verbose = FALSE) %>%
               RunUMAP(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
               FindNeighbors(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
               FindClusters(resolution = 1, algorithm = 4, method = "igraph")

DimPlot(obj.list[["Mouse"]], label = TRUE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.list[["Mouse"]], label = TRUE, group.by = "subclass") + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
# DimPlot(obj.list[["Mouse"]], label = TRUE, group.by = "type") + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

obj.list[["Opossum"]] <- SCTransform(obj.list[["Opossum"]], vst.flavor = "v2", verbose = FALSE) %>%
               RunPCA(npcs = 30, verbose = FALSE) %>%
               RunUMAP(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
               FindNeighbors(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
               FindClusters(resolution = 1, algorithm = 4, method = "igraph")

DimPlot(obj.list[["Opossum"]], label = TRUE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.list[["Opossum"]], label = TRUE, group.by = "subclass") + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
# DimPlot(obj.list[["Opossum"]], label = TRUE, group.by = "type") + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

features <- SelectIntegrationFeatures(object.list = obj.list, nfeatures = 5000)
obj.list <- PrepSCTIntegration(object.list = obj.list, anchor.features = features)
anchors <- FindIntegrationAnchors(object.list = obj.list, normalization.method = "SCT", anchor.features = features)
obj.combined.sct <- IntegrateData(anchorset = anchors, normalization.method = "SCT", features.to.integrate = common.features)

```


```{r}

obj.combined.sct <- RunPCA(obj.combined.sct, verbose = FALSE)
obj.combined.sct <- RunUMAP(obj.combined.sct, reduction = "pca", dims = 1:30, verbose = FALSE)
obj.combined.sct <- FindNeighbors(obj.combined.sct, reduction = "pca", dims = 1:30)
obj.combined.sct <- FindClusters(obj.combined.sct, resolution = 1, algorithm = 4, method = "igraph")

```

```{r}



```


```{r}

DimPlot(obj.combined.sct, reduction = "umap", group.by = "species", raster = FALSE, shuffle = TRUE, cols = c("#909090", "#c692b8")) + xlim(-16, 14) + ylim(-14, 16) + coord_equal()
DimPlot(obj.combined.sct, reduction = "umap", group.by = "subclass", split.by = "species", label = FALSE, raster = FALSE, order = rev(c("Pvalb", "Sst", "Vip", "Lamp5", "Sncg")), cols = c("#589B43", "#9B53A0",  "#29589A", "#EF3C46", "#EfAE70")) + NoLegend() + xlim(-16, 14) + ylim(-14, 16) + coord_equal()

# ggsave(file="G:/Shared drives/Grants/2024 Gorzek NRSA/_FIGURES/Figure 2/UMAP_Mixed.svg", plot=mixed_plot, dpi=500)
# ggsave(file="G:/Shared drives/Grants/2024 Gorzek NRSA/_FIGURES/Figure 2/UMAP_Split.svg", plot=split_plot, dpi=500)

```

