---
title: "R Notebook"
output: html_notebook
---

```{r}

library(tidyverse)
library(dplyr)

mouse.counts <- read.csv("G:/Shared drives/Opossum transcriptomics/figures/Mouse_Subclass_Sample_v1.csv")
rownames(mouse.counts) <- mouse.counts$X
mouse.counts <- mouse.counts[, -1]
mouse.counts$species <- "Mouse"
mouse.counts$GABAergic <- rowSums(mouse.counts[, c("Pvalb", "Sst", "Vip", "Lamp5", "Frem1", "Stac")])

opossum.counts <- read.csv("G:/Shared drives/Opossum transcriptomics/figures/Opossum_Subclass_Sample_V1.csv")
rownames(opossum.counts) <- opossum.counts$X
opossum.counts <- opossum.counts[, -1]
opossum.counts$species <- "Opossum"
opossum.counts$GABAergic <- rowSums(opossum.counts[, c("Pvalb", "Sst", "Vip", "Lamp5", "Frem1", "Stac")])

both.counts <- rbind(mouse.counts, opossum.counts)
both.counts$sample <- rownames(both.counts)

```


```{r}

both.counts <- both.counts %>%
  mutate(Pvalb = Pvalb / GABAergic,
         Sst = Sst / GABAergic,
         Vip = Vip / GABAergic,
         Lamp5 = Lamp5 / GABAergic,
         Frem1 = Frem1 / GABAergic,
         Stac = Stac / GABAergic
         )

scatter.counts <- both.counts

both.counts <- both.counts %>%
  pivot_longer(
    cols = c("Pvalb", "Sst", "Vip", "Lamp5", "Frem1", "Stac"),
    names_to = "cell.identity", 
    values_to = "fraction"
  )

```


```{r}

Opossum <- c(341.827681, 405.761658, 420.756541, 367.624986, NA)
Mouse <- c(312.525333, 298.613220, 277.710731, 313.741436, 284.142407)

df <- data.frame(Opossum, Mouse)
df <- df %>%
  pivot_longer(cols = c("Opossum", "Mouse"), names_to = "species", values_to = "density")
df

```

```{r, fig.height=3, fig.width=2.15}

df$species <- factor(df$species, levels = c("Opossum", "Mouse"))

# class.counts <- df[df$species %in% c("L2.3.IT"), ]

hmo_class <- ggplot(df, aes(x = factor(species, level = c("density")), y = density, fill = species)) +
    geom_bar(stat = "summary", fun = "median", position = position_dodge(width = 0.8), width = 0.75) +
    geom_point(colour = "black", position = position_dodge(width = 0.8), size = 1) +
    scale_x_discrete(labels = c("")) +
    scale_y_continuous(breaks = c(0, 100, 200, 300, 400, 500), expand = c(0, 0), limits = c(0, 500)) +
    guides(fill = guide_legend(override.aes = list(shape = NA))) +
    theme_classic() + theme(axis.text = element_text(color = "black"), legend.text = element_text(size = 10)) + 
    labs(x = NULL, y = NULL, fill = NULL) + 
    scale_fill_manual("legend", values = c("Opossum" = "#c692b8", "Mouse" = "#aaaaaa"))

ggsave(file="G:/Shared drives/Opossum transcriptomics/figures/PV_Cell_Density.svg", plot=hmo_class, width=2.15, height=3, dpi=500)
ggsave(file="G:/Shared drives/Opossum transcriptomics/figures/PV_Cell_Density.png", plot=hmo_class, width=2.15, height=3, dpi=500)

```

```{r}

res.aov <- aov(density ~ species, data = df)
tukey <- TukeyHSD(res.aov, which = "species")

```


```{r, fig.height=3, fig.width=4.5}

both.counts$species <- factor(both.counts$species, levels = c("Opossum", "Mouse", "Human"))

class.counts <- both.counts[both.counts$cell.identity %in% c("Pvalb", "Sst", "Vip", "Lamp5", "Frem1", "Stac"), ]

ggplot(class.counts, aes(x = factor(cell.identity, level = c("Pvalb", "Sst", "Vip", "Lamp5", "Frem1", "Stac")), y = fraction, fill = species)) +
    geom_bar(stat = "summary", fun = "median", position = position_dodge(width = 0.8), width = 0.75) +
    geom_point(colour = "black", position = position_dodge(width = 0.8), size = 1) +
    scale_x_discrete(labels = c("Pvalb", "Sst", "Vip", "Lamp5", "Frem1", "Stac")) +
    scale_y_continuous(breaks = c(0, 0.25, 0.5, 0.75), expand = c(0, 0), limits = c(0, 0.751)) +
    guides(fill = guide_legend(override.aes = list(shape = NA))) +
    theme_classic() + theme(axis.text = element_text(color = "black"), legend.text = element_text(size = 10)) + 
    labs(x = NULL, y = "Fraction of GABAergic Cells", fill = NULL) + 
    scale_fill_manual("legend", values = c("Opossum" = "#c692b8", "Mouse" = "#aaaaaa", "Human" = "#f1c296"))

# ggsave(file="G:/Shared drives/Opossum transcriptomics/figures/HMO_GABAergic_Subclass_Proportion.svg", plot=hmo_gabaergic, width=4.5, height=3, dpi=500)
# ggsave(file="G:/Shared drives/Opossum transcriptomics/figures/HMO_GABAergic_Subclass_Proportion.png", plot=hmo_gabaergic, width=4.5, height=3, dpi=500)

```


```{r}

res.aov2 <- aov(fraction ~ species * cell.identity, data = class.counts)
tukey <- TukeyHSD(res.aov2, which = "species:cell.identity")

```

