---
title: "Opossum M1 Object"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
library(data.table)

data_path <- "E:/Opossum_V1/output/"

sample_IDs <- c('MD23.36.002', 'MD23.36.003', 'MD23.36.004', 'MD23.36.005',
                'MD23.36.006')

objs <- c()

for (sample in sample_IDs) {
  
  temp.obj.path <- paste(data_path, sample, "/", sep = "")
  temp.obj.data <- Read10X(temp.obj.path, gene.column = 1)
  temp.obj <- CreateSeuratObject(counts = temp.obj.data, project = "Opossum_V1")
  temp.obj$sample <- sample
  temp.obj <- scrublet_R(seurat_obj = temp.obj)
  objs <- append(objs, temp.obj)
  
}

```


```{r}

obj.opossum <- merge(objs[[1]], y = objs[2:5], add.cell.ids = sample_IDs, project = "Opossum_V1")

```


```{r}

ncbi.mapping <- read.csv("E:/_genomes/Opossum_Ensembl_NCBI.txt")
ncbi.mapping.id <- paste0("LOC", as.list(ncbi.mapping$NCBI.gene..formerly.Entrezgene..ID))
genes.mapping.opossum <- as.list(ncbi.mapping$Gene.name)
ids.mapping.opossum <- as.list(ncbi.mapping$Gene.stable.ID)
genes.opossum = rownames(obj.opossum)
for (gene in ncbi.mapping.id) {
  
    idx.ncbi <- which(ncbi.mapping.id %in% gene)

    if (length(idx.ncbi) == 1) {
      
      gene.opossum <- genes.mapping.opossum[idx.ncbi]
      id.opossum <- ids.mapping.opossum[idx.ncbi]
      
      if (gene.opossum == "") {
        
        idx.opossum <- which(genes.opossum %in% id.opossum)
        genes.opossum[idx.opossum] <- gene
        
      } else {
        
        idx.opossum <- which(genes.opossum %in% gene.opossum)
        genes.opossum[idx.opossum] <- gene
        
      }
      
    }
  
}

genes.mapping <- read.csv("E:/_genomes/Opossum_Mouse_Genes.txt")
genes.mapping.mouse <- as.list(genes.mapping$Mouse.gene.name)
genes.mapping.opossum <- as.list(genes.mapping$Gene.name)
ids.mapping.opossum <- as.list(genes.mapping$Gene.stable.ID)
genes.opossum = rownames(obj.opossum)
for (gene in genes.mapping.mouse) {
  
    idx.mouse <- which(genes.mapping.mouse %in% gene)

    if (length(idx.mouse) == 1) {
      
      gene.opossum <- genes.mapping.opossum[idx.mouse]
      id.opossum <- ids.mapping.opossum[idx.mouse]
      
      if (gene.opossum == "") {
        
        idx.opossum <- which(genes.opossum %in% id.opossum)
        genes.opossum[idx.opossum] <- gene
        
      } else {
        
        idx.opossum <- which(genes.opossum %in% gene.opossum)
        genes.opossum[idx.opossum] <- gene
        
      }
      
    }
  
}

```


```{r}

obj.df <- as.data.frame(as.matrix(obj.opossum[["RNA"]]@counts))
rownames(obj.df) <- genes.opossum
obj.opossum.temp <- CreateSeuratObject(counts = obj.df, meta.data = obj.opossum[[]])
obj.opossum <- obj.opossum.temp

```


```{r}

VlnPlot(obj.opossum, features = c("nFeature_RNA"), group.by = "sample", raster = FALSE)
VlnPlot(obj.opossum, features = c("nCount_RNA"), group.by = "sample", raster = FALSE)
FeatureScatter(obj.opossum, feature1 = "nCount_RNA", feature2 = "nFeature_RNA", raster = FALSE)

```


```{r}

cell_mask <- Reduce(intersect,list(WhichCells(obj.opossum, expression = nFeature_RNA > 700), 
                                   WhichCells(obj.opossum, expression = nFeature_RNA < 6500),
                                   WhichCells(obj.opossum, expression = nCount_RNA < 40000)))

gene_mask <- rownames(obj.opossum)[Matrix::rowSums(obj.opossum[["RNA"]]@counts > 0) > 8]

obj.opossum <- subset(obj.opossum, features = gene_mask, cells = cell_mask)

```


```{r}

obj.opossum <- SplitObject(obj.opossum, split.by = "sample")

for (sample in names(obj.opossum)) {
    obj.opossum[[sample]] <- SCTransform(obj.opossum[[sample]], vst.flavor = "v2", verbose = FALSE) %>%
    RunPCA(npcs = 30, verbose = FALSE)
}

```


```{r}

features <- SelectIntegrationFeatures(object.list = obj.opossum, nfeatures = 3000)
obj.opossum <- PrepSCTIntegration(object.list = obj.opossum, anchor.features = features)
obj.opossum.anchors <- FindIntegrationAnchors(object.list = obj.opossum, normalization.method = "SCT", anchor.features = features)
obj.opossum.sct <- IntegrateData(anchorset = obj.opossum.anchors, normalization.method = "SCT")

```


```{r}

obj.opossum.sct <- RunPCA(obj.opossum.sct, verbose = FALSE)
obj.opossum.sct <- RunUMAP(obj.opossum.sct, dims = 1:30, method = "umap-learn", reduction = "pca")
obj.opossum.sct <- FindNeighbors(obj.opossum.sct, reduction = "pca", dims = 1:30)
obj.opossum.sct <- FindClusters(obj.opossum.sct, resolution = 1, algorithm = 4, method = "igraph")

```


```{r}

DimPlot(obj.opossum.sct, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.opossum.sct, reduction = "umap", group.by = "sample", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum.sct, "nFeature_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum.sct, "nCount_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.opossum.sct, reduction = "umap", group.by = "predicted_doublets", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

FeaturePlot(obj.opossum.sct, reduction = "umap", features = c("Snap25"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum.sct, reduction = "umap", features = c("Slc17a6"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum.sct, reduction = "umap", features = c("Gad2"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
# FeaturePlot(obj.opossum, reduction = "umap", features = c("Csf1R"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum.sct, reduction = "umap", features = c("Mog"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
# FeaturePlot(obj.opossum, reduction = "umap", features = c("PDGFRA"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.opossum.sct, reduction = "umap", features = c("Aldh1l1"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
# FeaturePlot(obj.opossum.sct, reduction = "umap", features = c("Col1a1"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum.sct, reduction = "umap", features = c("PVALB"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum.sct, reduction = "umap", features = c("Sst"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum.sct, reduction = "umap", features = c("Vip"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum.sct, reduction = "umap", features = c("Lamp5"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum.sct, reduction = "umap", features = c("Sncg"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

SaveH5Seurat(obj.opossum.sct, "E:/Opossum_V1/seurat/opossum_v1_all.h5seurat", overwrite = TRUE, verbose = TRUE)

```

