---
title: "Opossum M1 Raw"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
library(data.table)

data_path <- "E:/Opossum_M1/output/monDom5/"

sample_IDs <- c("NW_TX0055-4", "NW_TX0055-5", "NW_TX0055-6", "NW_TX0064-3", 
                "NW_TX0064-4", "NW_TX0064-5", "NW_TX0077-7", "NW_TX0077-8", 
                "NW_TX0078-1", "NW_TX0090-11", "NW_TX0092-8")

objs <- c()

for (sample in sample_IDs) {
  
  temp.obj.path <- paste(data_path, sample, "/outs/filtered_feature_bc_matrix/", sep = "")
  temp.obj.data <- Read10X(temp.obj.path)
  temp.obj <- CreateSeuratObject(counts = temp.obj.data, project = "Opossum_M1")
  temp.obj$sample <- sample
  temp.obj <- scrublet_R(seurat_obj = temp.obj)
  objs <- append(objs, temp.obj)
  
}

```


```{r}

obj.opossum <- merge(objs[[1]], y = objs[2:11], add.cell.ids = sample_IDs, project = "Opossum_M1")

```


```{r}

VlnPlot(obj.opossum, features = c("nFeature_RNA"), group.by = "sample", raster = FALSE)
VlnPlot(obj.opossum, features = c("nCount_RNA"), group.by = "sample", raster = FALSE)
FeatureScatter(obj.opossum, feature1 = "nCount_RNA", feature2 = "nFeature_RNA", raster = FALSE)

```


```{r}

genes.mapping <- read.csv("E:/_genomes/Opossum_Mouse_Genes.txt")
genes.mapping.mouse <- as.list(genes.mapping$Mouse.gene.name)
genes.mapping.opossum <- as.list(genes.mapping$Gene.name)
ids.mapping.opossum <- as.list(genes.mapping$Gene.stable.ID)
genes.opossum = rownames(obj.opossum)
for (gene in genes.mapping.mouse) {
  
    idx.mouse <- which(genes.mapping.mouse %in% gene)

    if (length(idx.mouse) == 1) {
      
      gene.opossum <- genes.mapping.opossum[idx.mouse]
      id.opossum <- ids.mapping.opossum[idx.mouse]
      
      if (gene.opossum == "") {
        
        idx.opossum <- which(genes.opossum %in% id.opossum)
        genes.opossum[idx.opossum] <- gene
        
      } else {
        
        idx.opossum <- which(genes.opossum %in% gene.opossum)
        genes.opossum[idx.opossum] <- gene
        
      }
      
    }
  
}

```


```{r}

obj.df <- as.data.frame(as.matrix(obj.opossum[["RNA"]]@counts))
rownames(obj.df) <- genes.opossum
obj.opossum.temp <- CreateSeuratObject(counts = obj.df, meta.data = obj.opossum[[]])
obj.opossum <- obj.opossum.temp

```


```{r}

VlnPlot(obj.opossum, features = c("nFeature_RNA"), group.by = "sample", raster = FALSE)
VlnPlot(obj.opossum, features = c("nCount_RNA"), group.by = "sample", raster = FALSE)
FeatureScatter(obj.opossum, feature1 = "nCount_RNA", feature2 = "nFeature_RNA", raster = FALSE)

```


```{r}

cell_mask <- Reduce(intersect,list(WhichCells(obj.opossum, expression = nFeature_RNA > 700), 
                                   WhichCells(obj.opossum, expression = nFeature_RNA < 6500),
                                   WhichCells(obj.opossum, expression = nCount_RNA < 40000)))

gene_mask <- rownames(obj.opossum)[Matrix::rowSums(obj.opossum[["RNA"]]@counts > 0) > 8]

obj.opossum <- subset(obj.opossum, features = gene_mask, cells = cell_mask)

```


```{r}

obj.opossum <- NormalizeData(obj.opossum, normalization.method = "LogNormalize", scale.factor = 10000)
obj.opossum <- FindVariableFeatures(obj.opossum, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(obj.opossum)
obj.opossum <- ScaleData(obj.opossum, features = all.genes)
obj.opossum <- RunPCA(obj.opossum, features = VariableFeatures(object = obj.opossum))
ElbowPlot(obj.opossum, ndims = 50)

```


```{r}

obj.opossum <- FindNeighbors(obj.opossum, dims = 1:30)
obj.opossum <- FindClusters(obj.opossum, resolution = 1, algorithm = 4, method = "igraph")
obj.opossum <- RunUMAP(obj.opossum, dims = 1:30, method="umap-learn")

```


```{r}

DimPlot(obj.opossum, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.opossum, reduction = "umap", group.by = "sample", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.opossum, "nFeature_RNA", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.opossum, "nCount_RNA", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.opossum, reduction = "umap", group.by = "predicted_doublets", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

#glutamatergic 
FeaturePlot(obj.opossum, reduction = "umap", features = c("Snap25"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Slc17a6"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Aldh1l1"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Col1a1"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

#GABAergic 
FeaturePlot(obj.opossum, reduction = "umap", features = c("Gad2"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("PVALB"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Sst"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Vip"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Lamp5"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Sncg"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

#non-neuronal
FeaturePlot(obj.opossum, reduction = "umap", features = c("Csf1r"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal() # microglia
FeaturePlot(obj.opossum, reduction = "umap", features = c("Mog"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal() # oligodendrocytes
#FeaturePlot(obj.opossum, reduction = "umap", features = c("PDGFRA"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Aqp4"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal() # astrocytes
FeaturePlot(obj.opossum, reduction = "umap", features = c("Col1a1"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal() # VLMC
FeaturePlot(obj.opossum, reduction = "umap", features = c("Tek"), raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal() # endothelial

```


```{r}

cells.glutamatergic <- WhichCells(obj.opossum, ident = c(1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 23, 25))
obj.opossum$class <- ifelse(colnames(obj.opossum) %in% cells.glutamatergic, "glutamatergic", "ambiguous")

cells.gabaergic <- WhichCells(obj.opossum, ident = c(7, 13, 19, 20, 27, 29, 30))
obj.opossum$class[cells.gabaergic] <- "gabaergic"

cells.nonneuronal <- WhichCells(obj.opossum, ident = c(6, 21, 22, 24, 26, 28, 31))
obj.opossum$class[cells.nonneuronal] <- "nonneuronal"

```


```{r}

DimPlot(obj.opossum, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-19, 19) + ylim(-19, 19) + coord_equal()
DimPlot(obj.opossum, reduction = "umap", group.by = "class", raster = FALSE) + xlim(-19, 19) + ylim(-19, 19) + coord_equal()

```



```{r}

obj.opossum.glutamatergic <- subset(obj.opossum, subset = class == "glutamatergic")
obj.opossum.gabaergic <- subset(obj.opossum, subset = class == "gabaergic")
obj.opossum.nonneuronal <- subset(obj.opossum, subset = class == "nonneuronal")

```


```{r}

obj.opossum.glutamatergic <- NormalizeData(obj.opossum.glutamatergic, normalization.method = "LogNormalize", scale.factor = 10000)
obj.opossum.glutamatergic <- FindVariableFeatures(obj.opossum.glutamatergic, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(obj.opossum.glutamatergic)
obj.opossum.glutamatergic <- ScaleData(obj.opossum.glutamatergic, features = all.genes)
obj.opossum.glutamatergic <- RunPCA(obj.opossum, features = VariableFeatures(object = obj.opossum.glutamatergic))

obj.opossum.glutamatergic <- FindNeighbors(obj.opossum.glutamatergic, dims = 1:30)
obj.opossum.glutamatergic <- FindClusters(obj.opossum.glutamatergic, resolution = 1, algorithm = 4, method = "igraph")
obj.opossum.glutamatergic <- RunUMAP(obj.opossum.glutamatergic, dims = 1:30, method="umap-learn")

```


```{r}

obj.opossum.gabaergic <- NormalizeData(obj.opossum.gabaergic, normalization.method = "LogNormalize", scale.factor = 10000)
obj.opossum.gabaergic <- FindVariableFeatures(obj.opossum.gabaergic, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(obj.opossum.gabaergic)
obj.opossum.gabaergic <- ScaleData(obj.opossum.gabaergic, features = all.genes)
obj.opossum.gabaergic <- RunPCA(obj.opossum.gabaergic, features = VariableFeatures(object = obj.opossum.gabaergic))

obj.opossum.gabaergic <- FindNeighbors(obj.opossum.gabaergic, dims = 1:30)
obj.opossum.gabaergic <- FindClusters(obj.opossum.gabaergic, resolution = 1.1, algorithm = 4, method = "igraph")
obj.opossum.gabaergic <- RunUMAP(obj.opossum.gabaergic, dims = 1:30, method="umap-learn")

```


```{r}

obj.opossum.nonneuronal <- NormalizeData(obj.opossum.nonneuronal, normalization.method = "LogNormalize", scale.factor = 10000)
obj.opossum.nonneuronal <- FindVariableFeatures(obj.opossum.nonneuronal, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(obj.opossum.nonneuronal)
obj.opossum.nonneuronal <- ScaleData(obj.opossum.nonneuronal, features = all.genes)
obj.opossum.nonneuronal <- RunPCA(obj.opossum.nonneuronal, features = VariableFeatures(object = obj.opossum.nonneuronal))

obj.opossum.nonneuronal <- FindNeighbors(obj.opossum.nonneuronal, dims = 1:30)
obj.opossum.nonneuronal <- FindClusters(obj.opossum.nonneuronal, resolution = 1, algorithm = 4, method = "igraph")
obj.opossum.nonneuronal <- RunUMAP(obj.opossum.nonneuronal, dims = 1:30, method="umap-learn")

```


```{r}

SaveH5Seurat(obj.opossum.glutamatergic, "E:/opossum_M1/seurat/opossum_m1_glutamatergic_raw.h5seurat", overwrite = TRUE, verbose = TRUE)
SaveH5Seurat(obj.opossum.gabaergic, "E:/opossum_M1/seurat/opossum_m1_gabaergic_raw.h5seurat", overwrite = TRUE, verbose = TRUE)
SaveH5Seurat(obj.opossum.nonneuronal, "E:/opossum_M1/seurat/opossum_m1_nonneuronal_raw.h5seurat", overwrite = TRUE, verbose = TRUE)

```

