---
title: "R Notebook"
output: html_notebook
---


```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
obj.opossum <- LoadH5Seurat("E:/Opossum_V1/seurat/opossum_v1_all.h5Seurat")
# obj.mouse <- LoadH5Seurat("E:/Mouse_M1/seurat/mouse_m1_all.h5Seurat")

```


```{r}

FeaturePlot(obj.opossum, reduction = "umap", features = c("Scnn1a"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse, reduction = "umap", features = c("Scnn1a"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

FeaturePlot(obj.opossum, reduction = "umap", features = c("Lhx6"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse, reduction = "umap", features = c("Lhx6"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Adarb2"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse, reduction = "umap", features = c("Adarb2"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

FeaturePlot(obj.opossum, reduction = "umap", features = c("Polr2a"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse, reduction = "umap", features = c("Polr2a"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Ppib"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse, reduction = "umap", features = c("Ppib"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Ubc"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse, reduction = "umap", features = c("Ubc"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

FeaturePlot(obj.opossum, reduction = "umap", features = c("Polr2a"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse, reduction = "umap", features = c("Polr2a"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Ppib"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse, reduction = "umap", features = c("Ppib"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Ubc"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse, reduction = "umap", features = c("Ubc"), raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


