---
title: "R Notebook"
output: html_notebook
---


```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
obj.mouse.gabaergic <- LoadH5Seurat("E:/Mouse_M1/seurat/mouse_m1_gabaergic.h5Seurat")
obj.mouse.gabaergic$species <- "Mouse"
obj.mouse.gabaergic$subclass[obj.mouse.gabaergic$subclass == "Sst Chodl"] <- "Sst"
obj.opossum.gabaergic <- LoadH5Seurat("E:/Opossum_M1/seurat/opossum_m1_gabaergic_filt.h5Seurat")
obj.opossum.gabaergic$species <- "Opossum"

```


```{r}

common.features <- intersect(rownames(obj.mouse.gabaergic), rownames(obj.opossum.gabaergic))
obj.combined <- merge(obj.mouse.gabaergic[common.features,], y = obj.opossum.gabaergic[common.features,])

```


```{r}

markers <- FindConservedMarkers(obj.combined, ident.1 = "Vip", grouping.var = "species")

```


```{r, fig.height=3.5, fig.width=5.5}

Idents(obj.combined) <- "subclass"
levels(obj.combined) <- rev(c("Pvalb", "Sst", "Vip", "Lamp5", "Sncg", "Meis2"))
features.subclass <- c("Myo5b", "Sst", "Vip", "Lamp5", "Sncg", "Meis2")
DotPlot(obj.combined, features = features.subclass, dot.scale = 6, cols = c("#aaaaaa", "#a85d96"), col.min = -10, split.by = "species") +
       theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10), axis.text.y = element_text(size = 10))

# ggsave(file="G:/Shared drives/Opossum transcriptomics/figures/GABA_DotPlot.png", plot=dot, width=5.5, height=3.5, dpi=500)

```


```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
obj.mouse.glutamatergic <- LoadH5Seurat("E:/Mouse_M1/seurat/mouse_m1_glutamatergic.h5Seurat")
obj.mouse.glutamatergic$species <- "Mouse"
obj.mouse.glutamatergic$subclass <- obj.mouse.glutamatergic$subclass_label
obj.mouse.glutamatergic$subclass[obj.mouse.glutamatergic$subclass == "L6 IT Car3"] <- "L6 IT"
obj.opossum.glutamatergic <- LoadH5Seurat("E:/Opossum_M1/seurat/opossum_m1_glutamatergic_filt.h5Seurat")
obj.opossum.glutamatergic$species <- "Opossum"

```


```{r}

common.features <- intersect(rownames(obj.mouse.glutamatergic), rownames(obj.opossum.glutamatergic))
obj.combined <- merge(obj.mouse.glutamatergic[common.features,], y = obj.opossum.glutamatergic[common.features,])

```


```{r}

markers <- FindConservedMarkers(obj.combined, ident.1 = "L5 IT", grouping.var = "species")

```


```{r, fig.height=4, fig.width=6}

Idents(obj.combined) <- "subclass"
levels(obj.combined) <- rev(c("L2/3 IT", "L5 IT", "L5/6 NP", "L5 ET", "L6 CT", "L6b", "L6 IT"))
features.subclass <- c("Cux2", "Rorb", "Nxph1", "Lpp", "Syt6", "Atp10a", "Cdh9")
dot <- DotPlot(obj.combined, features = features.subclass, dot.scale = 6, cols = c("#aaaaaa", "#a85d96"), col.min = -10, split.by = "species") +
       theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10), axis.text.y = element_text(size = 10))

ggsave(file="G:/Shared drives/Opossum transcriptomics/figures/Glut_DotPlot.png", plot=dot, width=6, height=4, dpi=500)

```


```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
obj.mouse.nonneuronal <- LoadH5Seurat("E:/Mouse_M1/seurat/mouse_m1_nonneuronal.h5Seurat")
obj.mouse.nonneuronal$species <- "Mouse"
obj.mouse.nonneuronal$subclass <- obj.mouse.nonneuronal$subclass_label
obj.mouse.nonneuronal$subclass[obj.mouse.nonneuronal$subclass == "SMC"] <- "Peri"
obj.opossum.nonneuronal <- LoadH5Seurat("E:/Opossum_M1/seurat/opossum_m1_nonneuronal_filt.h5Seurat")
obj.opossum.nonneuronal$species <- "Opossum"

```


```{r}

common.features <- intersect(rownames(obj.mouse.nonneuronal), rownames(obj.opossum.nonneuronal))
obj.combined <- merge(obj.mouse.nonneuronal[common.features,], y = obj.opossum.nonneuronal[common.features,])

```


```{r}

markers <- FindConservedMarkers(obj.combined, ident.1 = "VLMC", grouping.var = "species")

```


```{r, fig.height=4, fig.width=6}

Idents(obj.combined) <- "subclass"
levels(obj.combined) <- rev(c("Astro", "Oligo", "OPC", "Micro-PVM", "Endo", "VLMC", "Peri"))
features.subclass <- c("Glis3", "Mog", "Pdgfra", "Csf1r", "Tek", "Bnc2", "Abcc9")
dot <- DotPlot(obj.combined, features = features.subclass, dot.scale = 6, cols = c("#aaaaaa", "#a85d96"), col.min = -10, split.by = "species") +
       theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 10), axis.text.y = element_text(size = 10))

ggsave(file="G:/Shared drives/Opossum transcriptomics/figures/Non_DotPlot.png", plot=dot, width=6, height=4, dpi=500)

```

