---
title: "R Notebook"
output: html_notebook
---

```{r}

library(Seurat)
library(SeuratDisk)
library(SeuratWrappers)
library(monocle3)
library(pheatmap)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(patchwork)
library(dplyr)
library(data.table)
library(clustree)
library(reshape2)
library(tidyr)
library(gridExtra)
library(stringr)
library(plyr)
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_integration_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/xgboost_train.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/plottingFxns.R")
colors_list <- GetColors()

obj.opossum.glutamatergic <- readRDS("E:/Transcriptomics_V1/Opossum/seurat/opossum_v1_glutamatergic_processed.rds")
obj.mouse.glutamatergic <- readRDS("E:/Transcriptomics_V1/Mouse/seurat/mouse_v1_P38_glutamatergic_processed.rds")

```


```{r}

Idents(obj.opossum.glutamatergic) <- "subclass"
obj.opossum.IT <- subset(obj.opossum.glutamatergic, idents = c("IT_A", "IT_B", "IT_C", "IT_D"))
obj.opossum.IT <- NormalizePCA(obj.opossum.IT)

Idents(obj.mouse.glutamatergic) <- "subclass"
obj.mouse.IT <- subset(obj.mouse.glutamatergic, idents = c("L2/3", "L4", "L5IT", "L6IT"))
obj.mouse.IT <- NormalizePCA(obj.mouse.IT)

```


```{r}

# Compute DE genes (Mouse)
de_genes_L2_L5 <- FindMarkers(
  object = obj.mouse.IT,
  ident.1 = "L2/3",
  ident.2 = "L5IT",
  logfc.threshold = 0.25,  # Adjust as needed
  min.pct = 0.1,  # Filter genes expressed in at least 10% of cells
  test.use = "wilcox"  # Wilcoxon test
)

# Compute DE genes (Opossum)
de_genes_A_C <- FindMarkers(
  object = obj.opossum.IT,
  ident.1 = "IT_A",
  ident.2 = "IT_C",
  logfc.threshold = 0.25,  # Adjust as needed
  min.pct = 0.1,  # Filter genes expressed in at least 10% of cells
  test.use = "wilcox"  # Wilcoxon test
)

obj.combined <- merge(obj.mouse.IT, y = obj.opossum.IT)

# Compute DE genes (L2/3)
de_genes_L2_A <- FindMarkers(
  object = obj.combined,
  ident.1 = "L2/3",
  ident.2 = "IT_A",
  logfc.threshold = 0.25,  # Adjust as needed
  min.pct = 0.1,  # Filter genes expressed in at least 10% of cells
  test.use = "wilcox"  # Wilcoxon test
)

# Compute DE genes (L5IT)
de_genes_L5_C <- FindMarkers(
  object = obj.combined,
  ident.1 = "L5IT",
  ident.2 = "IT_C",
  logfc.threshold = 0.25,  # Adjust as needed
  min.pct = 0.1,  # Filter genes expressed in at least 10% of cells
  test.use = "wilcox"  # Wilcoxon test
)

```


```{r, fig.height=6, fig.width=5}

library(EnhancedVolcano)

EnhancedVolcano(de_genes_L2_L5, lab = rownames(de_genes_L2_L5), x = 'avg_log2FC', y = 'p_val_adj')
EnhancedVolcano(de_genes_A_C, lab = rownames(de_genes_A_C), x = 'avg_log2FC', y = 'p_val_adj')
EnhancedVolcano(de_genes_L2_A, lab = rownames(de_genes_L2_A), x = 'avg_log2FC', y = 'p_val_adj')

```


```{r}

# View top DE genes
head(de_genes_L2_L5)

L2_L5_genes <- rownames(de_genes_L2_L5[de_genes_L2_L5$avg_log2FC > 1 & de_genes_L2_L5$pct.1 > 0.5 & de_genes_L2_L5$p_val_adj < 0.05, ])
L5_L2_genes <- rownames(de_genes_L2_L5[de_genes_L2_L5$avg_log2FC < -1 & de_genes_L2_L5$pct.1 > 0.5 & de_genes_L2_L5$p_val_adj < 0.05, ])
A_C_genes <- rownames(de_genes_A_C[de_genes_A_C$avg_log2FC > 1 & de_genes_A_C$pct.1 > 0.5 & de_genes_A_C$p_val_adj < 0.05, ])
C_A_genes <- rownames(de_genes_A_C[de_genes_A_C$avg_log2FC < -1 & de_genes_A_C$pct.1 > 0.5 & de_genes_A_C$p_val_adj < 0.05, ])
L2_A_genes <- rownames(de_genes_L2_A[de_genes_L2_A$avg_log2FC > 1 & de_genes_L2_A$pct.1 > 0.5 & de_genes_L2_A$p_val_adj < 0.05, ])
A_L2_genes <- rownames(de_genes_L2_A[de_genes_L2_A$avg_log2FC < -1 & de_genes_L2_A$pct.1 > 0.5 & de_genes_L2_A$p_val_adj < 0.05, ])
L5_C_genes <- rownames(de_genes_L5_C[de_genes_L5_C$avg_log2FC < 1 & de_genes_L5_C$pct.1 > 0.5 & de_genes_L5_C$p_val_adj < 0.05, ])

```


```{r}

library(rbioapi)

# Define the reference species (mouse: MGI)
species <- 10090

# Perform GO enrichment for L2/3 upregulated genes
go_L2_results <- rba_panther_enrich(up_L2_genes, organism = species, annot_dataset = "GO:0008150")

# Perform GO enrichment for L5IT upregulated genes
go_L5_results <- rba_panther_enrich(up_L5_genes, organism = species, annot_dataset = "GO:0008150")

```


```{r}

library(GOfuncR)

all_genes <- rownames(obj.mouse.IT)

L2_L5_genes_df <- data.frame(gene_id = all_genes, 
                             candidate = ifelse(all_genes %in% L2_L5_genes, 1, 0))

L5_L2_genes_df <- data.frame(gene_id = all_genes, 
                             candidate = ifelse(all_genes %in% L5_L2_genes, 1, 0))

all_genes <- rownames(obj.opossum.IT)

A_C_genes_df <- data.frame(gene_id = all_genes, 
                           candidate = ifelse(all_genes %in% A_C_genes, 1, 0))

C_A_genes_df <- data.frame(gene_id = all_genes, 
                           candidate = ifelse(all_genes %in% C_A_genes, 1, 0))

all_genes <- rownames(obj.combined)

L2_A_genes_df <- data.frame(gene_id = all_genes, 
                           candidate = ifelse(all_genes %in% L2_A_genes, 1, 0))

A_L2_genes_df <- data.frame(gene_id = all_genes, 
                           candidate = ifelse(all_genes %in% A_L2_genes, 1, 0))

C_A_genes_df <- data.frame(gene_id = all_genes, 
                           candidate = ifelse(all_genes %in% C_A_genes, 1, 0))

# Perform GO enrichment for L2/3 upregulated genes
go_L2_L5_results <- go_enrich(
  genes = as.data.frame(L2_L5_genes_df),
  organismDb = "Mus.musculus",  # Ensures correct annotation source
  silent = TRUE
)

# Perform GO enrichment for L5IT upregulated genes
go_L5_L2_results <- go_enrich(
  genes = as.data.frame(L5_L2_genes_df),
  organismDb = "Mus.musculus", 
  silent = TRUE
)

# Perform GO enrichment for IT_A upregulated genes
go_A_C_results <- go_enrich(
  genes = as.data.frame(A_C_genes_df),
  organismDb = "Mus.musculus",  # Ensures correct annotation source
  silent = TRUE
)

# Perform GO enrichment for IT_C upregulated genes
go_C_A_results <- go_enrich(
  genes = as.data.frame(C_A_genes_df),
  organismDb = "Mus.musculus", 
  silent = TRUE
)

# Perform GO enrichment for IT_A upregulated genes
go_L2_A_results <- go_enrich(
  genes = as.data.frame(L2_A_genes_df),
  organismDb = "Mus.musculus",  # Ensures correct annotation source
  silent = TRUE
)

# Perform GO enrichment for IT_A upregulated genes
go_A_L2_results <- go_enrich(
  genes = as.data.frame(A_L2_genes_df),
  organismDb = "Mus.musculus",  # Ensures correct annotation source
  silent = TRUE
)

# write.csv(go_L2_results$results, "E:/L23_L5_GO_Results_log2FC_2_pct_0-5.csv")
# write.csv(go_L5_results$results, "E:/L5_L23_GO_Results_log2FC_2_pct_0-5.csv")

```


```{r}

opossum.cats <- go_A_L2_results$results[go_A_L2_results$results$FWER_overrep < 0.05,]
mouse.cats <- go_L2_A_results$results[go_L2_A_results$results$FWER_overrep < 0.05,]

# mouse.cats[mouse.cats %in% opossum.cats == FALSE]
View(mouse.cats[mouse.cats$node_name %in% opossum.cats$node_name == FALSE,])
View(opossum.cats[opossum.cats$node_name %in% mouse.cats$node_name == FALSE,])

```


```{r}

go_L2_genes <- data.frame()
ontologies <- go_L2_L5_results$results$ontology[go_L2_L5_results$results$FWER_overrep < 0.05]
node_ids <- go_L2_L5_results$results$node_id[go_L2_L5_results$results$FWER_overrep < 0.05]
node_names <- go_L2_L5_results$results$node_name[go_L2_L5_results$results$FWER_overrep < 0.05]
for (i in 1:length(node_ids)) {
  ontology <- ontologies[i]
  id <- node_ids[i]
  name <- node_names[i]
  FWER <- go_L2_L5_results$results$FWER_overrep[i]
  genes <- get_anno_genes(id, database = "Mus.musculus")
  genes.of.interest <- genes$gene[genes$gene %in% L2_L5_genes]
  for (g in genes.of.interest) {
    go_L2_genes <- rbind(go_L2_genes, data.frame(ontology = ontology, id = id, name = name, gene = g, FWER = FWER))
  }
}

write.csv(go_L2_genes, "E:/L23_L5_GO_Genes_log2FC_1-5_pct_0-5_FWER_0-05.csv")

go_L5_genes <- data.frame()
ontologies <- go_L5_L2_results$results$ontology[go_L5_L2_results$results$FWER_overrep < 0.05]
node_ids <- go_L5_L2_results$results$node_id[go_L5_L2_results$results$FWER_overrep < 0.05]
node_names <- go_L5_L2_results$results$node_name[go_L5_L2_results$results$FWER_overrep < 0.05]
for (i in 1:length(node_ids)) {
  id <- node_ids[i]
  ontology <- ontologies[i]
  name <- node_names[i]
  FWER <- go_L5_L2_results$results$FWER_overrep[i]
  genes <- get_anno_genes(id, database = "Mus.musculus")
  genes.of.interest <- genes$gene[genes$gene %in% L5_L2_genes]
  for (g in genes.of.interest) {
    go_L5_genes <- rbind(go_L5_genes, data.frame(ontology = ontology, id = id, name = name, gene = g, FWER = FWER))
  }
}

write.csv(go_L5_genes, "E:/L5_L23_GO_Genes_log2FC_1_pct_0-5_FWER_0-05.csv")

go_L2_A_genes <- data.frame()
ontologies <- go_L2_A_results$results$ontology[go_L2_A_results$results$FWER_overrep < 0.05]
node_ids <- go_L2_A_results$results$node_id[go_L2_A_results$results$FWER_overrep < 0.05]
node_ids <- go_L2_A_results$results$node_id[go_L2_A_results$results$FWER_overrep < 0.05]
node_names <- go_L2_A_results$results$node_name[go_L2_A_results$results$FWER_overrep < 0.05]
for (i in 1:length(node_ids)) {
  ontology <- ontologies[i]
  id <- node_ids[i]
  name <- node_names[i]
  FWER <- go_L2_A_results$results$FWER_overrep[i]
  genes <- get_anno_genes(id, database = "Mus.musculus")
  genes.of.interest <- genes$gene[genes$gene %in% L2_A_genes]
  for (g in genes.of.interest) {
    go_L2_A_genes <- rbind(go_L2_A_genes, data.frame(ontology = ontology, id = id, name = name, gene = g, FWER = FWER))
  }
}

write.csv(go_L2_A_genes, "E:/L23_A_GO_Genes_log2FC_1_pct_0-5_FWER_0-05.csv")

go_A_L2_genes <- data.frame()
ontologies <- go_A_L2_results$results$ontology[go_A_L2_results$results$FWER_overrep < 0.05]
node_ids <- go_A_L2_results$results$node_id[go_A_L2_results$results$FWER_overrep < 0.05]
node_ids <- go_A_L2_results$results$node_id[go_A_L2_results$results$FWER_overrep < 0.05]
node_names <- go_A_L2_results$results$node_name[go_A_L2_results$results$FWER_overrep < 0.05]
for (i in 1:length(node_ids)) {
  ontology <- ontologies[i]
  id <- node_ids[i]
  name <- node_names[i]
  FWER <- go_A_L2_results$results$FWER_overrep[i]
  genes <- get_anno_genes(id, database = "Mus.musculus")
  genes.of.interest <- genes$gene[genes$gene %in% A_L2_genes]
  for (g in genes.of.interest) {
    go_A_L2_genes <- rbind(go_A_L2_genes, data.frame(ontology = ontology, id = id, name = name, gene = g, FWER = FWER))
  }
}

write.csv(go_A_L2_genes, "E:/A_L23_GO_Genes_log2FC_1_pct_0-5_FWER_0-05.csv")

```


```{r}

plasticity.genes <- as.character(read.csv("C:/Users/TLab/Downloads/synaptic_plasticity_genes_mouse.csv")$Mouse_Gene)
go_L2_genes_plasticity <- go_L2_genes[go_L2_genes$name %in% plasticity.genes, ]

```


```{r}

library(ggplot2)

# Function to plot top GO terms
plot_GO <- function(go_results, title) {
  go_results %>%
    arrange(fdr) %>%
    head(10) %>%
    ggplot(aes(x = reorder(term.label, fdr), y = fdr)) +
    geom_bar(stat = "identity", fill = "steelblue") +
    coord_flip() +
    theme_minimal() +
    labs(title = title, x = "GO Term", y = "Fold Enrichment")
}

# Plot GO enrichment for L2/3
plot_GO(go_L2_results$result, "GO Enrichment for L2/3 Upregulated Genes")

# Plot GO enrichment for L5IT
plot_GO(go_L5_results$result, "GO Enrichment for L5IT Upregulated Genes")

```






































