---
title: "R Notebook"
output: html_notebook
---

```{r}

library(Seurat)
library(SeuratDisk)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(patchwork)
library(dplyr)
library(data.table)
library(clustree)
library(reshape2)
library(tidyr)
library(gridExtra)
library(stringr)
library(plyr)
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_integration_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/xgboost_train.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/plottingFxns.R")

obj.mouse <- readRDS("E:/Transcriptomics_V1/Mouse/Arlotta/ArlottaLab.rds")

```


```{r}

obj.mouse$timepoint <- obj.mouse$biosample_id
obj.mouse$timepoint[obj.mouse$biosample_id == "E18_S1"] <- "E18"
obj.mouse$timepoint[obj.mouse$biosample_id == "E18_S3"] <- "E18"
obj.mouse$timepoint[obj.mouse$biosample_id == "P1_S1"] <- "P1"
obj.mouse <- obj.mouse[, obj.mouse$biosample_id != "P1_S1"]

```


```{r}

timepoints <- c("P1", "P4") # unique(obj.mouse$timepoint)
objs.mouse <- list()
for (t in timepoints) {
  obj.temp <- subset(obj.mouse, timepoint == t)
  obj.temp <- ClusterSCT(obj.temp, c(1))
  objs.mouse[[t]] <- obj.temp
}

```


```{r}

timepoint <- "P4"
DimPlot(objs.mouse[[timepoint]], reduction = "umap", group.by = "New_cellType", label = T, raster = FALSE, label.size = 2) + NoLegend() + xlim(-8, 15) + ylim(-8, 12) + coord_equal()
obj.mouse.P4 <- subset(objs.mouse[["P4"]], New_cellType == c("UL CPN", "Layer 4", "DL_CPN_1", "DL_CPN_2", "CThPN", "Layer 6b", "SCPN", "NP"))
obj.mouse.P4 <- ClusterSCT(obj.mouse.P4, c(1))
DimPlot(obj.mouse.P4, reduction = "umap", group.by = "New_cellType", label = T, raster = FALSE, label.size = 3) + NoLegend() + xlim(-8, 8) + ylim(-8, 8) + coord_equal()

```


```{r}

timepoints <- c("P1", "P4")
objs.IT <- list()
for (t in timepoints) {
  objs.IT[[t]] <- subset(objs.mouse[[t]], New_cellType == c("UL CPN", "Layer 4", "DL CPN", "DL_CPN_1", "DL_CPN_2"))
  objs.IT[[t]] <- NormalizePCA(objs.IT[[t]])
  p <- DimPlot(objs.IT[[t]], reduction = "pca", group.by = "New_cellType", label = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-20, 20) + coord_equal()
  print(p)
}

```


```{r}

obj.mouse.P1.IT <- objs.IT$P1
obj.mouse.P4.IT <- objs.IT$P4

```


```{r}

obj.opossum.glutamatergic <- readRDS("E:/Transcriptomics_V1/Opossum/seurat/opossum_v1_glutamatergic_processed.rds")
Idents(obj.opossum.glutamatergic) <- "subclass"
obj.opossum.IT <- subset(obj.opossum.glutamatergic, idents = c("IT_A", "IT_B", "IT_C", "IT_D"))
obj.opossum.IT <- NormalizePCA(obj.opossum.IT)

```


```{r}

shared.HVFs <- SelectIntegrationFeatures(object.list = c(obj.mouse.IT, obj.opossum.IT), nfeatures = 3000)
obj.opossum.IT.SS.MP <- obj.opossum.IT[, sample(colnames(obj.opossum.IT), length(colnames(obj.mouse.IT)))]
obj.mouse.IT$species <- "Mouse"
obj.combined.IT <- merge(obj.mouse.IT, obj.opossum.IT.SS.MP)
obj.combined.IT <- SCTransform(obj.combined.IT, vst.flavor = "v2", residual.features = shared.HVFs, return.only.var.genes = FALSE, verbose = FALSE) %>%
                   RunPCA(npcs = 30, verbose = FALSE)

```


```{r}

DimPlot(obj.combined.IT, reduction = "pca", dims = c(6, 7), cols = c("#aaaaaa", "#c692b8"), group.by = "species", pt.size = 1, label = FALSE, shuffle = TRUE, raster = FALSE) + xlim(-30, 35) + ylim(-25, 40) + coord_equal()

```


```{r}

PlotPCLoadingsCorrelation(c(obj.opossum.IT, obj.mouse.IT), c("Opossum", "Mouse"))

```


```{r}

PlotWithinSpeciesVarianceExplained(obj.combined.IT, c("Opossum", "Mouse"), num_pcs = 30)

```


```{r}

obj.mouse.IT.Proj <- PCAProject(obj.mouse.IT, obj.opossum.IT)
DimPlot(obj.opossum.IT, reduction = "pca", group.by = "subclass", label = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-20, 20) + coord_equal()
DimPlot(obj.mouse.IT.Proj, reduction = "pca", group.by = "New_cellType", label = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-20, 20) + coord_equal()

```


```{r}

obj.mouse.P6.glutamatergic <- readRDS("E:/Transcriptomics_V1/Mouse/seurat/mouse_v1_P6_glutamatergic_processed.rds")
Idents(obj.mouse.P6.glutamatergic) <- "subclass"
obj.mouse.P6.IT <- subset(obj.mouse.P6.glutamatergic, idents = c("L2/3", "L4", "L5IT", "L6IT"))
obj.mouse.P6.IT <- NormalizePCA(obj.mouse.P6.IT)

```


```{r}

obj.mouse.P1.IT.Proj <- PCAProject(obj.mouse.P1.IT, obj.mouse.P6.IT)
DimPlot(obj.mouse.P6.IT, reduction = "pca", group.by = "subclass", label = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-20, 20) + coord_equal()
DimPlot(obj.mouse.P1.IT.Proj, reduction = "pca", group.by = "New_cellType", label = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-20, 20) + coord_equal()

```


```{r}

obj.mouse.P4.IT.Proj <- PCAProject(obj.mouse.P4.IT, obj.mouse.P6.IT)
DimPlot(obj.mouse.P6.IT, reduction = "pca", group.by = "subclass", label = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-20, 20) + coord_equal()
DimPlot(obj.mouse.P4.IT.Proj, reduction = "pca", group.by = "New_cellType", label = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-20, 20) + coord_equal()

```


```{r}

obj.opossum.IT.Proj <- PCAProject(obj.opossum.IT, obj.mouse.P6.IT)
DimPlot(obj.mouse.P6.IT, reduction = "pca", group.by = "subclass", label = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-20, 20) + coord_equal()
DimPlot(obj.opossum.IT.Proj, reduction = "pca", group.by = "subclass", label = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-20, 20) + coord_equal()

```


```{r}

library(ggplot2)
library(dplyr)

# Extract embeddings and metadata from each Seurat object
mouse_P6 <- as.data.frame(Embeddings(obj.mouse.P6.IT, "pca")[, 1:2]) %>%
  mutate(species = "mouse_P6")

mouse_P1_Proj <- as.data.frame(Embeddings(obj.mouse.P1.IT.Proj, "pca")[, 1:2]) %>%
  mutate(species = "mouse_P1_Proj")
colnames(mouse_P1_Proj) <- c("PC_1", "PC_2", "species")

mouse_P4_Proj <- as.data.frame(Embeddings(obj.mouse.P4.IT.Proj, "pca")[, 1:2]) %>%
  mutate(species = "mouse_P4_Proj")
colnames(mouse_P4_Proj) <- c("PC_1", "PC_2", "species")

opossum_Proj <- as.data.frame(Embeddings(obj.opossum.IT.Proj, "pca")[, 1:2]) %>%
  mutate(species = "opossum_Proj")
colnames(opossum_Proj) <- c("PC_1", "PC_2", "species")

# Combine all data frames
combined_data <- bind_rows(mouse_P6, mouse_P1_Proj, mouse_P4_Proj, opossum_Proj)

# Rename the columns to make it clearer
colnames(combined_data) <- c("PC1", "PC2", "species")

# Plot using ggplot2 with new colors and alpha adjustment
ggplot(combined_data, aes(x = PC1, y = PC2, color = species)) +
  geom_point(alpha = 0.5) +
  theme_minimal() +
  labs(title = "Projection of Cells onto PC1 and PC2",
       x = "PC1",
       y = "PC2") +
  scale_color_manual(values = c("mouse_P6" = "gray", "mouse_P1_Proj" = "purple", "mouse_P4_Proj" = "#fcba03", "opossum_Proj" = "#FF0000"))

```

