---
title: "mouse M1 Object"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
library(data.table)

obj.mouse.P38 <- LoadH5Seurat("E:/Transcriptomics_V1/Mouse/seurat/mouse_v1_all.h5seurat")

```


```{r}

Idents(obj.mouse.P38) <- "subclass"
obj.mouse.glutamatergic.P38 <- subset(obj.mouse.P38, idents = c("L2/3", "L4", "L5IT", "L6IT", "L5PT", "L5NP", "L6CT", "L6b"))

```


```{r}

all.genes <- rownames(obj.mouse.glutamatergic.P38)
obj.mouse.glutamatergic.P38 <- NormalizeData(obj.mouse.glutamatergic.P38, features = all.genes)
obj.mouse.glutamatergic.P38 <- FindVariableFeatures(obj.mouse.glutamatergic.P38, selection.method = "vst", nfeatures = 3000)
obj.mouse.glutamatergic.P38 <- ScaleData(obj.mouse.glutamatergic.P38, features = all.genes)
obj.mouse.glutamatergic.P38 <- RunPCA(obj.mouse.glutamatergic.P38, features = VariableFeatures(object = obj.mouse.glutamatergic.P38))
ElbowPlot(obj.mouse.glutamatergic.P38, ndims = 50)

```


```{r}

obj.mouse.glutamatergic.P38 <- FindNeighbors(obj.mouse.glutamatergic.P38, dims = 1:30)
obj.mouse.glutamatergic.P38 <- FindClusters(obj.mouse.glutamatergic.P38, resolution = 1, algorithm = 4, method = "igraph")
obj.mouse.glutamatergic.P38 <- RunUMAP(obj.mouse.glutamatergic.P38, dims = 1:30, method="umap-learn")

```


```{r}

DimPlot(obj.mouse.glutamatergic.P38, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.glutamatergic.P38, reduction = "umap", group.by = "subclass", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.glutamatergic.P38, reduction = "umap", group.by = "type", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.glutamatergic.P38, reduction = "umap", group.by = "sample", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.P38, "nFeature_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.P38, "nCount_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.glutamatergic.P38, reduction = "umap", group.by = "predicted_doublets", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

DimPlot(obj.mouse.glutamatergic.P38, reduction = "umap", group.by = "subclass", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.glutamatergic.P38, reduction = "umap", group.by = "type", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.P38, reduction = "umap", features = c("Cux2"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.P38, reduction = "umap", features = c("Rorb"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.P38, reduction = "umap", features = c("Deptor"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.P38, reduction = "umap", features = c("Foxp2"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.P38, reduction = "umap", features = c("Cdh9"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse.glutamatergic.P38, reduction = "umap", features = c("Dcc"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
# FeaturePlot(obj.mouse.glutamatergic.P38, reduction = "umap", features = c("Netrin"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

Idents(obj.mouse.glutamatergic.P38) <- "type"
L23.markers.mouse.A <- FindMarkers(obj.mouse.glutamatergic.P38, ident.1 = c("L2/3_A"), ident.2 = c("L2/3_B", "L2/3_C"), only.pos = TRUE, min.pct = 0.10, logfc.threshold = 0.4)
L23.markers.mouse.B <- FindMarkers(obj.mouse.glutamatergic.P38, ident.1 = c("L2/3_B"), ident.2 = c("L2/3_A", "L2/3_C"), only.pos = TRUE, min.pct = 0.10, logfc.threshold = 0.4)
L23.markers.mouse.C <- FindMarkers(obj.mouse.glutamatergic.P38, ident.1 = c("L2/3_C"), ident.2 = c("L2/3_A", "L2/3_B"), only.pos = TRUE, min.pct = 0.10, logfc.threshold = 0.4)

gradient.genes <- read.csv("G:/Shared drives/Opossum transcriptomics/genes/gradient_genes.txt", sep = "\t")
gradient.genes.A <- gradient.genes$gene[(gradient.genes$anno_L23 == "A") & is.na(gradient.genes$anno_L23 == "A") == FALSE]
gradient.genes.B <- gradient.genes$gene[gradient.genes$anno_L23 == "B" & is.na(gradient.genes$anno_L23 == "B") == FALSE]
gradient.genes.C <- gradient.genes$gene[gradient.genes$anno_L23 == "C" & is.na(gradient.genes$anno_L23 == "C") == FALSE]

```


```{r}

Idents(obj.mouse.glutamatergic.P38) <- "type"
L6CT.markers.mouse.A <- FindMarkers(obj.mouse.glutamatergic.P38, ident.1 = c("L6CT_A"), ident.2 = c("L6CT_B", "L6CT_C"), only.pos = TRUE, min.pct = 0.10, logfc.threshold = 0.4)
L6CT.markers.mouse.B <- FindMarkers(obj.mouse.glutamatergic.P38, ident.1 = c("L6CT_B"), ident.2 = c("L6CT_A", "L6CT_C"), only.pos = TRUE, min.pct = 0.10, logfc.threshold = 0.4)
L6CT.markers.mouse.C <- FindMarkers(obj.mouse.glutamatergic.P38, ident.1 = c("L6CT_C"), ident.2 = c("L6CT_A", "L6CT_B"), only.pos = TRUE, min.pct = 0.10, logfc.threshold = 0.4)

```


```{r}

Idents(obj.mouse.glutamatergic.P38) <- "type"
L6IT.markers.mouse.A <- FindMarkers(obj.mouse.glutamatergic.P38, ident.1 = c("L6IT_A"), ident.2 = c("L6IT_B"), only.pos = TRUE, min.pct = 0.10, logfc.threshold = 0.4)
L6IT.markers.mouse.B <- FindMarkers(obj.mouse.glutamatergic.P38, ident.1 = c("L6IT_B"), ident.2 = c("L6IT_A"), only.pos = TRUE, min.pct = 0.10, logfc.threshold = 0.4)

```


```{r}

SaveH5Seurat(obj.mouse.glutamatergic.P38, "E:/Transcriptomics_v1/Mouse/seurat/mouse_v1_P38_glutamatergic.h5seurat", overwrite = TRUE, verbose = TRUE)

```

