---
title: "R Notebook"
output: html_notebook
---


```{r}

library(Seurat)
library(SeuratDisk)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(patchwork)
library(dplyr)
library(data.table)
library(clustree)
library(reshape2)
library(tidyr)
library(gridExtra)
library(stringr)
library(plyr)
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_integration_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/xgboost_train.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/plottingFxns.R")

classes <- c("Glutamatergic", "GABAergic", "Nonneuronal")
objs.mouse <- c()
objs.opossum <- c()
objs.i.mouse <- c()
objs.i.opossum <- c()
objs.m.mouse <- c()
objs.m.opossum <- c()

for (cl in classes) {

  obj.opossum <- readRDS(paste0("E:/Transcriptomics_V1/Opossum/seurat/opossum_v1_", tolower(cl), "_processed.rds"))
  obj.opossum$species <- "Opossum"
  obj.mouse.P38 <- readRDS(paste0("E:/Transcriptomics_V1/Mouse/seurat/mouse_v1_P38_", tolower(cl), "_processed.rds"))
  obj.mouse.P38$species <- "Mouse"

  objs <- list(obj.opossum, obj.mouse.P38)
  obj.integrated <- IntegrateObjects(objs[[1]], objs[[2]], resolutions = c(1, 2), nfeatures = 3000, subsample = TRUE)
  objs.i <- SplitObject(obj.integrated, split.by = "species")
  objs.m <- MapObjects(objs.i[["Opossum"]], objs.i[["Mouse"]], c("subclass", "type"), assay = "integrated")
  objs.mouse <- append(objs.mouse, objs[[2]])
  objs.opossum <- append(objs.opossum, objs[[1]])
  objs.i.mouse <- append(objs.i.mouse, objs.i[["Mouse"]])
  objs.i.opossum <- append(objs.i.opossum, objs.i[["Opossum"]])
  objs.m.mouse <- append(objs.m.mouse, objs.m[[2]])
  objs.m.opossum <- append(objs.m.opossum, objs.m[[1]])
  
}

obj.mouse <- merge(objs.mouse[[1]], y = c(objs.mouse[[2]], objs.mouse[[3]]))
obj.opossum <- merge(objs.opossum[[1]], y = c(objs.opossum[[2]], objs.opossum[[3]]))
obj.m.mouse <- merge(objs.m.mouse[[1]], y = c(objs.m.mouse[[2]], objs.m.mouse[[3]]))
obj.m.opossum <- merge(objs.m.opossum[[1]], y = c(objs.m.opossum[[2]], objs.m.opossum[[3]]))

```


```{r}

obj.mouse <- ClusterSCT(obj.mouse, c(1))
obj.m.mouse <- ClusterSCT(obj.m.mouse, c(1))
obj.opossum <- ClusterSCT(obj.opossum, c(1))
obj.m.opossum <- ClusterSCT(obj.m.opossum, c(1))

```


```{r}

obj.mouse <- readRDS("E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/obj_mouse.rds")
obj.opossum <- readRDS("E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/obj_opossum.rds")
objs.i.mouse <- readRDS("E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/obj_i_mouse.rds")
objs.i.opossum <- readRDS("E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/obj_i_opossum.rds")
objs.m.mouse <- readRDS("E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/objs_m_mouse.rds")
objs.m.opossum <- readRDS("E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/objs_m_opossum.rds")
obj.m.mouse <- readRDS("E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/obj_m_mouse.rds")
obj.m.opossum <- readRDS("E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/obj_m_opossum.rds")

```


```{r}

colors_list <- list(
              # Glutamatergic
              IT = "#FF6C88",
              IT_A = "#FFB3B3",
              `L2/3` = "#FFB3B3",
              IT_B = "#FFA07A",
              L4 = "#FF7F50",
              IT_C = "#FF7F50",
              L5IT = "#FFA07A",
              IT_D = "#FF6347",
              L6IT = "#FF6347",
              L5NP = "#FF4500",
              L5PT = "#FF8C69",
              L6CT = "#FFA07A",
              L6b = "#FF6347",
            
              # GABAergic
              Pvalb = "#1E90FF",
              Sst = "#87CEEB",
              Vip = "#87CEFA",
              Lamp5 = "#4682B4",
              Frem1 = "#ADD8E6",
              Stac = "#5F9EA0",
            
              # Non-neuronal
              Astro = "#8C8C8C",
              Micro = "#A0A0A0",
              OD = "#B4B4B4",
              OPC = "#C8C8C8",
              Endo = "#505050",
              VLMC = "#B4B4B4"
)

```


```{r}

obj.mouse$species <- "Mouse"
obj.opossum$species <- "Opossum"
obj.combined <- merge(obj.mouse, y = obj.opossum)
obj.combined$subclass.plot <- obj.combined$subclass
obj.combined$subclass.plot[obj.combined$subclass %in% c("IT_A", "IT_B", "IT_C", "IT_D", "IT_E", 
                                                        "L2/3", "L4", "L5IT", "L6IT")] <- "IT"

Idents(obj.mouse) <- "subclass"
obj.mouse.glutamatergic <- subset(obj.mouse, idents = c("L2/3", "L4", "L5IT", "L6IT", "L5NP", "L5PT", "L6CT", "L6b"))
obj.mouse.gabaergic <- subset(obj.mouse, idents = c("Pvalb", "Sst", "Vip", "Lamp5", "Frem1", "Stac"))
obj.mouse.nonneuronal <- subset(obj.mouse, idents = c("Astro", "Micro", "OD", "OPC", "Endo", "VLMC"))

Idents(obj.opossum) <- "subclass"
obj.opossum.glutamatergic <- subset(obj.opossum, idents = c("IT_A", "IT_B", "IT_C", "IT_D", "L5NP", "L5PT", "L6CT", "L6b"))
obj.opossum.gabaergic <- subset(obj.opossum, idents = c("Pvalb", "Sst", "Vip", "Lamp5", "Frem1"))
obj.opossum.nonneuronal <- subset(obj.opossum, idents = c("Astro", "Micro", "OD", "OPC", "Endo"))

```


```{r, fig.width=8, fig.height=8}

Idents(obj.combined) <- "subclass.plot"
levels(obj.combined) <- rev(c("IT", "L5NP", "L5PT", "L6CT", "L6b",
                              "Pvalb", "Sst", "Vip", "Lamp5", "Frem1", "Stac", 
                              "Astro", "Micro", "OD", "OPC", "Endo", "VLMC"))
DotPlot(obj.combined, assay = "RNA", features = c("Syt14", "Satb2", "Nxph3", "Fezf2", "Foxp2", "Drd1", 
                                                  "Gad1", "Pvalb", "Sst", "Vip", "Lamp5", "Frem1", "Stac", 
                                                  "Aldh1l1", "Csf1r", "Mog", "Pdgfra", "Flt1", "Slc47a1"), 
                                     cols = c("#aaaaaa", "#c692b8"), split.by = "species", scale = T, scale.by = "radius", scale.max = 50, col.max = 2) + 
                      theme(axis.text.x=element_text(angle = 90, vjust = 0.4))

p <- DotPlot(obj.combined, assay = "RNA", features = c("Syt14", "Satb2", "Nxph3", "Fezf2", "Foxp2", "Drd1", 
                                                  "Gad1", "Pvalb", "Sst", "Vip", "Lamp5", "Frem1", "Stac", 
                                                  "Aldh1l1", "Csf1r", "Mog", "Pdgfra", "Flt1", "Slc47a1"), 
                                     cols = c("#aaaaaa", "#c692b8"), split.by = "species", scale = T, scale.by = "radius", scale.max = 50, col.max = 2) + 
                      theme(axis.text.x=element_text(angle = 90, vjust = 0.4))

ggsave("E:/Opossum_Paper/Figure 1/Opossum_Mouse-P38_DotPlot.svg", plot = p, width = 8, height = 8, dpi = 300)
ggsave("E:/Opossum_Paper/Figure 1/Opossum_Mouse-P38_DotPlot.png", plot = p, width = 8, height = 8, dpi = 300)

```


```{r}

obj.combined <- PrepSCTFindMarkers(obj.combined)

```


```{r}

markers.Neuronal <- FindConservedMarkers(obj.combined, ident.1 = c("IT", "L5NP", "L5PT", "L6CT", "L6b", "Pvalb", "Sst", "Vip", "Frem1"), grouping.var = "species")

```


```{r}

library(viridisLite)

DefaultAssay(obj.mouse.glutamatergic) <- "SCT"
Idents(obj.mouse.glutamatergic) <- "subclass"
mouse.levels <- c("L2/3", "L4", "L5IT", "L6IT", "L5NP", "L5PT", "L6CT", "L6b")
levels(obj.mouse.glutamatergic) <- mouse.levels
DoHeatmap(obj.mouse.glutamatergic, features = c("Ccbe1", "Mdga1", "Stard8", "Cux2", 
                                                "Whrn", "Rorb", 
                                                "Deptor", "Foxo1", "Ptprm", 
                                                "Zfp804b", "Cdh9", 
                                                "Tshz2", 
                                                "Erg", "Reln", 
                                                "Foxp2", "Syt6", 
                                                "Inpp4b", "Svil"), 
                                     slot = "scale.data", 
                                     group.colors = as.character(colors_list[mouse.levels]), 
                                     size = 3, disp.min = 0, disp.max = 3) + scale_fill_viridis(option = "A")

DefaultAssay(obj.opossum.glutamatergic) <- "SCT"
Idents(obj.opossum.glutamatergic) <- "subclass"
opossum.levels <- c("IT_A", "IT_C", "IT_B", "IT_D", "L5NP", "L5PT", "L6CT", "L6b")
levels(obj.opossum.glutamatergic) <- opossum.levels
DoHeatmap(obj.opossum.glutamatergic, features = c("Ccbe1", "Mdga1", "Stard8", "Cux2", 
                                                  "Whrn", "Rorb", 
                                                  "Deptor", "Foxo1", "Ptprm", 
                                                  "Zfp804b", "Cdh9", 
                                                  "Tshz2", 
                                                  "Erg", "Reln", 
                                                  "Foxp2", "Syt6", 
                                                  "Inpp4b", "Svil"), 
                                     slot = "scale.data", 
                                     group.colors = as.character(colors_list[opossum.levels]), 
                                     size = 3, disp.min = 0, disp.max = 3) + scale_fill_viridis(option = "A")

```


```{r}

library(viridisLite)

DefaultAssay(obj.mouse.glutamatergic) <- "SCT"
Idents(obj.mouse.glutamatergic) <- "subclass"
mouse.levels <- c("L2/3", "L4", "L5IT", "L6IT", "L5NP", "L5PT", "L6CT", "L6b")
levels(obj.mouse.glutamatergic) <- mouse.levels
DoHeatmap(obj.mouse.glutamatergic, features = c("Cux1", "Cux2", "Satb2", "Satb1", "Plxnd1", "Otof", "Rspo1", 
                                                "Nrp1", "Tle4", "Sox5", "Osr1", 
                                                "Foxp2", "Tbr1", "Fezf2"), 
                                     slot = "scale.data", 
                                     group.colors = as.character(colors_list[mouse.levels]), 
                                     size = 3, disp.min = 0, disp.max = 3) + scale_fill_viridis(option = "A")

DefaultAssay(obj.opossum.glutamatergic) <- "SCT"
Idents(obj.opossum.glutamatergic) <- "subclass"
opossum.levels <- c("IT_A", "IT_C", "IT_B", "IT_D", "L5NP", "L5PT", "L6CT", "L6b")
levels(obj.opossum.glutamatergic) <- opossum.levels
DoHeatmap(obj.opossum.glutamatergic, features = c("Cux1", "Cux2", "Satb2", "Satb1", "Pou3f3", "Plxnd1", "Otof", "Rspo1", 
                                                  "Bcl11b", "Nrp1", "Tle4", "Sox5", "Osr1", 
                                                  "Foxp2", "Tbr1", "Fezf2"), 
                                     slot = "scale.data", 
                                     group.colors = as.character(colors_list[opossum.levels]), 
                                     size = 3, disp.min = 0, disp.max = 3) + scale_fill_viridis(option = "A")

```


```{r}

DefaultAssay(obj.mouse.gabaergic) <- "SCT"
Idents(obj.mouse.gabaergic) <- "subclass"
mouse.levels <- c("Pvalb", "Sst", "Vip", "Lamp5", "Frem1", "Stac")
levels(obj.mouse.gabaergic) <- mouse.levels
DoHeatmap(obj.mouse.gabaergic, features = c("Pvalb", "Myo1e", "Syt2", "Myo5b", "Cemip", "Plcxd3", "Nek7", 
                                            "Sst", "Unc13c", "Lama4", "Ptpru", "Grik3", "Tmcc3", 
                                            "Vip", "Sema5b", 
                                            "Lamp5", "Sv2c", "Ndnf", "Crispld1", "Atp6ap1l", 
                                            "Frem1", "Megf10", "March3", 
                                            "Stac", "Cobll1"), 
                                     slot = "scale.data", 
                                     group.colors = as.character(colors_list[mouse.levels]), 
                                     size = 3, disp.min = 0, disp.max = 3) + scale_fill_viridis(option = "A")

DefaultAssay(obj.opossum.gabaergic) <- "SCT"
Idents(obj.opossum.gabaergic) <- "subclass"
opossum.levels <- c("Pvalb", "Sst", "Vip", "Lamp5", "Frem1")
levels(obj.opossum.gabaergic) <- opossum.levels
DoHeatmap(obj.opossum.gabaergic, features = c("Pvalb", "Myo1e", "Syt2", "Myo5b", "Cemip", "Plcxd3", "Nek7", 
                                              "Sst", "Unc13c", "Lama4", "Ptpru", "Grik3", "Tmcc3", 
                                              "Vip", "Sema5b", 
                                              "Lamp5", "Sv2c", "Ndnf", "Crispld1", "Atp6ap1l", 
                                              "Frem1", "Megf10", 
                                              "Cobll1"), 
                                     slot = "scale.data", 
                                     group.colors = as.character(colors_list[opossum.levels]), 
                                     size = 3, disp.min = 0, disp.max = 3) + scale_fill_viridis(option = "A")

```


```{r}

DefaultAssay(obj.mouse.nonneuronal) <- "SCT"
Idents(obj.mouse.nonneuronal) <- "subclass"
mouse.levels <- c("Astro", "Micro", "OD", "OPC", "Endo", "VLMC")
levels(obj.mouse.nonneuronal) <- mouse.levels
DoHeatmap(obj.mouse.nonneuronal, features = c("Aldh1l1", "Grin2c", "Phkg1", 
                                            "Cx3cr1", "Arhgap45", "Inpp5d", 
                                            "Enpp6", "St18", 
                                            "Pdgfra", "Cacng4", 
                                            "Pecam1", "Mecom", "Flt1"), 
                                     slot = "scale.data", 
                                     group.colors = as.character(colors_list[mouse.levels]), 
                                     size = 3, disp.min = 0, disp.max = 3) + scale_fill_viridis(option = "A")

DefaultAssay(obj.opossum.nonneuronal) <- "SCT"
Idents(obj.opossum.nonneuronal) <- "subclass"
opossum.levels <- c("Astro", "Micro", "OD", "OPC", "Endo")
levels(obj.opossum.nonneuronal) <- opossum.levels
DoHeatmap(obj.opossum.nonneuronal, features = c("Aldh1l1", "Grin2c", "Phkg1", 
                                              "Cx3cr1", "Arhgap45", "Inpp5d", 
                                              "Enpp6", "St18", 
                                              "Pdgfra", "Cacng4", 
                                              "Pecam1", "Mecom", "Flt1"), 
                                     slot = "scale.data", 
                                     group.colors = as.character(colors_list[opossum.levels]), 
                                     size = 3, disp.min = 0, disp.max = 3) + scale_fill_viridis(option = "A")

```


Next, plot top shared markers in the same way...


```{r}

saveRDS(obj.mouse, "E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/obj_mouse.rds")
saveRDS(obj.opossum, "E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/obj_opossum.rds")
saveRDS(objs.i.mouse, "E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/obj_i_mouse.rds")
saveRDS(objs.i.opossum, "E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/obj_i_opossum.rds")
saveRDS(objs.m.mouse, "E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/objs_m_mouse.rds")
saveRDS(objs.m.opossum, "E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/objs_m_opossum.rds")
saveRDS(obj.m.mouse, "E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/obj_m_mouse.rds")
saveRDS(obj.m.opossum, "E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/obj_m_opossum.rds")

```

