---
title: "R Notebook"
output: html_notebook
---


```{r}

library(Seurat)
library(SeuratDisk)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(patchwork)
library(dplyr)
library(data.table)
library(clustree)
library(reshape2)
library(tidyr)
library(gridExtra)
library(stringr)
library(plyr)
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_integration_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/xgboost_train.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/plottingFxns.R")

# obj.opossum.glutamatergic <- readRDS("E:/Transcriptomics_V1/Opossum/seurat/opossum_v1_glutamatergic_processed.rds")
obj.opossum.glutamatergic$subclass <- obj.opossum.glutamatergic$SCT_snn_res.2
obj.opossum.glutamatergic$type <- obj.opossum.glutamatergic$SCT_snn_res.2
obj.mouse.glutamatergic.P38 <- readRDS("E:/Transcriptomics_V1/Mouse/seurat/mouse_v1_P38_glutamatergic_processed.rds")
obj.mouse.glutamatergic.P38$species <- "Mouse"

objs <- list(obj.opossum.glutamatergic, obj.mouse.glutamatergic.P38)

```


```{r}

obj.integrated <- IntegrateObjects(objs[[1]], objs[[2]], resolutions = c(1), nfeatures = 6000, subsample = TRUE)

```


```{r}

subclasses <- c(c("L2/3", "L4", "L5IT", "L5NP", "L5PT", "L6CT", "L6IT", "L6b"), as.character(1:27))
PlotIntegration(obj.integrated, "species", c("integrated_snn_res.1"), subclasses)

```


```{r}

objs.i <- SplitObject(obj.integrated, split.by = "species")

```


```{r}

objs.m <- MapObjects(objs.i[[1]], objs.i[[2]], c("subclass", "type"), assay = "integrated")

```


```{r}

PlotMapping(objs.m, ident.order = subclasses)

```


```{r}

DimPlot(obj.mouse.glutamatergic.P38, group.by = "subclass", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
vfs <- VariableFeatures(obj.mouse.glutamatergic.P38[["SCT"]])
for (vf in 1:20) {
  p <- FeaturePlot(obj.mouse.glutamatergic.P38, features = vfs[vf], max.cutoff = 10, raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
  print(p)
}

```


```{r}

DimPlot(obj.opossum.glutamatergic, group.by = "SCT_snn_res.1", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
vfs <- VariableFeatures(obj.opossum.glutamatergic[["SCT"]])
for (vf in 21:40) {
  p <- FeaturePlot(obj.opossum.glutamatergic, features = vfs[vf], max.cutoff = 10, raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
  print(p)
}

```


```{r}

Idents(obj.opossum.glutamatergic) <- "SCT_snn_res.1"
obj.opossum.glutamatergic.IT <- subset(obj.opossum.glutamatergic, idents = c(2, 3, 4, 5, 7, 8, 9, 10, 11, 13, 14, 15, 17, 19))
obj.opossum.glutamatergic.IT <- ClusterSCT(obj.opossum.glutamatergic.IT, resolutions = c(1))

```


```{r}

PlotClusters(obj.opossum.glutamatergic.IT, group.id = "SCT_snn_res.1")

```


```{r}

FeaturePlot(obj.opossum.glutamatergic.IT, features = c("Cux2"))

```
































