---
title: "R Notebook"
output: html_notebook
---


```{r}

library(Seurat)
library(SeuratDisk)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(patchwork)
library(dplyr)
library(data.table)
library(clustree)
library(reshape2)
library(tidyr)
library(gridExtra)
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_integration_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/xgboost_train.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/plottingFxns.R")

obj.opossum.gabaergic.1AB <- readRDS("E:/Transcriptomics_V1/Opossum/1AB/seurat/opossum_v1_gabaergic_1AB_processed.rds")
subclass.markers.opossum.gabaergic.1AB <- readRDS("E:/Transcriptomics_V1/Opossum/1AB/seurat/marker_genes/markerdict_subclass.rds")
markers.opossum.gabaergic.1AB <- readRDS("E:/Transcriptomics_V1/Opossum/1AB/seurat/marker_genes/markerdict_types.rds")
obj.opossum.gabaergic.2AB <- readRDS("E:/Transcriptomics_V1/Opossum/2AB/seurat/opossum_v1_gabaergic_2AB_processed.rds")
subclass.markers.opossum.gabaergic.2AB <- readRDS("E:/Transcriptomics_V1/Opossum/2AB/seurat/marker_genes/markerdict_subclass.rds")
markers.opossum.gabaergic.2AB <- readRDS("E:/Transcriptomics_V1/Opossum/2AB/seurat/marker_genes/markerdict_types.rds")

objs <- list(obj.opossum.gabaergic.1AB, obj.opossum.gabaergic.2AB)
subclass.markers <- list(subclass.markers.opossum.gabaergic.1AB, subclass.markers.opossum.gabaergic.2AB)
type.markers <- list(markers.opossum.gabaergic.1AB, markers.opossum.gabaergic.2AB)
sample.names <- list("OpossumV1-1AB", "OpossumV1-2AB")

```


```{r}

subclasses <- c("Pvalb", "Sst", "Vip", "Lamp5", "Frem1", "Stac")

# pre-integration subclass comparison (DE genes)
PlotSubclassDEIntersection(subclass.markers[[1]], subclass.markers[[2]], 
                           rownames(objs[[1]]), rownames(objs[[2]]),
                           sample.names[[1]], sample.names[[2]],
                           subclasses, 0.2, percentage = T)

# pre-integration type comparison (DE genes)
for (sbcl in subclasses) {
  if (sbcl %in% names(type.markers[[1]]) & sbcl %in% names(type.markers[[2]])) {
    p <- PlotIdentDEIntersection(type.markers[[1]], type.markers[[2]],
                                 rownames(objs[[1]]), rownames(objs[[2]]),
                                 sample.names[[1]], sample.names[[2]],
                                 sbcl, sbcl, "type", "type", 0.2, percentage = T)
    print(p)
  }
}

```


```{r, fig.width=15, fig.height=6}

sbcl_conf_plots <- PlotSubclassCrossConfusionMatrices(objs[[1]], objs[[2]], sample.names[[1]], sample.names[[2]], subclasses, n_iters = 10, all.genes = TRUE, downsample = TRUE)

```


```{r}

print(sbcl_conf_plots[[1]])
print(sbcl_conf_plots[[2]])

```


```{r, fig.width=15, fig.height=6}

subclass.labels <- c("Pvalb") # , "Sst"
ident.labels <- c("type")

idnt_conf_plots <- PlotIdentCrossConfusionMatrices(objs[[1]], objs[[2]], sample.names[[1]], sample.names[[2]], subclass.labels, ident.labels, n_iters = 1, all.genes = TRUE, upsample = TRUE)

```


```{r}

for (sbcl in subclass.labels) {
  for (id in ident.labels) {
    print(idnt_conf_plots[[sbcl]][[id]][["avg1"]])
    print(idnt_conf_plots[[sbcl]][[id]][["avg2"]])
  }
}

```

