---
title: "R Notebook"
output: html_notebook
---


```{r}

library(Seurat)
library(SeuratDisk)
library(SeuratWrappers)
library(monocle3)
library(pheatmap)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(patchwork)
library(dplyr)
library(data.table)
library(clustree)
library(reshape2)
library(tidyr)
library(gridExtra)
library(stringr)
library(plyr)
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_integration_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/xgboost_train.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/plottingFxns.R")

obj.opossum.glutamatergic <- readRDS("E:/Transcriptomics_V1/Opossum/seurat/opossum_v1_glutamatergic_processed.rds")
obj.mouse.glutamatergic <- readRDS("E:/Transcriptomics_V1/Mouse/seurat/mouse_v1_P38_glutamatergic_processed.rds")

```


```{r}

colors_list <- list(
              # Glutamatergic
              IT = "#FF6C88",
              IT_A = "#FFB3B3",
              `L2/3` = "#FFB3B3",
              IT_B = "#FFA07A",
              L4 = "#FF7F50",
              IT_C = "#FF7F50",
              L5IT = "#FFA07A",
              IT_D = "#FF6347",
              L6IT = "#FF6347",
              L5NP = "#FF4500",
              L5PT = "#32a852", 
              L6CT = "#7de89a",
              L6b = "#206633",
            
              # GABAergic
              Pvalb = "#1E90FF",
              Sst = "#87CEEB",
              Vip = "#87CEFA",
              Lamp5 = "#4682B4",
              Frem1 = "#ADD8E6",
              Stac = "#5F9EA0",
            
              # Non-neuronal
              Astro = "#8C8C8C",
              Micro = "#A0A0A0",
              OD = "#B4B4B4",
              OPC = "#C8C8C8",
              Endo = "#505050",
              VLMC = "#B4B4B4"
)

```


```{r}

Idents(obj.opossum.glutamatergic) <- "subclass"
obj.opossum.IT <- subset(obj.opossum.glutamatergic, idents = c("IT_A", "IT_B", "IT_C", "IT_D"))

Idents(obj.mouse.glutamatergic) <- "subclass"
obj.mouse.IT <- subset(obj.mouse.glutamatergic, idents = c("L2/3", "L4", "L5IT", "L6IT"))

```


```{r}

source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_functions.R")

obj.opossum.IT.SH <- ShuffleExpression(obj.opossum.IT, "subclass")
obj.opossum.IT.SHA <- ShuffleExpression(obj.opossum.IT, "subclass", ignore_group = TRUE)

obj.mouse.IT.SH <- ShuffleExpression(obj.mouse.IT, "subclass")
obj.mouse.IT.SHA <- ShuffleExpression(obj.mouse.IT, "subclass", ignore_group = TRUE)

```


```{r}

obj.opossum.IT <- ClusterSCT(obj.opossum.IT, resolutions = c(1))
obj.opossum.IT.SH <- SCTransform(obj.opossum.IT.SH, vst.flavor = "v2", return.only.var.genes = FALSE, verbose = FALSE) %>%
                     RunPCA(npcs = 30, verbose = FALSE)
obj.opossum.IT.SHA <- SCTransform(obj.opossum.IT.SHA, vst.flavor = "v2", return.only.var.genes = FALSE, verbose = FALSE) %>%
                      RunPCA(npcs = 30, verbose = FALSE)
obj.mouse.IT <- ClusterSCT(obj.mouse.IT, resolutions = c(1))
obj.mouse.IT.SH <- SCTransform(obj.mouse.IT.SH, vst.flavor = "v2", return.only.var.genes = FALSE, verbose = FALSE) %>%
                     RunPCA(npcs = 30, verbose = FALSE)
obj.mouse.IT.SHA <- SCTransform(obj.mouse.IT.SHA, vst.flavor = "v2", return.only.var.genes = FALSE, verbose = FALSE) %>%
                      RunPCA(npcs = 30, verbose = FALSE)

```


```{r}

source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_functions.R")

obj.opossum.IT <- NormalizePCA(obj.opossum.IT)
obj.opossum.IT.SH <- NormalizePCA(obj.opossum.IT.SH)
obj.opossum.IT.SHA <- NormalizePCA(obj.opossum.IT.SHA)
obj.mouse.IT <- NormalizePCA(obj.mouse.IT)
obj.mouse.IT.SH <- NormalizePCA(obj.mouse.IT.SH)
obj.mouse.IT.SHA <- NormalizePCA(obj.mouse.IT.SHA)

```


```{r}

opossum.pcs <- obj.opossum.IT@reductions$pca@cell.embeddings[, 1:2]
write.table(opossum.pcs, "E:/Transcriptomics_V1/Integration/opossum_pcs.txt", sep = " ", col.names = FALSE, row.names = FALSE)
mouse.pcs <- obj.mouse.IT@reductions$pca@cell.embeddings[, 1:2]
write.table(mouse.pcs, "E:/Transcriptomics_V1/Integration/mouse_pcs.txt", sep = " ", col.names = FALSE, row.names = FALSE)

```


```{r}

source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_functions.R")

# DimPlot(obj.mouse.IT, reduction = "pca", group.by = "sample", pt.size = 1, shuffle = TRUE, raster = FALSE) + xlim(-16, 18) + ylim(-20, 14) + coord_equal()
subclasses.mouse <- c("L2/3", "L4", "L5IT", "L6IT")
Idents(obj.mouse.IT) <- "subclass"
levels(obj.mouse.IT) <- subclasses.mouse
pl <- DimPlot(obj.mouse.IT, reduction = "pca", cols = colors_list[subclasses.mouse], pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-16, 18) + ylim(-20, 14) + coord_equal()
ggsave("E:/Opossum_Paper/Mouse_PC.png", plot = pl, dpi = 300)
ggsave("E:/Opossum_Paper/Mouse_PC.svg", plot = pl, dpi = 300)
# FeaturePlot(obj.mouse.IT, "nCount_RNA", reduction = "pca", pt.size = 2, raster = FALSE) + NoLegend() + xlim(-16, 18) + ylim(-20, 14) + coord_equal()

# DimPlot(obj.mouse.IT.SH, reduction = "pca", group.by = "sample", pt.size = 1, shuffle = TRUE, raster = FALSE) + xlim(-30, 35) + ylim(-45, 20) + coord_equal()
# subclasses.mouse <- c("L2/3", "L4", "L5IT", "L6IT")
# Idents(obj.mouse.IT.SH) <- "subclass"
# levels(obj.mouse.IT.SH) <- subclasses.mouse
# pl <- DimPlot(obj.mouse.IT.SH, reduction = "pca", cols = colors_list[subclasses.mouse], pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-30, 35) + ylim(-45, 20) + coord_equal()
# pl[[1]]$layers[[1]]$aes_params$alpha =  0.8
# pl
# FeaturePlot(obj.mouse.IT.SH, "nCount_RNA", reduction = "pca", pt.size = 2, raster = FALSE) + NoLegend() + xlim(-30, 35) + ylim(-45, 20) + coord_equal()
# 
# DimPlot(obj.mouse.IT.SHA, reduction = "pca", group.by = "sample", pt.size = 1, shuffle = TRUE, raster = FALSE) + xlim(-30, 35) + ylim(-45, 20) + coord_equal()
# subclasses.mouse <- c("L2/3", "L4", "L5IT", "L6IT")
# Idents(obj.mouse.IT.SHA) <- "subclass"
# levels(obj.mouse.IT.SHA) <- subclasses.mouse
# pl <- DimPlot(obj.mouse.IT.SHA, reduction = "pca", cols = colors_list[subclasses.mouse], pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-30, 35) + ylim(-45, 20) + coord_equal()
# pl[[1]]$layers[[1]]$aes_params$alpha =  0.8
# pl
# FeaturePlot(obj.mouse.IT.SHA, "nCount_RNA", reduction = "pca", pt.size = 2, raster = FALSE) + NoLegend() + xlim(-30, 35) + ylim(-45, 20) + coord_equal()

# DimPlot(obj.opossum.IT, reduction = "pca", group.by = "sample", pt.size = 1, shuffle = TRUE, raster = FALSE) + xlim(-20, 20) + ylim(-18, 22) + coord_equal()
subclasses.opossum <- c("IT_A", "IT_B", "IT_C", "IT_D")
Idents(obj.opossum.IT) <- "subclass"
levels(obj.opossum.IT) <- subclasses.opossum
pl <- DimPlot(obj.opossum.IT, reduction = "pca", cols = colors_list[subclasses.opossum], pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-18, 22) + coord_equal()
ggsave("E:/Opossum_Paper/Opossum_PC.png", plot = pl, dpi = 300)
ggsave("E:/Opossum_Paper/Opossum_PC.svg", plot = pl, dpi = 300)
# FeaturePlot(obj.opossum.IT, "nCount_RNA", reduction = "pca", pt.size = 2, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-18, 22) + coord_equal()

# DimPlot(obj.opossum.IT.SH, reduction = "pca", group.by = "sample", pt.size = 1, shuffle = TRUE, raster = FALSE) + xlim(-35, 45) + ylim(-40, 40) + coord_equal()
# subclasses.opossum <- c("IT_A", "IT_B", "IT_C", "IT_D")
# Idents(obj.opossum.IT.SH) <- "subclass"
# levels(obj.opossum.IT.SH) <- subclasses.opossum
# pl <- DimPlot(obj.opossum.IT.SH, reduction = "pca", cols = colors_list[subclasses.opossum], pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-35, 45) + ylim(-40, 40) + coord_equal()
# pl[[1]]$layers[[1]]$aes_params$alpha =  0.8
# pl
# FeaturePlot(obj.opossum.IT.SH, "nCount_RNA", reduction = "pca", pt.size = 2, raster = FALSE) + NoLegend() + xlim(-35, 45) + ylim(-40, 40) + coord_equal()
# 
# DimPlot(obj.opossum.IT.SHA, reduction = "pca", group.by = "sample", pt.size = 1, shuffle = TRUE, raster = FALSE) + xlim(-35, 45) + ylim(-40, 40) + coord_equal()
# subclasses.opossum <- c("IT_A", "IT_B", "IT_C", "IT_D")
# Idents(obj.opossum.IT.SHA) <- "subclass"
# levels(obj.opossum.IT.SHA) <- subclasses.opossum
# pl <- DimPlot(obj.opossum.IT.SHA, reduction = "pca", cols = colors_list[subclasses.opossum], pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-35, 45) + ylim(-40, 40) + coord_equal()
# pl[[1]]$layers[[1]]$aes_params$alpha =  0.8
# pl
# FeaturePlot(obj.opossum.IT.SHA, "nCount_RNA", reduction = "pca", pt.size = 2, raster = FALSE) + NoLegend() + xlim(-35, 45) + ylim(-40, 40) + coord_equal()

```


```{r}

mouse.polygon <- read.csv("E:/Transcriptomics_V1/Integration/mouse_polygon.csv")
mouse.polygon <- mouse.polygon[c(1, 3, 4, 2), ]
mouse.polygon <- rbind(mouse.polygon, mouse.polygon[1, ])
subclasses.mouse <- c("L2/3", "L4", "L5IT", "L6IT")
Idents(obj.mouse.IT) <- "subclass"
levels(obj.mouse.IT) <- subclasses.mouse
pl <- DimPlot(obj.mouse.IT, reduction = "pca", cols = colors_list[subclasses.mouse], pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-16, 20) + ylim(-22, 14) + coord_equal() + geom_point(data = mouse.polygon, aes(x = X..X, y = Y), color = "black", size = 2) + 
  geom_path(data = mouse.polygon, aes(x = X..X, y = Y), color = "black", linetype = "dashed", size = 1)
ggsave("E:/Opossum_Paper/Mouse_PC.png", plot = pl, dpi = 300)
ggsave("E:/Opossum_Paper/Mouse_PC.svg", plot = pl, dpi = 300)

opossum.polygon <- read.csv("E:/Transcriptomics_V1/Integration/opossum_polygon.csv")
opossum.polygon <- rbind(opossum.polygon, opossum.polygon[1, ])
subclasses.opossum <- c("IT_A", "IT_B", "IT_C", "IT_D")
Idents(obj.opossum.IT) <- "subclass"
levels(obj.opossum.IT) <- subclasses.opossum
pl <- DimPlot(obj.opossum.IT, reduction = "pca", cols = colors_list[subclasses.opossum], pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 22) + ylim(-18, 24) + coord_equal() +     geom_point(data = opossum.polygon, aes(x = X..X, y = Y), color = "black", size = 2) + 
  geom_path(data = opossum.polygon, aes(x = X..X, y = Y), color = "black", linetype = "dashed", size = 1)
ggsave("E:/Opossum_Paper/Opossum_PC.png", plot = pl, dpi = 300)
ggsave("E:/Opossum_Paper/Opossum_PC.svg", plot = pl, dpi = 300)

```


```{r}

subclasses.opossum <- c("IT_A", "IT_B", "IT_C", "IT_D")
Idents(obj.opossum.IT) <- "subclass"
levels(obj.opossum.IT) <- subclasses.opossum
obj.opossum.IT.nA <- subset(obj.opossum.IT, idents = "IT_A", invert = TRUE)
pl <- DimPlot(obj.opossum.IT.nA, reduction = "pca", cols = c("#6a6c6d", "#6a6c6d", "#6a6c6d"), pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-18, 22) + coord_equal()
ggsave("E:/Opossum_Paper/Opossum_PC_IT_A_Gray.png", plot = pl, dpi = 300)
ggsave("E:/Opossum_Paper/Opossum_PC_IT_A_Gray.svg", plot = pl, dpi = 300)

subclasses.opossum <- c("IT_A", "IT_B", "IT_C", "IT_D")
Idents(obj.opossum.IT) <- "subclass"
levels(obj.opossum.IT) <- subclasses.opossum
obj.opossum.IT.A <- subset(obj.opossum.IT, idents = "IT_A")
pl <- DimPlot(obj.opossum.IT.A, reduction = "pca", cols = colors_list[["IT_A"]], pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-18, 22) + coord_equal()
ggsave("E:/Opossum_Paper/Opossum_PC_IT_A.png", plot = pl, dpi = 300)
ggsave("E:/Opossum_Paper/Opossum_PC_IT_A.svg", plot = pl, dpi = 300)

```


```{r}

subclasses.opossum <- c("IT_A", "IT_B", "IT_C", "IT_D")
Idents(obj.opossum.IT) <- "subclass"
levels(obj.opossum.IT) <- subclasses.opossum
obj.opossum.IT.nB <- subset(obj.opossum.IT, idents = "IT_B", invert = TRUE)
pl <- DimPlot(obj.opossum.IT.nB, reduction = "pca", cols = c("#6a6c6d", "#6a6c6d", "#6a6c6d"), pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-18, 22) + coord_equal()
ggsave("E:/Opossum_Paper/Opossum_PC_IT_B_Gray.png", plot = pl, dpi = 300)
ggsave("E:/Opossum_Paper/Opossum_PC_IT_B_Gray.svg", plot = pl, dpi = 300)

subclasses.opossum <- c("IT_A", "IT_B", "IT_C", "IT_D")
Idents(obj.opossum.IT) <- "subclass"
levels(obj.opossum.IT) <- subclasses.opossum
obj.opossum.IT.B <- subset(obj.opossum.IT, idents = "IT_B")
pl <- DimPlot(obj.opossum.IT.B, reduction = "pca", cols = colors_list[["IT_B"]], pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-18, 22) + coord_equal()
ggsave("E:/Opossum_Paper/Opossum_PC_IT_B.png", plot = pl, dpi = 300)
ggsave("E:/Opossum_Paper/Opossum_PC_IT_B.svg", plot = pl, dpi = 300)

```


```{r}

subclasses.opossum <- c("IT_A", "IT_B", "IT_C", "IT_D")
Idents(obj.opossum.IT) <- "subclass"
levels(obj.opossum.IT) <- subclasses.opossum
obj.opossum.IT.nC <- subset(obj.opossum.IT, idents = "IT_C", invert = TRUE)
pl <- DimPlot(obj.opossum.IT.nC, reduction = "pca", cols = c("#6a6c6d", "#6a6c6d", "#6a6c6d"), pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-18, 22) + coord_equal()
ggsave("E:/Opossum_Paper/Opossum_PC_IT_C_Gray.png", plot = pl, dpi = 300)
ggsave("E:/Opossum_Paper/Opossum_PC_IT_C_Gray.svg", plot = pl, dpi = 300)

subclasses.opossum <- c("IT_A", "IT_B", "IT_C", "IT_D")
Idents(obj.opossum.IT) <- "subclass"
levels(obj.opossum.IT) <- subclasses.opossum
obj.opossum.IT.C <- subset(obj.opossum.IT, idents = "IT_C")
pl <- DimPlot(obj.opossum.IT.C, reduction = "pca", cols = colors_list[["IT_C"]], pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-18, 22) + coord_equal()
ggsave("E:/Opossum_Paper/Opossum_PC_IT_C.png", plot = pl, dpi = 300)
ggsave("E:/Opossum_Paper/Opossum_PC_IT_C.svg", plot = pl, dpi = 300)

```


```{r}

subclasses.opossum <- c("IT_A", "IT_B", "IT_C", "IT_D")
Idents(obj.opossum.IT) <- "subclass"
levels(obj.opossum.IT) <- subclasses.opossum
obj.opossum.IT.nD <- subset(obj.opossum.IT, idents = "IT_D", invert = TRUE)
pl <- DimPlot(obj.opossum.IT.nD, reduction = "pca", cols = c("#6a6c6d", "#6a6c6d", "#6a6c6d"), pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-18, 22) + coord_equal()
ggsave("E:/Opossum_Paper/Opossum_PC_IT_D_Gray.png", plot = pl, dpi = 300)
ggsave("E:/Opossum_Paper/Opossum_PC_IT_D_Gray.svg", plot = pl, dpi = 300)

subclasses.opossum <- c("IT_A", "IT_B", "IT_C", "IT_D")
Idents(obj.opossum.IT) <- "subclass"
levels(obj.opossum.IT) <- subclasses.opossum
obj.opossum.IT.D <- subset(obj.opossum.IT, idents = "IT_D")
pl <- DimPlot(obj.opossum.IT.D, reduction = "pca", cols = colors_list[["IT_D"]], pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-20, 20) + ylim(-18, 22) + coord_equal()
ggsave("E:/Opossum_Paper/Opossum_PC_IT_D.png", plot = pl, dpi = 300)
ggsave("E:/Opossum_Paper/Opossum_PC_IT_D.svg", plot = pl, dpi = 300)

```

MAP THESE SHUFFLED GROUPS?

```{r}

obj.m.opossum <- readRDS("E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/obj_m_opossum.rds")
obj.m.opossum.IT <- obj.m.opossum[, colnames(obj.m.opossum) %in% colnames(obj.opossum.IT)]
obj.opossum.IT.MP <- obj.opossum.IT[, colnames(obj.opossum.IT) %in% colnames(obj.m.opossum.IT)]
obj.opossum.IT.MP <- obj.opossum.IT.MP[, match(colnames(obj.opossum.IT.MP), colnames(obj.m.opossum.IT))]
obj.opossum.IT.MP$predicted.subclass.score <- obj.m.opossum.IT$predicted.subclass.score
obj.opossum.IT.MP$predicted.subclass <- obj.m.opossum.IT$predicted.subclass

DimPlot(obj.opossum.IT.MP, reduction = "pca", group.by = "predicted.subclass", pt.size = 1, shuffle = TRUE, raster = FALSE) + xlim(-35, 45) + ylim(-40, 40) + coord_equal()
FeaturePlot(obj.opossum.IT.MP, "predicted.subclass.score", reduction = "pca", pt.size = 1, raster = FALSE) + NoLegend() + xlim(-35, 45) + ylim(-40, 40) + coord_equal()

```


```{r}

objs.m.IT <- MapObjects(obj.opossum.IT.SS, obj.mouse.IT, c("subclass", "type"), assay = "SCT")

DimPlot(objs.m.IT[[1]], reduction = "pca", group.by = "predicted.subclass", pt.size = 1, shuffle = TRUE, raster = FALSE) + xlim(-35, 45) + ylim(-40, 40) + coord_equal()
FeaturePlot(objs.m.IT[[1]], "predicted.subclass.score", reduction = "pca", pt.size = 1, raster = FALSE) + NoLegend() + xlim(-35, 45) + ylim(-40, 40) + coord_equal()
FeaturePlot(objs.m.IT[[1]], "Rorb", reduction = "pca", pt.size = 1, raster = FALSE) + NoLegend() + xlim(-35, 45) + ylim(-40, 40) + coord_equal()

```


```{r}

shared.HVFs <- SelectIntegrationFeatures(object.list = c(obj.mouse.IT, obj.opossum.IT), nfeatures = 3000)

obj.mouse.IT.SVF <- SCTransform(obj.mouse.IT, vst.flavor = "v2", residual.features = shared.HVFs, return.only.var.genes = FALSE, verbose = FALSE) %>%
                    RunPCA(npcs = 30, verbose = FALSE)

obj.opossum.IT.SVF <- SCTransform(obj.opossum.IT, vst.flavor = "v2", residual.features = shared.HVFs, return.only.var.genes = FALSE, verbose = FALSE) %>%
                      RunPCA(npcs = 30, verbose = FALSE)

```


```{r}

source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_functions.R")

DimPlot(obj.mouse.IT.SVF, reduction = "pca", group.by = "sample", pt.size = 1, shuffle = TRUE, raster = FALSE) + xlim(-30, 35) + ylim(-45, 20) + coord_equal()
subclasses.mouse <- c("L2/3", "L4", "L5IT", "L6IT")
Idents(obj.mouse.IT.SVF) <- "subclass"
levels(obj.mouse.IT.SVF) <- subclasses.mouse
pl <- DimPlot(obj.mouse.IT.SVF, reduction = "pca", cols = colors_list[subclasses.mouse], pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-30, 25) + ylim(-20, 35) + coord_equal()
pl[[1]]$layers[[1]]$aes_params$alpha =  0.8
pl
FeaturePlot(obj.mouse.IT.SVF, "nCount_RNA", reduction = "pca", pt.size = 2, raster = FALSE) + NoLegend() + xlim(-30, 35) + ylim(-45, 20) + coord_equal()

DimPlot(obj.opossum.IT.SVF, reduction = "pca", group.by = "sample", pt.size = 1, shuffle = TRUE, raster = FALSE) + xlim(-35, 45) + ylim(-40, 40) + coord_equal()
subclasses.opossum <- c("IT_A", "IT_B", "IT_C", "IT_D")
Idents(obj.opossum.IT.SVF) <- "subclass"
levels(obj.opossum.IT.SVF) <- subclasses.opossum
pl <- DimPlot(obj.opossum.IT.SVF, reduction = "pca", cols = colors_list[subclasses.opossum], pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-35, 45) + ylim(-40, 40) + coord_equal()
pl[[1]]$layers[[1]]$aes_params$alpha =  0.8
pl
FeaturePlot(obj.opossum.IT.SVF, "nCount_RNA", reduction = "pca", pt.size = 2, raster = FALSE) + NoLegend() + xlim(-35, 45) + ylim(-40, 40) + coord_equal()

```


```{r}

obj.opossum.IT.SS <- obj.opossum.IT[, sample(colnames(obj.opossum.IT), length(colnames(obj.mouse.IT)))]
obj.mouse.IT$species <- "Mouse"
obj.combined.IT <- merge(obj.mouse.IT, obj.opossum.IT.SS)
obj.combined.IT <- SCTransform(obj.combined.IT, vst.flavor = "v2", residual.features = shared.HVFs, return.only.var.genes = FALSE, verbose = FALSE) %>%
                   RunPCA(npcs = 30, verbose = FALSE)

```


```{r}

DimPlot(obj.combined.IT, reduction = "pca", dims = c(2, 3), group.by = "species", pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-35, 45) + ylim(-40, 40) + coord_equal()
DimPlot(obj.combined.IT, reduction = "pca", dims = c(2, 3), split.by = "species", group.by = "subclass", pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-35, 45) + ylim(-40, 40) + coord_equal()
FeaturePlot(obj.combined.IT, "nCount_RNA", reduction = "pca", dims = c(2, 3), pt.size = 2, raster = FALSE) + NoLegend() + xlim(-35, 45) + ylim(-40, 40) + coord_equal()

```


```{r}

objs <- list(obj.opossum.IT, obj.mouse.IT)
obj.integrated.IT <- IntegrateObjects(objs[[1]], objs[[2]], resolutions = c(1, 2), nfeatures = 3000, subsample = TRUE)
objs.i.IT <- SplitObject(obj.integrated.IT, split.by = "species")
objs.im.IT <- MapObjects(objs.i.IT[["Opossum"]], objs.i.IT[["Mouse"]], c("subclass", "type"), assay = "integrated")

```


```{r}

DimPlot(objs.im.IT[[1]], reduction = "pca", group.by = "subclass", pt.size = 1, shuffle = TRUE, raster = FALSE) + xlim(-35, 45) + ylim(-40, 40) + coord_equal()
DimPlot(objs.im.IT[[1]], reduction = "pca", group.by = "predicted.subclass", pt.size = 1, shuffle = TRUE, raster = FALSE) + xlim(-35, 45) + ylim(-40, 40) + coord_equal()
FeaturePlot(objs.im.IT[[1]], "predicted.subclass.score", reduction = "pca", pt.size = 1, raster = FALSE) + NoLegend() + xlim(-35, 45) + ylim(-40, 40) + coord_equal()

```


```{r}

obj.im.opossum.IT <- objs.im.IT[[1]]
obj.im.opossum.IT.SS <- obj.im.opossum.IT[, colnames(obj.im.opossum.IT) %in% colnames(obj.opossum.IT)]
obj.opossum.IT.IMP <- obj.opossum.IT[, colnames(obj.opossum.IT) %in% colnames(obj.im.opossum.IT)]
obj.opossum.IT.IMP <- obj.opossum.IT.IMP[, match(colnames(obj.opossum.IT.IMP), colnames(obj.im.opossum.IT))]
obj.opossum.IT.IMP$predicted.subclass.score <- obj.im.opossum.IT$predicted.subclass.score
obj.opossum.IT.IMP$predicted.subclass <- obj.im.opossum.IT$predicted.subclass

DimPlot(obj.opossum.IT.IMP, reduction = "pca", group.by = "predicted.subclass", pt.size = 1, label = TRUE, shuffle = TRUE, raster = FALSE) + NoLegend() + xlim(-35, 45) + ylim(-40, 40) + coord_equal()
FeaturePlot(obj.opossum.IT.IMP, "predicted.subclass.score", reduction = "pca", pt.size = 1, raster = FALSE) + NoLegend() + xlim(-35, 45) + ylim(-40, 40) + coord_equal()

```


GRADIENT GENES


```{r}

Idents(obj.opossum.IT) <- "subclass"
markers.opossum.IT <- FindAllMarkers(obj.opossum.IT, assay = "SCT", logfc.threshold = 0.8, only.pos = TRUE)

```


```{r}

gene_list <- rownames(markers.opossum.IT)

# Subset the Seurat object to include only the genes of interest
DefaultAssay(obj.opossum.IT) <- "RNA"
seurat_subset <- subset(obj.opossum.IT, features = gene_list)

data <- GetAssayData(object = seurat_subset, slot = "data")
celldata <- as.data.frame(seurat_subset@meta.data)
genedata <- as.data.frame(x = row.names(data), row.names = row.names(data))
colnames(genedata) <- "gene_short_name"
cds <- new_cell_data_set(data, cell_metadata = celldata, gene_metadata = genedata)
cds <- estimate_size_factors(cds)

# Learn the graph and order cells by pseudotime on the subset CDS
cds <- preprocess_cds(cds, method = "PCA")
cds <- reduce_dimension(cds, reduction_method = "UMAP")
cds <- cluster_cells(cds)
cds <- learn_graph(cds)
cds <- order_cells(cds)

# Extract the pseudotime information from the subset CDS
pseudotime_data <- pseudotime(cds)

# Create a data frame with pseudotime and cell names
pseudotime_df <- data.frame(cell = colnames(cds), pseudotime = pseudotime_data)
# Order the data frame by pseudotime
pseudotime_df <- pseudotime_df[order(pseudotime_df$pseudotime), ]
# Extract ordered cell names
ordered_cells <- pseudotime_df$cell

# Extract expression matrix for the specified genes
# sampled_cells <- ordered_cells[ordered_cells %in% sample(ordered_cells, 2000, replace = FALSE, prob = NULL)]
expression_matrix <- as.matrix(exprs(cds[gene_list[gene_list %in% rownames(cds)], ordered_cells]))

breaks <- seq(-2, 2, length.out = 101)
colors <- colorRampPalette(c("blue", "white", "red"))(100)

# Generate the heatmap
pheatmap(expression_matrix, cluster_rows = FALSE, cluster_cols = FALSE,
         show_rownames = FALSE, show_colnames = FALSE,
         scale = "column", 
         color = colors,
         breaks = breaks,
         main = "Gene Expression Heatmap Ordered by Pseudotime")

```

