---
title: "R Notebook"
output: html_notebook
---


```{r}

library(Seurat)
library(SeuratDisk)
library(SeuratWrappers)
library(monocle3)
library(pheatmap)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(patchwork)
library(dplyr)
library(data.table)
library(clustree)
library(reshape2)
library(tidyr)
library(gridExtra)
library(stringr)
library(plyr)
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_integration_functions.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/xgboost_train.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/plottingFxns.R")

obj.opossum <- readRDS(paste0("E:/Transcriptomics_V1/Opossum/seurat/opossum_v1_glutamatergic_processed.rds"))
obj.mouse.P38 <- readRDS(paste0("E:/Transcriptomics_V1/Mouse/seurat/mouse_v1_P38_glutamatergic_processed.rds"))

```


```{r}

Idents(obj.opossum) <- "subclass"
obj.opossum.PT <- subset(obj.opossum, idents = c("L5PT", "L5NP", "L6CT", "L6b"))

Idents(obj.mouse.P38) <- "subclass"
obj.mouse.PT <- subset(obj.mouse.P38, idents = c("L5PT", "L5NP", "L6CT", "L6b"))

```


```{r}

obj.opossum.PT <- ClusterSCT(obj.opossum.PT, resolutions = c(1))
obj.mouse.PT <- ClusterSCT(obj.mouse.PT, resolutions = c(1))

```


```{r}

DimPlot(obj.opossum.PT, reduction = "umap", group.by = "sample", label = FALSE, raster = FALSE, shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.opossum.PT, reduction = "umap", group.by = "subclass", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.opossum.PT, reduction = "umap", group.by = "type", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
p <- DimPlot(obj.opossum.PT, reduction = "umap", group.by = "subclass", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
# ggsave("E:/Opossum_Paper/Figure 2/Opossum_V1_PT_UMAP_Subclass_FullSpace.png", plot = p, dpi = 300)
# ggsave("E:/Opossum_Paper/Figure 2/Opossum_V1_PT_UMAP_Subclass_FullSpace.svg", plot = p, dpi = 300)

DimPlot(obj.mouse.PT, reduction = "umap", group.by = "sample", label = FALSE, raster = FALSE, shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.PT, reduction = "umap", group.by = "subclass", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.PT, reduction = "umap", group.by = "type", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
p <- DimPlot(obj.mouse.PT, reduction = "umap", group.by = "subclass", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
# ggsave("E:/Opossum_Paper/Figure 2/Mouse-P38_V1_PT_UMAP_Subclass_FullSpace.png", plot = p, dpi = 300)
# ggsave("E:/Opossum_Paper/Figure 2/Mouse-P38_V1_PT_UMAP_Subclass_FullSpace.svg", plot = p, dpi = 300)

```


```{r}

opossum.vfs <- VariableFeatures(obj.opossum.PT)
mouse.vfs <- VariableFeatures(obj.mouse.PT)

poss.shared.vfs <- intersect(rownames(obj.opossum.PT), mouse.vfs)
shared.vfs <- intersect(opossum.vfs, mouse.vfs)
orthologues <- intersect(rownames(obj.opossum.PT), rownames(obj.mouse.PT))

```


```{r}

# cluster objects in shared VF space
obj.opossum.PT.SVF <- obj.opossum.PT
obj.mouse.PT.SVF <- obj.mouse.PT

obj.opossum.PT.SVF <- SCTransform(obj.opossum.PT.SVF, vst.flavor = "v2", residual.features = shared.vfs, return.only.var.genes = FALSE, verbose = FALSE) %>%
                      RunPCA(npcs = 30, verbose = FALSE) %>%
                      FindNeighbors(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
                      RunUMAP(reduction = "pca", dims = 1:30, verbose = FALSE)

obj.mouse.PT.SVF <- SCTransform(obj.mouse.PT.SVF, vst.flavor = "v2", residual.features = shared.vfs, return.only.var.genes = FALSE, verbose = FALSE) %>%
                    RunPCA(npcs = 30, verbose = FALSE) %>%
                    FindNeighbors(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
                    RunUMAP(reduction = "pca", dims = 1:30, verbose = FALSE)

```


```{r}

DimPlot(obj.opossum.PT.SVF, reduction = "umap", group.by = "sample", label = FALSE, raster = FALSE, shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.opossum.PT.SVF, reduction = "umap", group.by = "subclass", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.opossum.PT.SVF, reduction = "umap", group.by = "type", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
p <- DimPlot(obj.opossum.PT.SVF, reduction = "umap", group.by = "subclass", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
ggsave("E:/Opossum_Paper/Figure 2/Opossum_V1_PT_UMAP_Subclass_SharedVFSpace.png", plot = p, dpi = 300)
ggsave("E:/Opossum_Paper/Figure 2/Opossum_V1_PT_UMAP_Subclass_SharedVFSpace.svg", plot = p, dpi = 300)

DimPlot(obj.mouse.PT.SVF, reduction = "umap", group.by = "sample", label = FALSE, raster = FALSE, shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.PT.SVF, reduction = "umap", group.by = "subclass", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.PT.SVF, reduction = "umap", group.by = "type", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
p <- DimPlot(obj.mouse.PT.SVF, reduction = "umap", group.by = "subclass", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
ggsave("E:/Opossum_Paper/Figure 2/Mouse-P38_V1_PT_UMAP_Subclass_SharedVFSpace.png", plot = p, dpi = 300)
ggsave("E:/Opossum_Paper/Figure 2/Mouse-P38_V1_PT_UMAP_Subclass_SharedVFSpace.svg", plot = p, dpi = 300)

```


```{r}

# cluster objects in shared VF space
obj.opossum.PT.PVF <- obj.opossum.PT
obj.mouse.PT.PVF <- obj.mouse.PT

obj.opossum.PT.PVF <- SCTransform(obj.opossum.PT.SVF, vst.flavor = "v2", residual.features = poss.shared.vfs, return.only.var.genes = FALSE, verbose = FALSE) %>%
                      RunPCA(npcs = 30, verbose = FALSE) %>%
                      FindNeighbors(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
                      RunUMAP(reduction = "pca", dims = 1:30, verbose = FALSE)

obj.mouse.PT.PVF <- SCTransform(obj.mouse.PT.SVF, vst.flavor = "v2", residual.features = poss.shared.vfs, return.only.var.genes = FALSE, verbose = FALSE) %>%
                    RunPCA(npcs = 30, verbose = FALSE) %>%
                    FindNeighbors(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
                    RunUMAP(reduction = "pca", dims = 1:30, verbose = FALSE)

```


```{r}

DimPlot(obj.opossum.PT.PVF, reduction = "umap", group.by = "sample", label = FALSE, raster = FALSE, shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.opossum.PT.PVF, reduction = "umap", group.by = "subclass", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.opossum.PT.PVF, reduction = "umap", group.by = "type", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
p <- DimPlot(obj.opossum.PT.PVF, reduction = "umap", group.by = "subclass", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
ggsave("E:/Opossum_Paper/Figure 2/Opossum_V1_PT_UMAP_Subclass_PossSharedVFSpace.png", plot = p, dpi = 300)
ggsave("E:/Opossum_Paper/Figure 2/Opossum_V1_PT_UMAP_Subclass_PossSharedVFSpace.svg", plot = p, dpi = 300)

DimPlot(obj.mouse.PT.PVF, reduction = "umap", group.by = "sample", label = FALSE, raster = FALSE, shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.PT.PVF, reduction = "umap", group.by = "subclass", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.PT.PVF, reduction = "umap", group.by = "type", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
p <- DimPlot(obj.mouse.PT.PVF, reduction = "umap", group.by = "subclass", label = TRUE, raster = FALSE, shuffle = TRUE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
ggsave("E:/Opossum_Paper/Figure 2/Mouse-P38_V1_PT_UMAP_Subclass_PossSharedVFSpace.png", plot = p, dpi = 300)
ggsave("E:/Opossum_Paper/Figure 2/Mouse-P38_V1_PT_UMAP_Subclass_PossSharedVFSpace.svg", plot = p, dpi = 300)

```


```{r}

Idents(obj.mouse.PT) <- "subclass"
DoHeatmap(obj.mouse.PT, features = c("Ccbe1", "Mdga1", "Stard8", "Cux2", 
                                     "Whrn", "Rorb",
                                     "Deptor", "Foxo1", "Ptprm", 
                                     "Zfp804b", "Cdh9"), slot = "data", disp.min = 0, disp.max = 3) + scale_fill_gradientn(colors = c("white", "red"))

Idents(obj.opossum.PT) <- "subclass"
levels(obj.opossum.PT) <- c("PT_A", "PT_B", "PT_C", "PT_D", "PT_E")
DoHeatmap(obj.opossum.PT, features = c("Ccbe1", "Mdga1", "Stard8", "Cux2", 
                                     "Whrn", "Rorb",
                                     "Deptor", "Foxo1", "Ptprm", 
                                     "Zfp804b", "Cdh9"), slot = "data", disp.min = 0, disp.max = 3) + scale_fill_gradientn(colors = c("white", "red"))

```


```{r}

obj.mouse.PT$species <- "Mouse"
objs.PT <- list(obj.opossum.PT, obj.mouse.PT)
obj.integrated.PT <- IntegrateObjects(objs.PT[[1]], objs.PT[[2]], resolutions = c(1, 2), nfeatures = 3000, subsample = TRUE)
objs.i.PT <- SplitObject(obj.integrated.PT, split.by = "species")
objs.m.PT <- MapObjects(objs.i.PT[[1]], objs.i.PT[[2]], c("subclass", "type"), assay = "integrated")

```


```{r}

PlotMapping(objs.m.PT, ident.order = c("L5PT", "L5NP", "L6CT", "L6b"))

```


```{r, fig.width=15, fig.height=6}

sbcl_conf_plots <- PlotSubclassCrossConfusionMatrices(objs.i[[1]], objs.i[[2]], 
                                                      "Opossum", "Mouse", 
                                                      assay = "integrated",
                                                      c("L5PT", "L5NP", "L6CT", "L6b"), n_iters = 5, all.genes = FALSE, upsample = TRUE)

```


```{r}

print(sbcl_conf_plots[[1]])
print(sbcl_conf_plots[[2]])

```


```{r}

subclass.markers.opossum.glutamatergic <- readRDS("E:/Transcriptomics_V1/Opossum/seurat/marker_genes/Glutamatergic/markerdict_subclass.rds")
subclass.markers.mouse.glutamatergic.P38 <- readRDS("E:/Transcriptomics_V1/Mouse/seurat/marker_genes/Glutamatergic/P38/markerdict_subclass.rds")

subclasses <- c("L5PT", "L5NP", "L6CT", "L6b")

# pre-integration subclass comparison (DE genes)
for (pc in c(T, F)) {
  p <- PlotSubclassDEIntersection(subclass.markers.mouse.glutamatergic.P38, subclass.markers.opossum.glutamatergic, 
                                  rownames(objs.i[[1]]), rownames(objs.i[[2]]),
                                  "Mouse", "Opossum",
                                  subclasses, 0.2, "E:/Transcriptomics_V1/Integration/Opossum_Mouse-P38/subclass_markers/Glutamatergic/", percentage = pc)
  print(p)
}

```


```{r}

Idents(obj.mouse.PT) <- "subclass"
markers.mouse.PT <- FindAllMarkers(obj.mouse.PT, only.pos = TRUE, logfc.threshold = 0.4)
Idents(obj.opossum.PT) <- "subclass"
markers.opossum.PT <- FindAllMarkers(obj.opossum.PT, only.pos = TRUE, logfc.threshold = 0.4)

```


```{r}

plotGeneFractions(markers.mouse.PT, orthologues)
markers.opossum.PT$cluster <- factor(markers.opossum.PT$cluster, levels = c("PT_A", "PT_B", "PT_C", "PT_D", "PT_E"))
plotGeneFractions(markers.opossum.PT, orthologues)

```


```{r}

Idents(obj.mouse.PT) <- "type"
obj.mouse.L23 <- subset(obj.mouse.PT, idents = c("L2/3_A", "L2/3_B", "L2/3_C"))
markers.mouse.L23 <- FindAllMarkers(obj.mouse.L23, only.pos = TRUE, logfc.threshold = 0.4)
markers.mouse.L23$cluster <- factor(markers.mouse.L23$cluster, levels = c("L2/3_A", "L2/3_B", "L2/3_C"))
markers.mouse.L23.sorted <- markers.mouse.L23 %>%
                             arrange(cluster, desc(avg_log2FC))
gene_list <- markers.mouse.L23.sorted$gene

```


```{r}

# Subset the Seurat object to include only the genes of interest
DefaultAssay(obj.mouse.L23) <- "RNA"
seurat_subset <- subset(obj.mouse.L23, features = gene_list)

data <- GetAssayData(object = seurat_subset, slot = "counts")
celldata <- as.data.frame(seurat_subset@meta.data)
genedata <- as.data.frame(x = row.names(data), row.names = row.names(data))
colnames(genedata) <- "gene_short_name"
cds <- new_cell_data_set(data, cell_metadata = celldata, gene_metadata = genedata)
cds <- estimate_size_factors(cds)

# Learn the graph and order cells by pseudotime on the subset CDS
cds <- preprocess_cds(cds, method = "PCA")
cds <- reduce_dimension(cds, reduction_method = "UMAP")
cds <- cluster_cells(cds)
cds <- learn_graph(cds)
cds <- order_cells(cds)

# Extract the pseudotime information from the subset CDS
pseudotime_data <- pseudotime(cds)

# Create a data frame with pseudotime and cell names
pseudotime_df <- data.frame(cell = colnames(cds), pseudotime = pseudotime_data)
# Order the data frame by pseudotime
pseudotime_df <- pseudotime_df[order(pseudotime_df$pseudotime), ]
# Extract ordered cell names
ordered_cells <- pseudotime_df$cell

# Extract expression matrix for the specified genes
# sampled_cells <- ordered_cells[ordered_cells %in% sample(ordered_cells, 2000, replace = FALSE, prob = NULL)]
expression_matrix <- as.matrix(exprs(cds[gene_list, ordered_cells]))

breaks <- seq(-5, 5, length.out = 101)
colors <- colorRampPalette(c("blue", "white", "red"))(100)

# Generate the heatmap
pheatmap(expression_matrix, cluster_rows = FALSE, cluster_cols = FALSE,
         show_rownames = FALSE, show_colnames = FALSE,
         scale = "row", 
         color = colors,
         breaks = breaks,
         main = "Gene Expression Heatmap Ordered by Pseudotime")

```




















