---
title: "Integrate Retina Mouse Opossum"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(cowplot)
library(dplyr)
library(SeuratDisk)
library(lisi)

obj.opossum <- readRDS("E:/Transcriptomics_Retina/Opossum/opossum_retina_rgc.rds")
obj.opossum <- obj.opossum.rgc
obj.opossum$species <- "Opossum"

obj.mouse <- readRDS("E:/Transcriptomics_Retina/Mouse/mouse_retina_rgc.rds")
obj.mouse <- obj.mouse.rgc
obj.mouse$species <- "Mouse"

obj.mouse <- obj.mouse[, sample(colnames(obj.mouse), size = ncol(obj.opossum), replace = FALSE)]

```


```{r}

common.features <- intersect(rownames(obj.mouse), rownames(obj.opossum))
obj.combined <- merge(obj.mouse[common.features,], y = obj.opossum[common.features,])
# obj.combined[["RNA"]] <- split(obj.combined[["RNA"]], f = obj.combined$species)

```


```{r}

obj.combined <- NormalizeData(obj.combined)
obj.combined <- FindVariableFeatures(obj.combined)
obj.combined <- ScaleData(obj.combined)
obj.combined <- RunPCA(obj.combined)

obj.combined <- FindNeighbors(obj.combined, dims = 1:30, reduction = "pca")
obj.combined <- FindClusters(obj.combined, resolution = 1, algorithm = 4, method = "igraph", cluster.name = "clusters.unintegrated")

obj.combined <- RunUMAP(obj.combined, dims = 1:30, reduction = "pca", method="umap-learn", reduction.name = "umap.unintegrated")

```


```{r}

DimPlot(obj.combined, label = FALSE, split.by = "species", group.by = "orig.file") + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.combined, label = TRUE, split.by = "species", group.by = "cell_class") + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.combined, label = TRUE, split.by = "species", group.by = "type") + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
# DimPlot(obj.list[["Mouse"]], label = TRUE, group.by = "type") + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```



```{r}

obj.combined <- IntegrateLayers(
      object = obj.combined, 
      method = CCAIntegration, 
      orig.reduction = "pca", 
      new.reduction = "integrated.cca",
      verbose = FALSE
                               )

```


```{r}

obj.combined <- FindNeighbors(obj.combined, reduction = "integrated.cca", dims = 1:30)
obj.combined <- FindClusters(obj.combined, resolution = 2, cluster.name = "cca_clusters")

obj.combined <- RunUMAP(obj.combined, reduction = "integrated.cca", dims = 1:30, reduction.name = "umap.cca")

```


```{r}

DimPlot(obj.combined, reduction = "umap.cca", group.by = "species", raster = FALSE, shuffle = TRUE, cols = c("#909090", "#c692b8")) + xlim(-16, 14) + ylim(-14, 16) + coord_equal()
DimPlot(obj.combined, reduction = "umap.cca", split.by = "species", group.by = "orig.file", raster = FALSE, shuffle = TRUE) + xlim(-16, 14) + ylim(-14, 16) + coord_equal()
DimPlot(obj.combined, reduction = "umap.cca", split.by = "species", group.by = "type", raster = FALSE, shuffle = TRUE, label = TRUE) + xlim(-16, 14) + ylim(-14, 16) + coord_equal() + NoLegend()
# DimPlot(obj.combined, reduction = "umap.cca", group.by = "subclass", split.by = "species", label = FALSE, raster = FALSE, order = rev(c("Pvalb", "Sst", "Vip", "Lamp5", "Sncg")), cols = c("#589B43", "#9B53A0",  "#29589A", "#EF3C46", "#EfAE70")) + NoLegend() + xlim(-16, 14) + ylim(-14, 16) + coord_equal()

# ggsave(file="G:/Shared drives/Grants/2024 Gorzek NRSA/_FIGURES/Figure 2/UMAP_Mixed.svg", plot=mixed_plot, dpi=500)
# ggsave(file="G:/Shared drives/Grants/2024 Gorzek NRSA/_FIGURES/Figure 2/UMAP_Split.svg", plot=split_plot, dpi=500)

```


```{r}

obj.combined.join <- JoinLayers(obj.combined)

```


```{r}

obj.list <- SplitObject(obj.combined.join, split.by = "species")

```


```{r}

# Source scripts with functions
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/xgboost_train.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/plottingFxns.R")

Idents(obj.list[["Opossum"]]) <- "type"
Idents(obj.list[["Mouse"]]) <- "type"

# Define a wrapper function to train model on common highly variable genes
TrainXGBoost = function(train, test, train.clusters = "", test.clusters = "", features = c()){
  
  Idents(train) = train.clusters
  Idents(test) = test.clusters
  
  AC_model <- TrainModel(train, training_genes = features)
  
  return(AC_model)
}

# Train model
MO_model <- TrainXGBoost(obj.list[["Mouse"]], 
                         obj.list[["Opossum"]], 
                         train.clusters = "type", 
                         test.clusters = "type", 
                         features = common.features)

```

```{r}

source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/xgboost_train.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/plottingFxns.R")

Idents(obj.list[["Opossum"]]) <- "type"
Idents(obj.list[["Mouse"]]) <- "type"
confusion_matrix <- BuildConfusionMatrix(obj.list[["Opossum"]], obj.list[["Mouse"]], model = MO_model)
plotConfusionMatrix(confusion_matrix, plot.return = TRUE, stagger.threshold = 15)

```











