---
title: "Integrate Retina Mouse Opossum"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(cowplot)
library(dplyr)
library(SeuratDisk)
library(lisi)

obj.opossum <- readRDS("E:/Transcriptomics_Retina/Opossum/opossum_retina_rgc_integrated.rds")
obj.opossum$species <- "Opossum"

obj.mouse <- readRDS("E:/Transcriptomics_Retina/Mouse/mouse_retina_rgc_integrated.rds")
obj.mouse$species <- "Mouse"

obj.mouse <- obj.mouse[, sample(colnames(obj.mouse), size = ncol(obj.opossum), replace = FALSE)]

```


```{r}

common.features <- intersect(rownames(obj.mouse), rownames(obj.opossum))
obj.combined <- merge(obj.mouse[common.features,], y = obj.opossum[common.features,])
obj.combined <- merge(obj.mouse, y = obj.opossum)
obj.list <- SplitObject(obj.combined, split.by = "species")

```


```{r}

obj.list[["Mouse"]] <- SCTransform(obj.list[["Mouse"]], assay = "integrated", vst.flavor = "v2", return.only.var.genes = FALSE) %>%
                       RunPCA(npcs = 30, verbose = FALSE) %>%
                       RunUMAP(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
                       FindNeighbors(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
                       FindClusters(resolution = 1, algorithm = 4, method = "igraph")

DimPlot(obj.list[["Mouse"]], label = FALSE, shuffle = TRUE, group.by = "orig.file") + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.list[["Mouse"]], label = TRUE, group.by = "type") + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

obj.list[["Opossum"]] <- SCTransform(obj.list[["Opossum"]], vst.flavor = "v2", verbose = FALSE) %>%
                         RunPCA(npcs = 30, verbose = FALSE) %>%
                         RunUMAP(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
                         FindNeighbors(reduction = "pca", dims = 1:30, verbose = FALSE) %>%
                         FindClusters(resolution = 1, algorithm = 4, method = "igraph")

DimPlot(obj.list[["Opossum"]], label = FALSE, shuffle = TRUE, group.by = "orig.file") + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.list[["Opossum"]], label = TRUE, group.by = "type") + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

features <- SelectIntegrationFeatures(object.list = obj.list, assay = c("integrated", "integrated"), nfeatures = 3000)
obj.list <- PrepSCTIntegration(object.list = obj.list, assay = "SCT", anchor.features = features)
anchors <- FindIntegrationAnchors(object.list = obj.list, normalization.method = "SCT", anchor.features = features)
obj.combined <- IntegrateData(anchorset = anchors, normalization.method = "SCT")

```


```{r}

obj.combined <- RunPCA(obj.combined)
obj.combined <- FindNeighbors(obj.combined, reduction = "pca", dims = 1:30)
obj.combined <- FindClusters(obj.combined, resolution = 1, algorithm = 4, method = "igraph")
obj.combined <- RunUMAP(obj.combined, reduction = "pca", dims = 1:30)

```


```{r}

DimPlot(obj.combined, reduction = "umap", group.by = "species", raster = FALSE, shuffle = TRUE, cols = c("#909090", "#c692b8")) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.combined, reduction = "umap", split.by = "species", group.by = "orig.file", raster = FALSE, shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.combined, reduction = "umap", split.by = "species", group.by = "type", raster = FALSE, shuffle = TRUE, label = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal() + NoLegend()

```


```{r}

# obj.combined.join <- JoinLayers(obj.combined)

```


```{r}

obj.combined.list <- SplitObject(obj.combined, split.by = "species")

```


```{r}

# Source scripts with functions
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/xgboost_train.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/plottingFxns.R")

Idents(obj.combined.list[["Opossum"]]) <- "type"
Idents(obj.combined.list[["Mouse"]]) <- "type"

# Define a wrapper function to train model on common highly variable genes
TrainXGBoost = function(train, test, train.clusters = "", test.clusters = "", features = c()){
  
  Idents(train) = train.clusters
  Idents(test) = test.clusters
  
  AC_model <- TrainModel(train, training_genes = features)
  
  return(AC_model)
}

# Train model
MO_model <- TrainXGBoost(obj.combined.list[["Mouse"]], 
                         obj.combined.list[["Opossum"]], 
                         train.clusters = "type", 
                         test.clusters = "type", 
                         features = rownames(obj.combined.list[["Mouse"]]@assays[["integrated"]]@data))

```

```{r}

source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/xgboost_train.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/plottingFxns.R")

Idents(obj.combined.list[["Opossum"]]) <- "type"
Idents(obj.combined.list[["Mouse"]]) <- "type"
confusion_matrix <- BuildConfusionMatrix(obj.combined.list[["Opossum"]], obj.combined.list[["Mouse"]], model = MO_model)
plotConfusionMatrix(confusion_matrix, plot.return = TRUE, stagger.threshold = 15)

```


```{r}

# Source scripts with functions
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/xgboost_train.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/plottingFxns.R")

Idents(obj.combined.list[["Opossum"]]) <- "type"
Idents(obj.combined.list[["Mouse"]]) <- "type"

# Define a wrapper function to train model on common highly variable genes
TrainXGBoost = function(train, test, train.clusters = "", test.clusters = "", features = c()){
  
  Idents(train) = train.clusters
  Idents(test) = test.clusters
  
  AC_model <- TrainModel(train, training_genes = features)
  
  return(AC_model)
}

# Train model
OM_model <- TrainXGBoost(obj.combined.list[["Opossum"]], 
                         obj.combined.list[["Mouse"]], 
                         train.clusters = "type", 
                         test.clusters = "type", 
                         features = rownames(obj.combined.list[["Mouse"]]@assays[["integrated"]]@data))

```


```{r, fig.height=10, fig.width=6}

source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/xgboost_train.R")
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/xgboost/plottingFxns.R")

Idents(obj.combined.list[["Opossum"]]) <- "type"
Idents(obj.combined.list[["Mouse"]]) <- "type"
confusion_matrix <- BuildConfusionMatrix(obj.combined.list[["Mouse"]], obj.combined.list[["Opossum"]], model = OM_model)
plotConfusionMatrix(confusion_matrix, plot.return = TRUE, stagger.threshold = 15)

```





