---
title: "Opossum M1 GABAergic"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
obj.mouse <- readRDS("E:/Transcriptomics_Retina/Mouse/Mouse_initial.rds")

```


```{r}

obj.mouse <- subset(obj.mouse, subset = nCount_RNA < 40000)
VlnPlot(obj.mouse, features = c("nFeature_RNA"), group.by = "orig.file", raster = FALSE)
VlnPlot(obj.mouse, features = c("nCount_RNA"), group.by = "orig.file", raster = FALSE)
FeatureScatter(obj.mouse, feature1 = "nCount_RNA", feature2 = "nFeature_RNA", raster = FALSE)

```


```{r}

DimPlot(obj.mouse, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse, reduction = "umap", group.by = "orig.file", raster = FALSE, shuffle = TRUE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse, reduction = "umap", group.by = "cell_class", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse, reduction = "umap", group.by = "type", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.mouse, "nFeature_RNA", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.mouse, "nCount_RNA", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

obj.mouse.rgc <- subset(obj.mouse, cell_class == "RGC")
obj.mouse.rgc <- subset(obj.mouse.rgc, type == "Unannotated", invert = TRUE)
obj.mouse.rgc$animal <- NA
obj.mouse.rgc$animal[obj.mouse.rgc$orig.file %in% c("adultRGC1", "adultRGC2")] <- "3"
obj.mouse.rgc$animal[obj.mouse.rgc$orig.file %in% c("adultRGC3", "adultRGC4", "adultRGC5", "adultRGC6")] <- "4"
obj.mouse.rgc$animal[obj.mouse.rgc$orig.file %in% c("adultRGC7", "adultRGC8", "adultRGC9", "adultRGC10")] <- "5"

```


```{r}

DimPlot(obj.mouse.rgc, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.rgc, reduction = "umap", group.by = "animal", raster = FALSE, shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.rgc, reduction = "umap", group.by = "cell_class", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.rgc, reduction = "umap", group.by = "type", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse.rgc, "nFeature_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.mouse.rgc, "nCount_RNA", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

# # SCT Integration
# obj.mouse.rgc.list <- SplitObject(obj.mouse.rgc, split.by = "animal")
# for (i in 1:length(obj.mouse.rgc.list)) {
#       obj.mouse.rgc.list[[i]] <- SCTransform(obj.mouse.rgc.list[[i]], vst.flavor = "v2", return.only.var.genes = FALSE)
# }
# 
# features <- SelectIntegrationFeatures(object.list = obj.mouse.rgc.list, nfeatures = 3000)
# obj.mouse.rgc.list <- PrepSCTIntegration(object.list = obj.mouse.rgc.list, anchor.features = features)
# anchors <- FindIntegrationAnchors(object.list = obj.mouse.rgc.list, normalization.method = "SCT", anchor.features = features)
# features.list <- lapply(obj.mouse.rgc.list, rownames)
# common.features <- intersect(intersect(features.list[[1]], features.list[[2]]), features.list[[3]])
# obj.mouse.rgc.combined <- IntegrateData(anchorset = anchors, normalization.method = "SCT", features.to.integrate = common.features)

# # Old-Fashioned Integration
# obj.mouse.rgc.list <- SplitObject(obj.mouse.rgc, split.by = "animal")
# for (i in 1:length(obj.mouse.rgc.list)) {
#       obj.mouse.rgc.list[[i]] <- NormalizeData(obj.mouse.rgc.list[[i]], verbose = FALSE)
#       obj.mouse.rgc.list[[i]] <- FindVariableFeatures(obj.mouse.rgc.list[[i]], selection.method = "vst", nfeatures = 2000, verbose = FALSE)
# }
# 
# anchors <- FindIntegrationAnchors(object.list = obj.mouse.rgc.list, normalization.method = "LogNormalize", anchor.features = features)
# features.list <- lapply(obj.mouse.rgc.list, rownames)
# common.features <- intersect(intersect(features.list[[1]], features.list[[2]]), features.list[[3]])
# obj.mouse.rgc.combined <- IntegrateData(anchorset = anchors, normalization.method = "LogNormalize", features.to.integrate = common.features)
# obj.mouse.rgc.combined <- ScaleData(obj.mouse.rgc.combined, verbose = FALSE)

```


```{r}

obj.mouse.rgc <- SCTransform(obj.mouse.rgc, vst.flavor = "v2")
obj.mouse.rgc <- RunPCA(obj.mouse.rgc)
obj.mouse.rgc <- FindNeighbors(obj.mouse.rgc, reduction = "pca", dims = 1:30)
obj.mouse.rgc <- FindClusters(obj.mouse.rgc, resolution = 1, algorithm = 4, method = "igraph")
obj.mouse.rgc <- RunUMAP(obj.mouse.rgc, reduction = "pca", dims = 1:30)

```


```{r}

DimPlot(obj.mouse.rgc, reduction = "umap", group.by = "animal", shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.rgc, reduction = "umap", group.by = "cell_class", label = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.rgc, reduction = "umap", group.by = "type", label = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
VlnPlot(obj.mouse.rgc, features = c("nFeature_RNA"), group.by = "type", raster = FALSE)
VlnPlot(obj.mouse.rgc, features = c("nCount_RNA"), group.by = "type", raster = FALSE)

```


```{r}

obj.mouse.rgc.combined <- RunPCA(obj.mouse.rgc.combined)
obj.mouse.rgc.combined <- FindNeighbors(obj.mouse.rgc.combined, reduction = "pca", dims = 1:30)
obj.mouse.rgc.combined <- FindClusters(obj.mouse.rgc.combined, resolution = 1, algorithm = 4, method = "igraph")
obj.mouse.rgc.combined <- RunUMAP(obj.mouse.rgc.combined, reduction = "pca", dims = 1:30)

```


```{r}

DimPlot(obj.mouse.rgc.combined, reduction = "umap", group.by = "animal", shuffle = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.rgc.combined, reduction = "umap", group.by = "cell_class", label = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.mouse.rgc.combined, reduction = "umap", group.by = "type", label = TRUE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
VlnPlot(obj.mouse.rgc.combined, features = c("nFeature_RNA"), group.by = "type", raster = FALSE)
VlnPlot(obj.mouse.rgc.combined, features = c("nCount_RNA"), group.by = "type", raster = FALSE)

```

```{r}

# SaveH5Seurat(obj.mouse.rgc, "E:/Transcriptomics_Retina/Mouse/mouse_retina_rgc.h5seurat", overwrite = TRUE, verbose = TRUE)
saveRDS(obj.mouse.rgc, "E:/Transcriptomics_Retina/Mouse/mouse_retina_rgc_raw.rds")

```

