---
title: "Mouse M1 Object"
output: html_notebook
---

```{r}

library(Seurat)
library(SeuratDisk)
library(reticulate)
library(scrubletR)
library(ggplot2)
library(patchwork)
library(dplyr)
library(data.table)
library(tidyverse)
source("C:/Ryan/GitHub/trachtenberg-lab/transcriptomics/tools/seurat_functions.R")

matrix <- readRDS("E:/Transcriptomics_M1/Mouse/Mouse_M1_10xV3_Matrix.RDS")
meta_tb <- arrow::read_feather("E:/Transcriptomics_M1/Mouse/Mouse_M1_10xV3_Metadata.feather")
meta_df <- as.data.frame(meta_tb)
row.names(meta_df) <- meta_df[, "sample_id"]
obj.mouse <- CreateSeuratObject(counts = matrix, meta.data = meta_df)
rm(list = c("matrix", "meta_df", "meta_tb"))

obj.mouse$species <- "Mouse"

```


```{r}

obj.mouse <- NormalizeData(obj.mouse, normalization.method = "LogNormalize", scale.factor = 10000)
obj.mouse <- FindVariableFeatures(obj.mouse, selection.method = "vst", nfeatures = 3000)
all.genes <- rownames(obj.mouse)
obj.mouse <- ScaleData(obj.mouse, features = all.genes)
obj.mouse <- RunPCA(obj.mouse, features = VariableFeatures(object = obj.mouse))
obj.mouse <- FindNeighbors(obj.mouse, dims = 1:30)
obj.mouse <- FindClusters(obj.mouse, resolution = 1, algorithm = 4, method = "igraph")
obj.mouse <- RunUMAP(obj.mouse, dims = 1:30, method="umap-learn")

```


```{r}

obj.mouse$sample <- obj.mouse$donor_id

obj.mouse$class <- gsub("-", "", tolower(obj.mouse$class_label))

obj.mouse$subclass <- obj.mouse$subclass_label
obj.mouse$subclass[obj.mouse$subclass == "Sst Chodl"] <- "Sst"
obj.mouse$subclass[obj.mouse$subclass == "L6 IT Car3"] <- "L6 IT"
obj.mouse$subclass[obj.mouse$subclass == "L2/3 IT"] <- "L2/3"
obj.mouse$subclass[obj.mouse$subclass == "L5 IT"] <- "L5IT"
obj.mouse$subclass[obj.mouse$subclass == "L5/6 NP"] <- "L5NP"
obj.mouse$subclass[obj.mouse$subclass == "L5 ET"] <- "L5PT"
obj.mouse$subclass[obj.mouse$subclass == "L6 IT"] <- "L6IT"
obj.mouse$subclass[obj.mouse$subclass == "L6 CT"] <- "L6CT"
obj.mouse$subclass[obj.mouse$subclass == "Micro-PVM"] <- "Micro"
obj.mouse$subclass[obj.mouse$subclass == "Oligo"] <- "OD"

obj.mouse$type <- obj.mouse$cluster_label
meta.data <- obj.mouse[[]]
df <- meta.data[,c("subclass", "type")]

# Define the mapping list
mapping <- c("L2/3 IT" = "L2/3", "L5 IT" = "L5IT", "L5/6 NP" = "L5NP", "L5 ET" = "L5PT", "L6 IT" = "L6IT", 
             "L6 CT" = "L6CT", "Micro-PVM" = "Micro", "Oligo" = "OD")

# Function to rename type values within each subclass
rename_types <- function(data) {
  data %>%
    group_by(subclass) %>%
    mutate(
      type = factor(type),
      type_rank = as.numeric(factor(type, levels = names(sort(table(type), decreasing = TRUE)))),
      type = paste0(subclass, "_", LETTERS[type_rank])
    ) %>%
    select(-type_rank) %>%
    ungroup()
}

# Apply the function
df_renamed <- rename_types(df)
obj.mouse$type <- df_renamed$type
obj.mouse$type[obj.mouse$type == "OPC_A"] <- "OPC"
obj.mouse$type[obj.mouse$type == "Peri_A"] <- "Peri"
obj.mouse$type[obj.mouse$type == "SMC_A"] <- "SMC"

```


```{r}

DimPlot(obj.mouse, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse, reduction = "umap", group.by = "sample", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.mouse, "nFeature_RNA", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
FeaturePlot(obj.mouse, "nCount_RNA", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

DimPlot(obj.mouse, reduction = "umap", group.by = "class", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse, reduction = "umap", group.by = "subclass", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.mouse, reduction = "umap", group.by = "type", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

Idents(obj.mouse) <- "class"

obj.mouse.glutamatergic <- subset(obj.mouse, idents = "glutamatergic")
saveRDS(obj.mouse.glutamatergic, "E:/Transcriptomics_M1/Mouse/seurat/mouse_m1_glutamatergic.rds")

obj.mouse.gabaergic <- subset(obj.mouse, idents = "gabaergic")
saveRDS(obj.mouse.gabaergic, "E:/Transcriptomics_M1/Mouse/seurat/mouse_m1_gabaergic.rds")

obj.mouse.nonneuronal <- subset(obj.mouse, idents = "nonneuronal")
saveRDS(obj.mouse.nonneuronal, "E:/Transcriptomics_M1/Mouse/seurat/mouse_m1_nonneuronal.rds")

```

