---
title: "Opossum M1 All"
output: html_notebook
---

```{r}

library(Seurat)
library(reticulate)
library(arrow)
library(ggplot2)
library(dplyr)
library(SeuratDisk)
obj.opossum <- LoadH5Seurat("E:/Transcriptomics_V1/Opossum/seurat/opossum_m1_all.h5Seurat")

```


```{r}

DimPlot(obj.opossum, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.opossum, reduction = "umap", group.by = "sample", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
DimPlot(obj.opossum, reduction = "umap", group.by = "predicted_doublets", raster = FALSE) + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

FeaturePlot(obj.opossum, reduction = "umap", features = c("Snap25"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Gad2"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Csf1r"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Mog"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Pdgfra"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Aldh1l1"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
# FeaturePlot(obj.opossum, reduction = "umap", features = c("Col1a1"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

FeaturePlot(obj.opossum, reduction = "umap", features = c("Slc17a6"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
# FeaturePlot(obj.opossum, reduction = "umap", features = c("Slc17a7"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Gad1"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Lhx6"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Adarb2"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

FeaturePlot(obj.opossum, reduction = "umap", features = c("PVALB"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Sst"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Vip"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Lamp5"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Frem1"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```


```{r}

DefaultAssay(obj.opossum) <- "RNA"

FeaturePlot(obj.opossum, reduction = "umap", features = c("Cux2"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Rorb"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Foxp2"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Deptor"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Nxph1"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Tshz2"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Cdh9"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("Inpp4b"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()
FeaturePlot(obj.opossum, reduction = "umap", features = c("ERG"), raster = FALSE) + NoLegend() + xlim(-18, 18) + ylim(-18, 18) + coord_equal()

```



```{r}

# cells.glutamatergic <- WhichCells(obj.opossum, ident = c(1, 2, 3, 6, 8, 9, 10, 11, 12, 16, 18, 19, 20 ,21, 23, 26 ))
# obj.opossum$class <- ifelse(colnames(obj.opossum) %in% cells.glutamatergic, "glutamatergic", "ambiguous")

cells.gabaergic <- WhichCells(obj.opossum, ident = c(11, 15, 16))
obj.opossum$class[cells.gabaergic] <- "gabaergic"

# cells.nonneuronal <- WhichCells(obj.opossum, ident = c(8, 10, 21, 23, 25, 26, 27, 29))
# obj.opossum$class[cells.nonneuronal] <- "nonneuronal"

```


```{r}

DimPlot(obj.opossum, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 15) + ylim(-15, 15) + coord_equal()
DimPlot(obj.opossum, reduction = "umap", group.by = "class", raster = FALSE) + xlim(-15, 15) + ylim(-15, 15) + coord_equal()

```


```{r}

cells.L23 <- WhichCells(obj.opossum, ident = c(3, 8, 18, 21))
obj.opossum$subclass <- ifelse(colnames(obj.opossum) %in% cells.glutamatergic, "L2/3", "ambiguous")

cells.L4 <- WhichCells(obj.opossum, ident = c(1, 11, 12, 19))
obj.opossum$subclass[cells.L4] <- "L4"

cells.L5IT <- WhichCells(obj.opossum, ident = c(2, 6, 16))
obj.opossum$subclass[cells.L5IT] <- "L5IT"

cells.L5NP <- WhichCells(obj.opossum, ident = c(9))
obj.opossum$subclass[cells.L5NP] <- "L5NP"

cells.L6CT <- WhichCells(obj.opossum, ident = c(10, 23, 26))
obj.opossum$subclass[cells.L6CT] <- "L6CT"

cells.L6IT <- WhichCells(obj.opossum, ident = c(20))
obj.opossum$subclass[cells.L6IT] <- "L6IT"


DimPlot(obj.opossum, reduction = "umap", label = TRUE, raster = FALSE) + NoLegend() + xlim(-15, 12) + ylim(-15, 12) + coord_equal()
DimPlot(obj.opossum, reduction = "umap", group.by = "class", raster = FALSE) + xlim(-15, 12) + ylim(-15, 12) + coord_equal()

```



```{r}

# obj.opossum.glutamatergic <- subset(obj.opossum, subset = class == "glutamatergic")
# SaveH5Seurat(obj.opossum.glutamatergic, "E:/Transcriptomics_V1/Opossum/seurat/opossum_m1_glutamatergic_raw.h5seurat", overwrite = TRUE, verbose = TRUE)

obj.opossum.gabaergic <- subset(obj.opossum, subset = class == "gabaergic")
SaveH5Seurat(obj.opossum.gabaergic, "E:/Transcriptomics_V1/Opossum/seurat/adult_opossum_v1_gabaergic.h5seurat", overwrite = TRUE, verbose = TRUE)

# obj.opossum.nonneuronal <- subset(obj.opossum, subset = class == "nonneuronal")
# SaveH5Seurat(obj.opossum.nonneuronal, "E:/Opossum_M1/seurat/opossum_m1_nonneuronal_raw.h5seurat", overwrite = TRUE, verbose = TRUE)

```

